/** Lista de bancos brasileiros (código ISPB + nome + código de compensação). */
export interface BancoBrasil {
  codigo: string;
  nome: string;
  nomeAbrev: string;
}

export const BANCOS_BRASIL: BancoBrasil[] = [
  { codigo: "001", nome: "Banco do Brasil S.A.", nomeAbrev: "Banco do Brasil" },
  { codigo: "003", nome: "Banco da Amazônia S.A.", nomeAbrev: "Bancoamazônia" },
  { codigo: "004", nome: "Banco do Nordeste do Brasil S.A.", nomeAbrev: "BNB" },
  { codigo: "007", nome: "BNDES - Banco Nacional do Desenvolvimento Econômico e Social", nomeAbrev: "BNDES" },
  { codigo: "010", nome: "Credicoamo Crédito Rural Cooperativa", nomeAbrev: "Credicoamo" },
  { codigo: "011", nome: "Credit Suisse Hedging-Griffo Corretora de Valores S.A.", nomeAbrev: "C6 Bank" },
  { codigo: "012", nome: "Banco Inbursa S.A.", nomeAbrev: "Inbursa" },
  { codigo: "014", nome: "State Street Brasil S.A. – Banco Comercial", nomeAbrev: "State Street" },
  { codigo: "017", nome: "BNY Mellon Banco S.A.", nomeAbrev: "BNY Mellon" },
  { codigo: "018", nome: "Banco Tricury S.A.", nomeAbrev: "Tricury" },
  { codigo: "021", nome: "Banestes S.A. Banco do Estado do Espírito Santo", nomeAbrev: "Banestes" },
  { codigo: "024", nome: "Banco Bandepe S.A.", nomeAbrev: "Bandepe" },
  { codigo: "025", nome: "Banco Alfa S.A.", nomeAbrev: "Banco Alfa" },
  { codigo: "029", nome: "Banco Itaú Consignado S.A.", nomeAbrev: "Itaú Consignado" },
  { codigo: "033", nome: "Banco Santander (Brasil) S.A.", nomeAbrev: "Santander" },
  { codigo: "036", nome: "Banco Bradesco BBI S.A.", nomeAbrev: "Bradesco BBI" },
  { codigo: "037", nome: "Banco do Estado do Pará S.A.", nomeAbrev: "Banpará" },
  { codigo: "040", nome: "Banco Cargill S.A.", nomeAbrev: "Cargill" },
  { codigo: "041", nome: "Banco do Estado do Rio Grande do Sul S.A.", nomeAbrev: "Banrisul" },
  { codigo: "047", nome: "Banco do Estado de Sergipe S.A.", nomeAbrev: "Banese" },
  { codigo: "060", nome: "Confidence Corretora de Câmbio S.A.", nomeAbrev: "Confidence" },
  { codigo: "062", nome: "Hipercard Banco Múltiplo S.A.", nomeAbrev: "Hipercard" },
  { codigo: "063", nome: "Banco Bradescard S.A.", nomeAbrev: "Bradescard" },
  { codigo: "064", nome: "Goldman Sachs do Brasil Banco Múltiplo S.A.", nomeAbrev: "Goldman Sachs" },
  { codigo: "065", nome: "Banco AndBank (Brasil) S.A.", nomeAbrev: "AndBank" },
  { codigo: "066", nome: "Banco Morgan Stanley S.A.", nomeAbrev: "Morgan Stanley" },
  { codigo: "069", nome: "Banco Crefisa S.A.", nomeAbrev: "Crefisa" },
  { codigo: "070", nome: "BRB - Banco de Brasília S.A.", nomeAbrev: "BRB" },
  { codigo: "074", nome: "Banco J. Safra S.A.", nomeAbrev: "Safra" },
  { codigo: "075", nome: "Banco ABN AMRO S.A.", nomeAbrev: "ABN AMRO" },
  { codigo: "076", nome: "Banco KDB do Brasil S.A.", nomeAbrev: "KDB" },
  { codigo: "077", nome: "Banco Inter S.A.", nomeAbrev: "Banco Inter" },
  { codigo: "078", nome: "Haitong Banco de Investimento do Brasil S.A.", nomeAbrev: "Haitong" },
  { codigo: "079", nome: "Banco Original do Agronegócio S.A.", nomeAbrev: "Original Agro" },
  { codigo: "080", nome: "BT Corretora de Câmbio Ltda.", nomeAbrev: "BT Câmbio" },
  { codigo: "081", nome: "BBN Banco Brasileiro de Negócios S.A.", nomeAbrev: "BBN" },
  { codigo: "082", nome: "Banco Topázio S.A.", nomeAbrev: "Topázio" },
  { codigo: "083", nome: "Banco da China Brasil S.A.", nomeAbrev: "Banco da China" },
  { codigo: "084", nome: "Uniprime Norte do Paraná", nomeAbrev: "Uniprime Norte" },
  { codigo: "085", nome: "Cooperativa Central de Crédito - Ailos", nomeAbrev: "Ailos" },
  { codigo: "089", nome: "Cooperativa de Crédito Rural da Região da Mogiana", nomeAbrev: "Credisan" },
  { codigo: "091", nome: "Unicred do Brasil", nomeAbrev: "Unicred" },
  { codigo: "092", nome: "BRK S.A. Crédito, Financiamento e Investimento", nomeAbrev: "BRK" },
  { codigo: "093", nome: "Polocred S.C. Crédito, Financiamento e Investimento", nomeAbrev: "Polocred" },
  { codigo: "094", nome: "Banco Finaxis S.A.", nomeAbrev: "Finaxis" },
  { codigo: "095", nome: "Travelex Banco de Câmbio S.A.", nomeAbrev: "Travelex" },
  { codigo: "096", nome: "Banco B3 S.A.", nomeAbrev: "Banco B3" },
  { codigo: "097", nome: "Credisis - Central de Cooperativas de Crédito Ltda.", nomeAbrev: "Credisis" },
  { codigo: "098", nome: "Credialiança Cooperativa de Crédito Rural", nomeAbrev: "Credialiança" },
  { codigo: "099", nome: "Uniprime Central – Central Interestadual de Cooperativas de Crédito Ltda.", nomeAbrev: "Uniprime Central" },
  { codigo: "100", nome: "Planner Corretora de Valores S.A.", nomeAbrev: "Planner" },
  { codigo: "101", nome: "Renascença Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Renascença" },
  { codigo: "102", nome: "XP Investimentos S.A.", nomeAbrev: "XP Investimentos" },
  { codigo: "104", nome: "Caixa Econômica Federal", nomeAbrev: "Caixa Econômica" },
  { codigo: "105", nome: "Lecca Crédito, Financiamento e Investimento S/A", nomeAbrev: "Lecca" },
  { codigo: "107", nome: "Banco Bocom BBM S.A.", nomeAbrev: "Bocom BBM" },
  { codigo: "108", nome: "PortoCred S.A. Crédito, Financiamento e Investimento", nomeAbrev: "PortoCred" },
  { codigo: "111", nome: "OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "Oliveira Trust" },
  { codigo: "113", nome: "Magliano S.A. Corretora de Câmbio e Valores Mobiliários", nomeAbrev: "Magliano" },
  { codigo: "114", nome: "Central Cooperativa de Crédito no Estado do Espírito Santo (CECOOP)", nomeAbrev: "Cecoop" },
  { codigo: "117", nome: "Advanced Corretora de Câmbio Ltda.", nomeAbrev: "Advanced" },
  { codigo: "119", nome: "Banco Western Union do Brasil S.A.", nomeAbrev: "Western Union" },
  { codigo: "120", nome: "Banco Rodobens S.A.", nomeAbrev: "Rodobens" },
  { codigo: "121", nome: "Banco Agibank S.A.", nomeAbrev: "Agibank" },
  { codigo: "122", nome: "Banco Bradesco BERJ S.A.", nomeAbrev: "Bradesco BERJ" },
  { codigo: "124", nome: "Banco Woori Bank do Brasil S.A.", nomeAbrev: "Woori Bank" },
  { codigo: "125", nome: "Brasil Plural S.A. Banco Múltiplo", nomeAbrev: "Brasil Plural" },
  { codigo: "126", nome: "BR Partners Banco de Investimento S.A.", nomeAbrev: "BR Partners" },
  { codigo: "127", nome: "Codepe Corretora de Valores e Câmbio S.A.", nomeAbrev: "Codepe" },
  { codigo: "128", nome: "MS Bank S.A. Banco de Câmbio", nomeAbrev: "MS Bank" },
  { codigo: "129", nome: "UBS Brasil Banco de Investimento S.A.", nomeAbrev: "UBS Brasil" },
  { codigo: "130", nome: "Caruana S.A. Sociedade de Crédito, Financiamento e Investimento", nomeAbrev: "Caruana" },
  { codigo: "131", nome: "TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA.", nomeAbrev: "Tullett Prebon" },
  { codigo: "132", nome: "ICBC do Brasil Banco Múltiplo S.A.", nomeAbrev: "ICBC" },
  { codigo: "133", nome: "Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar (CRESOL)", nomeAbrev: "Cresol" },
  { codigo: "134", nome: "BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "BGC Liquidez" },
  { codigo: "136", nome: "UNICRED DO BRASIL – CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED", nomeAbrev: "Unicred Brasil" },
  { codigo: "138", nome: "Get Money Corretora de Câmbio S.A.", nomeAbrev: "Get Money" },
  { codigo: "139", nome: "Intesa Sanpaolo Brasil S.A. – Banco Múltiplo", nomeAbrev: "Intesa Sanpaolo" },
  { codigo: "140", nome: "Easynvest – Título Corretora de Valores SA", nomeAbrev: "Easynvest" },
  { codigo: "142", nome: "Broker Brasil Corretora de Câmbio Ltda.", nomeAbrev: "Broker Brasil" },
  { codigo: "143", nome: "Treviso Corretora de Câmbio S.A.", nomeAbrev: "Treviso" },
  { codigo: "144", nome: "BEXS Banco de Câmbio S.A.", nomeAbrev: "Bexs" },
  { codigo: "145", nome: "Levycam – Corretora de Câmbio e Valores Ltda.", nomeAbrev: "Levycam" },
  { codigo: "146", nome: "GUITTA Corretora de Câmbio Ltda.", nomeAbrev: "Guitta" },
  { codigo: "149", nome: "Facta Financeira S.A. – Crédito Financiamento e Investimento", nomeAbrev: "Facta" },
  { codigo: "157", nome: "ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "ICAP" },
  { codigo: "159", nome: "Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor", nomeAbrev: "Casa do Crédito" },
  { codigo: "163", nome: "Commerzbank Brasil S.A. – Banco Múltiplo", nomeAbrev: "Commerzbank" },
  { codigo: "169", nome: "Banco Olé Bonsucesso Consignado S.A.", nomeAbrev: "Olé Bonsucesso" },
  { codigo: "172", nome: "Albatross Corretora de Câmbio e Valores S.A.", nomeAbrev: "Albatross" },
  { codigo: "173", nome: "BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "BRL Trust" },
  { codigo: "174", nome: "Pernambucanas Financiadora S.A. Crédito, Financiamento e Investimento", nomeAbrev: "Pernambucanas" },
  { codigo: "177", nome: "Guide Investimentos S.A. Corretora de Valores", nomeAbrev: "Guide" },
  { codigo: "180", nome: "CM Capital Markets Corretora de Câmbio, Títulos e Valores Mobiliários Ltda.", nomeAbrev: "CM Capital" },
  { codigo: "183", nome: "Socred S.A. – Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte", nomeAbrev: "Socred" },
  { codigo: "184", nome: "Banco Itaú BBA S.A.", nomeAbrev: "Itaú BBA" },
  { codigo: "188", nome: "ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES", nomeAbrev: "Ativa" },
  { codigo: "189", nome: "HS Financeira S.A. Crédito, Financiamento e Investimentos", nomeAbrev: "HS Financeira" },
  { codigo: "190", nome: "Servicoop", nomeAbrev: "Servicoop" },
  { codigo: "191", nome: "Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Nova Futura" },
  { codigo: "194", nome: "Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Parmetal" },
  { codigo: "196", nome: "Fair Corretora de Câmbio S.A.", nomeAbrev: "Fair" },
  { codigo: "197", nome: "Stone Pagamentos S.A.", nomeAbrev: "Stone" },
  { codigo: "208", nome: "Banco BTG Pactual S.A.", nomeAbrev: "BTG Pactual" },
  { codigo: "212", nome: "Banco Original S.A.", nomeAbrev: "Banco Original" },
  { codigo: "213", nome: "Banco Arbi S.A.", nomeAbrev: "Arbi" },
  { codigo: "217", nome: "Banco John Deere S.A.", nomeAbrev: "John Deere" },
  { codigo: "218", nome: "Banco BS2 S.A.", nomeAbrev: "BS2" },
  { codigo: "222", nome: "Banco Credit Agricole Brasil S.A.", nomeAbrev: "Crédit Agricole" },
  { codigo: "224", nome: "Banco Fibra S.A.", nomeAbrev: "Fibra" },
  { codigo: "225", nome: "Banco Brascan S.A.", nomeAbrev: "Brascan" },
  { codigo: "229", nome: "Banco Cruzeiro do Sul S.A.", nomeAbrev: "Cruzeiro do Sul" },
  { codigo: "230", nome: "Unicard Banco Múltiplo S.A.", nomeAbrev: "Unicard" },
  { codigo: "233", nome: "Banco Cifra S.A.", nomeAbrev: "Cifra" },
  { codigo: "237", nome: "Banco Bradesco S.A.", nomeAbrev: "Bradesco" },
  { codigo: "241", nome: "Banco Clássico S.A.", nomeAbrev: "Clássico" },
  { codigo: "243", nome: "Banco Máxima S.A.", nomeAbrev: "Máxima" },
  { codigo: "246", nome: "Banco ABC Brasil S.A.", nomeAbrev: "ABC Brasil" },
  { codigo: "249", nome: "Banco Investcred Unibanco S.A.", nomeAbrev: "Investcred" },
  { codigo: "250", nome: "BCV – Banco de Crédito e Varejo S/A", nomeAbrev: "BCV" },
  { codigo: "253", nome: "Bexs Corretora de Câmbio S/A", nomeAbrev: "Bexs Câmbio" },
  { codigo: "254", nome: "Parana Banco S.A.", nomeAbrev: "Paraná Banco" },
  { codigo: "259", nome: "Moneycorp Banco de Câmbio S.A.", nomeAbrev: "Moneycorp" },
  { codigo: "260", nome: "Nu Pagamentos S.A. (Nubank)", nomeAbrev: "Nubank" },
  { codigo: "265", nome: "Banco Fator S.A.", nomeAbrev: "Fator" },
  { codigo: "266", nome: "Banco Cédula S.A.", nomeAbrev: "Cédula" },
  { codigo: "268", nome: "Barigui Companhia Hipotecária", nomeAbrev: "Barigui" },
  { codigo: "269", nome: "HSBC Brasil S.A. – Banco de Investimento", nomeAbrev: "HSBC Brasil" },
  { codigo: "270", nome: "Sagitur Corretora de Câmbio Ltda.", nomeAbrev: "Sagitur" },
  { codigo: "271", nome: "IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.", nomeAbrev: "IB Corretora" },
  { codigo: "272", nome: "Agência de Fomento do Estado de Santa Catarina S.A.", nomeAbrev: "Badesc" },
  { codigo: "273", nome: "Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel", nomeAbrev: "Sulcredi" },
  { codigo: "274", nome: "MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LTDA.", nomeAbrev: "Money Plus" },
  { codigo: "276", nome: "Banco Senff S.A.", nomeAbrev: "Senff" },
  { codigo: "278", nome: "Genial Investimentos Corretora de Valores Mobiliários S.A.", nomeAbrev: "Genial" },
  { codigo: "279", nome: "Cooperativa de Credito Rural de Primavera Do Leste", nomeAbrev: "Primacredi" },
  { codigo: "280", nome: "Avista S.A. Crédito, Financiamento e Investimento", nomeAbrev: "Avista" },
  { codigo: "281", nome: "Cooperativa de Crédito Rural Coopavel", nomeAbrev: "Coopavel" },
  { codigo: "283", nome: "RB Capital Investimentos Distribuidora de Títulos e Valores Mobiliários Limitada", nomeAbrev: "RB Capital" },
  { codigo: "285", nome: "Frente Corretora de Câmbio Ltda.", nomeAbrev: "Frente" },
  { codigo: "286", nome: "Cooperativa de Crédito Rural de Ouro – Sulcredi/Ouro", nomeAbrev: "Sulcredi/Ouro" },
  { codigo: "288", nome: "CAROL Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Carol" },
  { codigo: "289", nome: "U.S. Bancorp", nomeAbrev: "U.S. Bancorp" },
  { codigo: "290", nome: "Pagseguro Internet S.A.", nomeAbrev: "PagSeguro" },
  { codigo: "292", nome: "BS2 Distribuidora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "BS2 DTVM" },
  { codigo: "293", nome: "Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Lastro RDV" },
  { codigo: "296", nome: "VISION S.A. CORRETORA DE CAMBIO", nomeAbrev: "Vision" },
  { codigo: "298", nome: "Vip's Corretora de Câmbio Ltda.", nomeAbrev: "Vip's" },
  { codigo: "299", nome: "SOROCRED – CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A", nomeAbrev: "Sorocred" },
  { codigo: "300", nome: "Banco de la Nación Argentina", nomeAbrev: "Nación Argentina" },
  { codigo: "301", nome: "BPP Instituição de Pagamentos S.A.", nomeAbrev: "BPP" },
  { codigo: "306", nome: "Portopar Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Portopar" },
  { codigo: "307", nome: "Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.", nomeAbrev: "Terra" },
  { codigo: "309", nome: "Cambionet Corretora de Câmbio Ltda.", nomeAbrev: "Cambionet" },
  { codigo: "310", nome: "VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.", nomeAbrev: "Vortx" },
  { codigo: "315", nome: "PI Distribuidora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "PI DTVM" },
  { codigo: "318", nome: "Banco BMG S.A.", nomeAbrev: "BMG" },
  { codigo: "320", nome: "China Construction Bank (Brasil) Banco Múltiplo S/A", nomeAbrev: "CCB Brasil" },
  { codigo: "321", nome: "Crefaz Sociedade de Crédito ao Microempreendedor e a Empresa de Pequeno Porte LTDA", nomeAbrev: "Crefaz" },
  { codigo: "322", nome: "Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz", nomeAbrev: "Crediluz" },
  { codigo: "323", nome: "Mercado Pago", nomeAbrev: "Mercado Pago" },
  { codigo: "324", nome: "Cartos Sociedade de Crédito Direto S.A.", nomeAbrev: "Cartos" },
  { codigo: "325", nome: "Órama Distribuidora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "Órama" },
  { codigo: "326", nome: "PARATI – CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.", nomeAbrev: "Parati" },
  { codigo: "328", nome: "Cooperativa de Economia e Crédito Mútuo dos Fabricantes de Calçados de Sapiranga", nomeAbrev: "Cecm Fabricantes" },
  { codigo: "329", nome: "QI Sociedade de Crédito Direto S.A.", nomeAbrev: "QI SCD" },
  { codigo: "330", nome: "Banca Pueyo S.A.", nomeAbrev: "Banca Pueyo" },
  { codigo: "331", nome: "Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "Fram Capital" },
  { codigo: "332", nome: "Acesso Soluções de Pagamento S.A.", nomeAbrev: "Acesso" },
  { codigo: "335", nome: "Banco Digio S.A.", nomeAbrev: "Digio" },
  { codigo: "336", nome: "Banco C6 S.A.", nomeAbrev: "C6 Bank" },
  { codigo: "340", nome: "Super Pagamentos e Administração de Meios Eletrônicos S.A.", nomeAbrev: "Super Pagamentos" },
  { codigo: "341", nome: "Itaú Unibanco S.A.", nomeAbrev: "Itaú" },
  { codigo: "342", nome: "Creditas Sociedade de Crédito Direto S.A.", nomeAbrev: "Creditas" },
  { codigo: "343", nome: "FFA – Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.", nomeAbrev: "FFA" },
  { codigo: "348", nome: "Banco XP S.A.", nomeAbrev: "Banco XP" },
  { codigo: "349", nome: "ALYMENTE SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Alymente" },
  { codigo: "350", nome: "Cooperativa De Crédito Rural De Pequenos Agricultores E Da Reforma Agrária Do Centro-Oeste", nomeAbrev: "Crehnor" },
  { codigo: "352", nome: "TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Toro" },
  { codigo: "354", nome: "Necton Investimentos S.A. Corretora de Valores Mobiliários e Commodities", nomeAbrev: "Necton" },
  { codigo: "355", nome: "ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Ótimo" },
  { codigo: "356", nome: "Banco Real S.A.", nomeAbrev: "Banco Real" },
  { codigo: "359", nome: "ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A", nomeAbrev: "Zema" },
  { codigo: "360", nome: "Trinus Capital Distribuidora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "Trinus" },
  { codigo: "362", nome: "CIELO S.A.", nomeAbrev: "Cielo" },
  { codigo: "363", nome: "Singulare Corretora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "Singulare" },
  { codigo: "364", nome: "GERENCIANET PAGAMENTOS DO BRASIL LTDA", nomeAbrev: "Gerencianet" },
  { codigo: "365", nome: "SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS", nomeAbrev: "Solidus" },
  { codigo: "366", nome: "Banco Société Générale Brasil S.A.", nomeAbrev: "Société Générale" },
  { codigo: "368", nome: "Banco CSF S.A.", nomeAbrev: "Carrefour" },
  { codigo: "370", nome: "Banco Mizuho do Brasil S.A.", nomeAbrev: "Mizuho" },
  { codigo: "371", nome: "Warren Corretora de Valores Mobiliários e Câmbio Ltda.", nomeAbrev: "Warren" },
  { codigo: "372", nome: "UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.", nomeAbrev: "Up.p" },
  { codigo: "373", nome: "UP Corretora de Câmbio S.A.", nomeAbrev: "UP Câmbio" },
  { codigo: "374", nome: "REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.", nomeAbrev: "Realize" },
  { codigo: "375", nome: "Banco Fenicia S.A.", nomeAbrev: "Fenicia" },
  { codigo: "376", nome: "Banco J. P. Morgan S.A.", nomeAbrev: "J.P. Morgan" },
  { codigo: "377", nome: "BMS Sociedade de Crédito Direto S.A.", nomeAbrev: "BMS SCD" },
  { codigo: "378", nome: "BBC LEASING S.A. – ARRENDAMENTO MERCANTIL", nomeAbrev: "BBC Leasing" },
  { codigo: "379", nome: "CECM dos Empregados e Servidores da Saúde, Educação, Cultura e Assistência Social", nomeAbrev: "Cecm Saúde" },
  { codigo: "380", nome: "PicPay Serviços S.A.", nomeAbrev: "PicPay" },
  { codigo: "381", nome: "Banco Mercedes-Benz do Brasil S.A.", nomeAbrev: "Mercedes-Benz" },
  { codigo: "382", nome: "FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.", nomeAbrev: "Fidúcia" },
  { codigo: "383", nome: "EBANX INSTITUIÇÃO DE PAGAMENTOS LTDA.", nomeAbrev: "Ebanx" },
  { codigo: "384", nome: "GLOBAL SCM S.A. SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR", nomeAbrev: "Global SCM" },
  { codigo: "385", nome: "Cooperativa de Economia e Crédito Mútuo dos Empregados de Empresas do Grupo Hipercard", nomeAbrev: "Cecm Hipercard" },
  { codigo: "386", nome: "Nu Financeira S.A. – Sociedade de Crédito, Financiamento e Investimento", nomeAbrev: "Nu Financeira" },
  { codigo: "387", nome: "Banco Toyota do Brasil S.A.", nomeAbrev: "Toyota" },
  { codigo: "389", nome: "Banco Mercantil do Brasil S.A.", nomeAbrev: "Mercantil do Brasil" },
  { codigo: "390", nome: "CAMINHOS COOPERATIVA DE CRÉDITO", nomeAbrev: "Caminhos" },
  { codigo: "391", nome: "COOPERATIVA DE CRÉDITO RURAL DE IBIAM – SULCREDI/IBIAM", nomeAbrev: "Sulcredi/Ibiam" },
  { codigo: "393", nome: "Banco Volkswagen S.A.", nomeAbrev: "Volkswagen" },
  { codigo: "394", nome: "Banco Bradesco Financiamentos S.A.", nomeAbrev: "Bradesco Financiamentos" },
  { codigo: "395", nome: "F.D'GOLD – DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "F.D'Gold" },
  { codigo: "396", nome: "HUB INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Hub IP" },
  { codigo: "397", nome: "LAQUS PARTICIPAÇÕES S.A.", nomeAbrev: "Laqus" },
  { codigo: "398", nome: "Ideal Corretora de Títulos e Valores Mobiliários S.A.", nomeAbrev: "Ideal" },
  { codigo: "399", nome: "Kirton Bank S.A. – Banco Múltiplo", nomeAbrev: "Kirton" },
  { codigo: "400", nome: "COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO-OESTE", nomeAbrev: "Cecoop Centro-Oeste" },
  { codigo: "401", nome: "IUGU INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Iugu" },
  { codigo: "402", nome: "COBUCCIO SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Cobuccio" },
  { codigo: "403", nome: "CORA SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Cora" },
  { codigo: "404", nome: "SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "SumUp" },
  { codigo: "406", nome: "ACCREDITO – SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Accredito" },
  { codigo: "408", nome: "BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Bonuspago" },
  { codigo: "410", nome: "PLANNER SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Planner SCD" },
  { codigo: "411", nome: "Via Certa Financiadora S.A. – Crédito, Financiamento e Investimentos", nomeAbrev: "Via Certa" },
  { codigo: "412", nome: "SOCIAL BANK BANCO MÚLTIPLO S/A", nomeAbrev: "Social Bank" },
  { codigo: "413", nome: "BANCO BV S.A.", nomeAbrev: "BV" },
  { codigo: "414", nome: "WORK SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Work" },
  { codigo: "415", nome: "LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Lamara" },
  { codigo: "416", nome: "CRED-UFES – Cooperativa de Crédito dos Servidores da Universidade Federal do Espírito Santo", nomeAbrev: "Cred-Ufes" },
  { codigo: "418", nome: "ZIPDIN SOLUÇÕES DIGITAIS SOCIEDADE DE CRÉDITO DIRETO S/A", nomeAbrev: "Zipdin" },
  { codigo: "419", nome: "NUMBRS PERSONAL FINANCE S.A.", nomeAbrev: "Numbrs" },
  { codigo: "421", nome: "LAR COOPERATIVA DE CRÉDITO – LAR CREDI", nomeAbrev: "Lar Credi" },
  { codigo: "422", nome: "Banco Safra S.A.", nomeAbrev: "Banco Safra" },
  { codigo: "423", nome: "COLUNA S/A DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS", nomeAbrev: "Coluna" },
  { codigo: "425", nome: "SOCINAL S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "Socinal" },
  { codigo: "426", nome: "BIORC FINANCEIRA – CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.", nomeAbrev: "Biorc" },
  { codigo: "427", nome: "Coop. de Crédito dos Servidores Públicos do Estado de Minas Gerais", nomeAbrev: "Credihab" },
  { codigo: "428", nome: "CREDSYSTEM SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Credsystem" },
  { codigo: "429", nome: "CREDIARE S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "Crediare" },
  { codigo: "430", nome: "COOPERATIVA DE CRÉDITO RURAL SEARA – CREDISEARA", nomeAbrev: "Crediseara" },
  { codigo: "433", nome: "BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "BR-Capital" },
  { codigo: "435", nome: "DELCRED SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Delcred" },
  { codigo: "436", nome: "PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Planner Trustee" },
  { codigo: "438", nome: "TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Trustee" },
  { codigo: "439", nome: "ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "ID Corretora" },
  { codigo: "440", nome: "CREDIBRF COOPERATIVA DE CRÉDITO", nomeAbrev: "Credibrf" },
  { codigo: "441", nome: "MAGNETIS – DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Magnetis" },
  { codigo: "443", nome: "CREDIHAB COOPERATIVA DE CRÉDITO HABITACIONAL", nomeAbrev: "Credihab" },
  { codigo: "444", nome: "TRINUS SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Trinus SCD" },
  { codigo: "445", nome: "PLANTAE S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "Plantae" },
  { codigo: "447", nome: "MIRAE ASSET WEALTH MANAGEMENT (BRAZIL) CCTVM LTDA.", nomeAbrev: "Mirae Asset" },
  { codigo: "448", nome: "HEMERA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Hemera" },
  { codigo: "449", nome: "DMCARD SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Dmcard" },
  { codigo: "450", nome: "FITBANK PAGAMENTOS ELETRÔNICOS S.A.", nomeAbrev: "Fitbank" },
  { codigo: "451", nome: "J17 – SOCIEDADE DE CRÉDITO DIRETO S/A", nomeAbrev: "J17" },
  { codigo: "452", nome: "CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Credifit" },
  { codigo: "453", nome: "MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Mérito" },
  { codigo: "454", nome: "MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Mérito DTVM" },
  { codigo: "455", nome: "FÊNIX DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Fênix" },
  { codigo: "456", nome: "Banco MUFG Brasil S.A.", nomeAbrev: "MUFG" },
  { codigo: "457", nome: "UY3 SOCIEDADE DE CRÉDITO DIRETO S/A", nomeAbrev: "UY3" },
  { codigo: "458", nome: "HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Hedge" },
  { codigo: "459", nome: "CIP COOPERATIVA DE CRÉDITO", nomeAbrev: "CIP Coop" },
  { codigo: "460", nome: "UNAVANTI SOCIEDADE DE CRÉDITO DIRETO S/A", nomeAbrev: "Unavanti" },
  { codigo: "461", nome: "ASAAS GESTÃO FINANCEIRA INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Asaas" },
  { codigo: "462", nome: "STARK SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Stark" },
  { codigo: "463", nome: "AZUMI DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Azumi" },
  { codigo: "464", nome: "Banco Sumitomo Mitsui Brasileiro S.A.", nomeAbrev: "Sumitomo Mitsui" },
  { codigo: "465", nome: "CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Capital Consig" },
  { codigo: "467", nome: "MASTER S/A CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS", nomeAbrev: "Master Câmbio" },
  { codigo: "468", nome: "PORTOSEG S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "Portoseg" },
  { codigo: "469", nome: "PICPAY BANK – BANCO MÚLTIPLO S.A.", nomeAbrev: "PicPay Bank" },
  { codigo: "470", nome: "CDC SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.", nomeAbrev: "CDC" },
  { codigo: "471", nome: "COOPERATIVA DE CRÉDITO RURAL DE SÃO MIGUEL DO OESTE", nomeAbrev: "Cocredi" },
  { codigo: "473", nome: "Banco Caixa Geral – Brasil S.A.", nomeAbrev: "Caixa Geral" },
  { codigo: "477", nome: "Citibank N.A.", nomeAbrev: "Citibank" },
  { codigo: "478", nome: "Banco Itaubank S.A.", nomeAbrev: "Itaubank" },
  { codigo: "481", nome: "SUPERLÓGICA SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Superlógica" },
  { codigo: "482", nome: "SBCASH SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "SBCash" },
  { codigo: "484", nome: "MAF DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "MAF" },
  { codigo: "485", nome: "CREDISIS – CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.", nomeAbrev: "Credisis Central" },
  { codigo: "487", nome: "Deutsche Bank S.A. – Banco Alemão", nomeAbrev: "Deutsche Bank" },
  { codigo: "488", nome: "JPMorgan Chase Bank, National Association", nomeAbrev: "JPMorgan Chase" },
  { codigo: "492", nome: "ING Bank N.V.", nomeAbrev: "ING" },
  { codigo: "494", nome: "Banco Rep. Oriental del Uruguay", nomeAbrev: "Banco Uruguai" },
  { codigo: "495", nome: "Banco de la Republica Oriental del Uruguay", nomeAbrev: "Banco Uruguay" },
  { codigo: "505", nome: "Banco Credit Suisse (Brasil) S.A.", nomeAbrev: "Credit Suisse" },
  { codigo: "506", nome: "RBERJ SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "RBerj" },
  { codigo: "507", nome: "SACON COOPERATIVA DE CRÉDITO", nomeAbrev: "Sacon" },
  { codigo: "508", nome: "AVENUE SECURITIES DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "Avenue" },
  { codigo: "509", nome: "CELCOIN INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Celcoin" },
  { codigo: "510", nome: "FFCRED SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "FFcred" },
  { codigo: "511", nome: "MAGNUM SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Magnum" },
  { codigo: "512", nome: "CAPITUAL – INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Capitual" },
  { codigo: "513", nome: "ATF CAPITAL SCD S.A.", nomeAbrev: "ATF Capital" },
  { codigo: "514", nome: "EXIM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Exim" },
  { codigo: "516", nome: "QISTA S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "Qista" },
  { codigo: "517", nome: "VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "Vitreo" },
  { codigo: "518", nome: "MERCADO CRÉDITO SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.", nomeAbrev: "Mercado Crédito" },
  { codigo: "519", nome: "LIONS TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Lions Trust" },
  { codigo: "520", nome: "SOMAPAY SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Somapay" },
  { codigo: "521", nome: "PEAK SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.", nomeAbrev: "Peak" },
  { codigo: "522", nome: "RED SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Red" },
  { codigo: "523", nome: "HR DIGITAL SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "HR Digital" },
  { codigo: "524", nome: "LEVE SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Leve" },
  { codigo: "525", nome: "INTERCAM CORRETORA DE CÂMBIO LTDA.", nomeAbrev: "Intercam" },
  { codigo: "526", nome: "NUMBRS PERSONAL FINANCE S.A.", nomeAbrev: "Numbrs" },
  { codigo: "527", nome: "ATICCA – SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Aticca" },
  { codigo: "528", nome: "REAG DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "Reag" },
  { codigo: "529", nome: "PINBANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Pinbank" },
  { codigo: "530", nome: "SER FINANCE SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Ser Finance" },
  { codigo: "531", nome: "BMP SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.", nomeAbrev: "BMP" },
  { codigo: "532", nome: "EAGLE SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Eagle" },
  { codigo: "533", nome: "SRM BANK – INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "SRM Bank" },
  { codigo: "534", nome: "EWALLY INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Ewally" },
  { codigo: "535", nome: "OPEA SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Opea" },
  { codigo: "536", nome: "NEON PAGAMENTOS S.A.", nomeAbrev: "Neon" },
  { codigo: "537", nome: "MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.", nomeAbrev: "Microcash" },
  { codigo: "538", nome: "SUDACRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.", nomeAbrev: "Sudacred" },
  { codigo: "539", nome: "SANTINVEST S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTOS", nomeAbrev: "Santinvest" },
  { codigo: "540", nome: "HBI FINANCEIRA S.A. CRÉDITO FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "HBI" },
  { codigo: "541", nome: "FUNDO GARANTIDOR DE CRÉDITOS", nomeAbrev: "FGC" },
  { codigo: "542", nome: "CLOUDWALK INSTITUIÇÃO DE PAGAMENTO E SERVICOS LTDA.", nomeAbrev: "CloudWalk" },
  { codigo: "543", nome: "COOPERATIVA DE CREDITO DOS SERVIDORES MUNICIPAIS DE PATOS DE MINAS", nomeAbrev: "Coopeser" },
  { codigo: "544", nome: "MULTICREDITO SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Multicredito" },
  { codigo: "545", nome: "SENSO CORRETORA DE CÂMBIO E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "Senso" },
  { codigo: "546", nome: "U4C INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "U4C" },
  { codigo: "547", nome: "COOP. DE CRÉDITO DOS PROFISSIONAIS DE SAÚDE DA ÁREA DA ABRANGÊNCIA DA AMREC", nomeAbrev: "Coop Saúde Amrec" },
  { codigo: "548", nome: "RPW S.A. SOCIEDADE DE CRÉDITO DIRETO", nomeAbrev: "RPW" },
  { codigo: "549", nome: "AGROCONSULT DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Agroconsult" },
  { codigo: "550", nome: "BEETELLER INSTITUIÇÃO DE PAGAMENTO LTDA.", nomeAbrev: "Beeteller" },
  { codigo: "551", nome: "NU INVEST CORRETORA DE VALORES S.A.", nomeAbrev: "NuInvest" },
  { codigo: "552", nome: "MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Mérito DTVM" },
  { codigo: "556", nome: "AGORA CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "Ágora" },
  { codigo: "559", nome: "KOIN MEIOS DE PAGAMENTO S.A.", nomeAbrev: "Koin" },
  { codigo: "560", nome: "MAF DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", nomeAbrev: "MAF DTVM" },
  { codigo: "561", nome: "PAY4FUN INSTITUIÇÃO DE PAGAMENTO S.A.", nomeAbrev: "Pay4Fun" },
  { codigo: "562", nome: "AZIMUT BRASIL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", nomeAbrev: "Azimut" },
  { codigo: "563", nome: "PROTEGE PAY SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Protege Pay" },
  { codigo: "564", nome: "PJBANK FINANCEIRA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO", nomeAbrev: "PJBank" },
  { codigo: "568", nome: "CONTA SIMPLES SOCIEDADE DE CRÉDITO DIRETO S.A.", nomeAbrev: "Conta Simples" },
  { codigo: "569", nome: "CONTA CORRENTE DIGITAL LTDA.", nomeAbrev: "Conta Corrente Digital" },
  { codigo: "571", nome: "CAMCRED COOPERATIVA DE CRÉDITO DAS REGIÕES DAS AMÉRICAS E CARIBE", nomeAbrev: "Camcred" },
  { codigo: "600", nome: "Banco Luso Brasileiro S.A.", nomeAbrev: "Luso Brasileiro" },
  { codigo: "604", nome: "Banco Industrial do Brasil S.A.", nomeAbrev: "Industrial do Brasil" },
  { codigo: "610", nome: "Banco VR S.A.", nomeAbrev: "Banco VR" },
  { codigo: "611", nome: "Banco Paulista S.A.", nomeAbrev: "Banco Paulista" },
  { codigo: "612", nome: "Banco Guanabara S.A.", nomeAbrev: "Guanabara" },
  { codigo: "613", nome: "Omni Banco S.A.", nomeAbrev: "Omni" },
  { codigo: "623", nome: "Banco Pan S.A.", nomeAbrev: "Banco Pan" },
  { codigo: "626", nome: "Banco C6 Consignado S.A.", nomeAbrev: "C6 Consignado" },
  { codigo: "630", nome: "Banco Smartbank S.A.", nomeAbrev: "Smartbank" },
  { codigo: "633", nome: "Banco Rendimento S.A.", nomeAbrev: "Rendimento" },
  { codigo: "634", nome: "Banco Triângulo S.A.", nomeAbrev: "Triângulo" },
  { codigo: "637", nome: "Banco Sofisa S.A.", nomeAbrev: "Sofisa" },
  { codigo: "643", nome: "Banco Pine S.A.", nomeAbrev: "Pine" },
  { codigo: "652", nome: "Itaú Unibanco Holding S.A.", nomeAbrev: "Itaú Holding" },
  { codigo: "653", nome: "Banco Indusval S.A.", nomeAbrev: "Indusval" },
  { codigo: "654", nome: "Banco A.J. Renner S.A.", nomeAbrev: "A.J. Renner" },
  { codigo: "655", nome: "Banco Votorantim S.A.", nomeAbrev: "Votorantim" },
  { codigo: "707", nome: "Banco Daycoval S.A.", nomeAbrev: "Daycoval" },
  { codigo: "712", nome: "Banco Ourinvest S.A.", nomeAbrev: "Ourinvest" },
  { codigo: "720", nome: "Banco RNX S.A.", nomeAbrev: "RNX" },
  { codigo: "739", nome: "Banco Cetelem S.A.", nomeAbrev: "Cetelem" },
  { codigo: "741", nome: "Banco Ribeirão Preto S.A.", nomeAbrev: "Ribeirão Preto" },
  { codigo: "743", nome: "Banco Semear S.A.", nomeAbrev: "Semear" },
  { codigo: "745", nome: "Banco Citibank S.A.", nomeAbrev: "Citibank" },
  { codigo: "746", nome: "Banco Modal S.A.", nomeAbrev: "Modal" },
  { codigo: "747", nome: "Banco Rabobank International Brasil S.A.", nomeAbrev: "Rabobank" },
  { codigo: "748", nome: "Banco Cooperativo Sicredi S.A.", nomeAbrev: "Sicredi" },
  { codigo: "751", nome: "Scotiabank Brasil S.A. Banco Múltiplo", nomeAbrev: "Scotiabank" },
  { codigo: "752", nome: "Banco BNP Paribas Brasil S.A.", nomeAbrev: "BNP Paribas" },
  { codigo: "753", nome: "Novo Banco Continental S.A. – Banco Múltiplo", nomeAbrev: "Novo Continental" },
  { codigo: "754", nome: "Banco Sistema S.A.", nomeAbrev: "Sistema" },
  { codigo: "755", nome: "Bank of America Merrill Lynch Banco Múltiplo S.A.", nomeAbrev: "Bank of America" },
  { codigo: "756", nome: "Banco Cooperativo do Brasil S.A. – Bancoob", nomeAbrev: "Sicoob" },
  { codigo: "757", nome: "Banco KEB Hana do Brasil S.A.", nomeAbrev: "KEB Hana" },
];

/** Retorna "Código — Nome Abreviado" para exibição no campo. */
export function formatarBanco(b: BancoBrasil): string {
  return `${b.codigo} — ${b.nomeAbrev}`;
}

/** Busca bancos por texto (filtra por código, nome abreviado e nome completo). */
export function buscarBancos(texto: string): BancoBrasil[] {
  if (!texto.trim()) return BANCOS_BRASIL;
  const t = texto.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  return BANCOS_BRASIL.filter(b => {
    const cod = b.codigo.toLowerCase();
    const abrev = b.nomeAbrev.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    const nome = b.nome.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return cod.includes(t) || abrev.includes(t) || nome.includes(t);
  });
}
