-- Recreate 5 tables with camelCase column names matching Drizzle schema

CREATE TABLE IF NOT EXISTS `termination_notices` (
  `id` int AUTO_INCREMENT NOT NULL,
  `companyId` int NOT NULL,
  `employeeId` int NOT NULL,
  `tipo` enum('empregador_trabalhado','empregador_indenizado','empregado_trabalhado','empregado_indenizado') NOT NULL,
  `dataInicio` date NOT NULL,
  `dataFim` date NOT NULL,
  `diasAviso` int NOT NULL DEFAULT 30,
  `anosServico` int DEFAULT 0,
  `reducaoJornada` enum('2h_dia','7_dias_corridos','nenhuma') DEFAULT 'nenhuma',
  `salarioBase` varchar(20),
  `previsaoRescisao` text,
  `valorEstimadoTotal` varchar(20),
  `status` enum('em_andamento','concluido','cancelado') NOT NULL DEFAULT 'em_andamento',
  `dataConclusao` date,
  `motivoCancelamento` text,
  `observacoes` text,
  `criadoPor` varchar(255),
  `criadoPorUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` timestamp NULL,
  `deletedBy` varchar(255),
  `deletedByUserId` int,
  PRIMARY KEY (`id`),
  INDEX `tn_company` (`companyId`),
  INDEX `tn_employee` (`employeeId`),
  INDEX `tn_status` (`status`)
);

CREATE TABLE IF NOT EXISTS `vacation_periods` (
  `id` int AUTO_INCREMENT NOT NULL,
  `companyId` int NOT NULL,
  `employeeId` int NOT NULL,
  `periodoAquisitivoInicio` date NOT NULL,
  `periodoAquisitivoFim` date NOT NULL,
  `periodoConcessivoFim` date NOT NULL,
  `dataInicio` date,
  `dataFim` date,
  `diasGozo` int DEFAULT 30,
  `fracionamento` int DEFAULT 1,
  `periodo2Inicio` date,
  `periodo2Fim` date,
  `periodo3Inicio` date,
  `periodo3Fim` date,
  `abonoPecuniario` tinyint DEFAULT 0,
  `valorFerias` varchar(20),
  `valorTercoConstitucional` varchar(20),
  `valorAbono` varchar(20),
  `valorTotal` varchar(20),
  `dataPagamento` date,
  `status` enum('pendente','agendada','em_gozo','concluida','vencida','cancelada') NOT NULL DEFAULT 'pendente',
  `vencida` tinyint DEFAULT 0,
  `pagamentoEmDobro` tinyint DEFAULT 0,
  `observacoes` text,
  `aprovadoPor` varchar(255),
  `aprovadoPorUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` timestamp NULL,
  `deletedBy` varchar(255),
  `deletedByUserId` int,
  PRIMARY KEY (`id`),
  INDEX `vp_company` (`companyId`),
  INDEX `vp_employee` (`employeeId`),
  INDEX `vp_status` (`status`),
  INDEX `vp_concessivo` (`periodoConcessivoFim`)
);

CREATE TABLE IF NOT EXISTS `cipa_meetings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `mandateId` int NOT NULL,
  `companyId` int NOT NULL,
  `tipo` enum('ordinaria','extraordinaria') NOT NULL DEFAULT 'ordinaria',
  `dataReuniao` date NOT NULL,
  `horaInicio` varchar(10),
  `horaFim` varchar(10),
  `local` varchar(255),
  `pauta` text,
  `ataTexto` text,
  `ataDocumentoUrl` text,
  `presentesJson` text,
  `status` enum('agendada','realizada','cancelada') NOT NULL DEFAULT 'agendada',
  `observacoes` text,
  `criadoPor` varchar(255),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `cmt_mandate` (`mandateId`),
  INDEX `cmt_company` (`companyId`),
  INDEX `cmt_data` (`dataReuniao`)
);

CREATE TABLE IF NOT EXISTS `pj_contracts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `companyId` int NOT NULL,
  `employeeId` int NOT NULL,
  `numeroContrato` varchar(50),
  `cnpjPrestador` varchar(20),
  `razaoSocialPrestador` varchar(255),
  `objetoContrato` text,
  `dataInicio` date NOT NULL,
  `dataFim` date NOT NULL,
  `renovacaoAutomatica` tinyint DEFAULT 0,
  `valorMensal` varchar(20),
  `percentualAdiantamento` int DEFAULT 40,
  `percentualFechamento` int DEFAULT 60,
  `diaAdiantamento` int DEFAULT 15,
  `diaFechamento` int DEFAULT 5,
  `modeloContratoUrl` text,
  `contratoAssinadoUrl` text,
  `tipoAssinatura` enum('manual','digital','pendente') DEFAULT 'pendente',
  `status` enum('ativo','vencido','renovado','cancelado','pendente_assinatura') NOT NULL DEFAULT 'pendente_assinatura',
  `alertaVencimentoEnviado` tinyint DEFAULT 0,
  `contratoAnteriorId` int,
  `observacoes` text,
  `criadoPor` varchar(255),
  `criadoPorUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` timestamp NULL,
  `deletedBy` varchar(255),
  `deletedByUserId` int,
  PRIMARY KEY (`id`),
  INDEX `pjc_company` (`companyId`),
  INDEX `pjc_employee` (`employeeId`),
  INDEX `pjc_status` (`status`),
  INDEX `pjc_vencimento` (`dataFim`)
);

CREATE TABLE IF NOT EXISTS `pj_payments` (
  `id` int AUTO_INCREMENT NOT NULL,
  `contractId` int NOT NULL,
  `companyId` int NOT NULL,
  `employeeId` int NOT NULL,
  `mesReferencia` varchar(7) NOT NULL,
  `tipo` enum('adiantamento','fechamento','bonificacao') NOT NULL,
  `valor` varchar(20) NOT NULL,
  `descricao` text,
  `dataPagamento` date,
  `status` enum('pendente','pago','cancelado') NOT NULL DEFAULT 'pendente',
  `comprovanteUrl` text,
  `observacoes` text,
  `criadoPor` varchar(255),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `pjp_contract` (`contractId`),
  INDEX `pjp_company_mes` (`companyId`, `mesReferencia`),
  INDEX `pjp_employee` (`employeeId`)
);
