[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@9 && pnpm install --frozen-lockfile --no-strict-peer-dependencies"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.js"
