CREATE TABLE `audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userName` varchar(255),
	`companyId` int,
	`action` varchar(50) NOT NULL,
	`module` varchar(50) NOT NULL,
	`entityType` varchar(50),
	`entityId` int,
	`details` text,
	`ipAddress` varchar(45),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cnpj` varchar(18) NOT NULL,
	`razaoSocial` varchar(255) NOT NULL,
	`nomeFantasia` varchar(255),
	`endereco` text,
	`cidade` varchar(100),
	`estado` varchar(2),
	`cep` varchar(10),
	`telefone` varchar(20),
	`email` varchar(320),
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`),
	CONSTRAINT `companies_cnpj_unique` UNIQUE(`cnpj`)
);
--> statement-breakpoint
CREATE TABLE `employee_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`companyId` int NOT NULL,
	`tipo` enum('Admissao','Promocao','Transferencia','Mudanca_Funcao','Mudanca_Setor','Mudanca_Salario','Afastamento','Retorno','Ferias','Desligamento','Outros') NOT NULL,
	`descricao` text,
	`valorAnterior` text,
	`valorNovo` text,
	`dataEvento` date NOT NULL,
	`registradoPor` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `employee_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employees` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`matricula` varchar(20),
	`nomeCompleto` varchar(255) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20),
	`orgaoEmissor` varchar(20),
	`dataNascimento` date,
	`sexo` enum('M','F','Outro'),
	`estadoCivil` enum('Solteiro','Casado','Divorciado','Viuvo','Uniao_Estavel'),
	`nacionalidade` varchar(50),
	`naturalidade` varchar(100),
	`nomeMae` varchar(255),
	`nomePai` varchar(255),
	`ctps` varchar(20),
	`serieCTPS` varchar(10),
	`pis` varchar(20),
	`tituloEleitor` varchar(20),
	`certificadoReservista` varchar(20),
	`cnh` varchar(20),
	`categoriaCNH` varchar(5),
	`validadeCNH` date,
	`logradouro` varchar(255),
	`numero` varchar(20),
	`complemento` varchar(100),
	`bairro` varchar(100),
	`cidade` varchar(100),
	`estado` varchar(2),
	`cep` varchar(10),
	`telefone` varchar(20),
	`celular` varchar(20),
	`email` varchar(320),
	`contatoEmergencia` varchar(255),
	`telefoneEmergencia` varchar(20),
	`cargo` varchar(100),
	`funcao` varchar(100),
	`setor` varchar(100),
	`dataAdmissao` date,
	`dataDemissao` date,
	`salarioBase` varchar(20),
	`horasMensais` varchar(10),
	`tipoContrato` enum('CLT','PJ','Temporario','Estagio','Aprendiz'),
	`jornadaTrabalho` varchar(50),
	`banco` varchar(100),
	`agencia` varchar(20),
	`conta` varchar(30),
	`tipoConta` enum('Corrente','Poupanca'),
	`chavePix` varchar(100),
	`status` enum('Ativo','Ferias','Afastado','Licenca','Desligado','Recluso') NOT NULL DEFAULT 'Ativo',
	`fotoUrl` text,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employees_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `permissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`profileId` int NOT NULL,
	`module` varchar(50) NOT NULL,
	`canView` boolean NOT NULL DEFAULT false,
	`canCreate` boolean NOT NULL DEFAULT false,
	`canEdit` boolean NOT NULL DEFAULT false,
	`canDelete` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `permissions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyId` int NOT NULL,
	`profileType` enum('adm_master','adm','operacional','avaliador','consulta') NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_profiles_id` PRIMARY KEY(`id`)
);
