// Rev. 1954 — Pacote EXTRA da Biblioteca DDS (80 temas curados adicionais).
// Plugado em `seedTemasPadrao` (router dds.ts) logo após TEMAS_BIBLIOTECA Rev. 1861.
// Códigos com prefixos NOVOS p/ não colidir com os 172 existentes:
//   OBRA-* (atividades específicas de obra civil)
//   RISCO-* (riscos físicos e cenários reais)
//   SAUDE-* (saúde ocupacional física)
//   TRAN-* (trânsito e logística)
//   FERR-* (ferramentas manuais)
//   QUI-* (produtos químicos da obra)
//   ELET-* (riscos elétricos específicos)
//   FORM-* (formas, ferragem, concretagem)
//   ESC-* (escavação, fundação, escoramento)
//   ACAB-* (acabamento — gesso, pintura, vidro)
//   LIDER-* (liderança e cultura de segurança)
//   COND-* (condições do canteiro)
// Idempotente: o seed pula códigos já existentes.

import type { TemaBiblioteca } from "./temasBiblioteca";

export const TEMAS_BIBLIOTECA_EXTRA: TemaBiblioteca[] = [
  // ───────────────────── ATIVIDADES DE OBRA (OBRA-*) ─────────────────────
  { codigo: "OBRA-LANCAMENTO-CONCRETO", titulo: "Lançamento de Concreto com Bomba", descricao: "Lançamento de concreto por bombeamento — pressão da linha, tubulação, mangote e equipe de espalhamento.",
    norma: "NR-18 + manual do fabricante da bomba lança", categoria: "LIVRE",
    pontosChave: ["Verificar acoplamentos da linha antes de iniciar (golpe de aríete mata)", "Distância mínima de 3m da boca do mangote durante lançamento", "Comunicação visual e sonora entre operador da bomba e equipe", "Nunca dobrar a mangueira pra interromper fluxo — use a válvula", "EPI obrigatório: capacete jugular, óculos, bota PVC, luva nitrílica"],
    reforco: "Golpe de aríete da linha de concreto já decapitou operário. Respeite a distância." },
  { codigo: "OBRA-VIBRACAO-CONCRETO", titulo: "Vibração de Concreto (Imersão)", descricao: "Adensamento de concreto com vibrador de imersão — ergonomia, choque elétrico e ruído.",
    norma: "NR-18 + NR-12 + NR-15", categoria: "LIVRE",
    pontosChave: ["Vibrador NUNCA em contato com armadura por mais de 5s (vibra a ferragem)", "Cabo elétrico íntegro e DR no quadro (água + eletricidade)", "Protetor auricular obrigatório (>85 dB)", "Revezamento a cada 30min (LER/DORT no punho)", "Mangote íntegro — vazamento = choque + lesão"],
    reforco: "Vibrador é elétrico em ambiente molhado. Sem DR = morte." },
  { codigo: "OBRA-DESFORMA", titulo: "Desforma de Lajes e Pilares", descricao: "Desforma após cura — risco de queda de altura, queda de peças e impacto.",
    norma: "NR-18 + NR-35", categoria: "LIVRE",
    pontosChave: ["Cura mínima conforme projeto antes de desformar", "Isolamento da área inferior (queda de painel/escora)", "Capacete + jugular + bota com biqueira", "Escorar pilar/laje enquanto retira painéis grandes", "Pregos retirados na hora — nunca pisotear ou pisar"],
    reforco: "Peça de forma pesa 30kg+. Cabeça embaixo = óbito." },
  { codigo: "OBRA-MONTAGEM-FORMA", titulo: "Montagem de Formas e Cimbramentos", descricao: "Montagem de formas de madeira/metálica e escoramento — estabilidade e travamento.",
    norma: "NR-18.6 (Estruturas de Concreto) + projeto estrutural", categoria: "LIVRE",
    pontosChave: ["Projeto de escoramento assinado por engenheiro", "Travamento horizontal obrigatório (contraventos)", "Plumo e nivelamento conferidos antes do concreto", "Carga útil máxima respeitada", "Inspeção visual diária antes do uso"],
    reforco: "Cimbramento que cai mata 10 de uma vez. Tem projeto — siga." },
  { codigo: "OBRA-FERRAGEM-CORTE", titulo: "Corte e Dobra de Vergalhão", descricao: "Bancada de ferragem — policorte, dobradeira e vergalhão expostos.",
    norma: "NR-18 + NR-12", categoria: "LIVRE",
    pontosChave: ["Protetor de disco da policorte SEMPRE no lugar", "Óculos ampla visão + protetor facial em corte", "Pontas de vergalhão com capa plástica (pé/olho)", "Dobradeira: distância das mãos da matriz", "Bancada organizada — vergalhão no chão = tropeço"],
    reforco: "Vergalhão sem capa furou olho/abdome. Cobre as pontas HOJE." },
  { codigo: "OBRA-ALVENARIA-ELEVACAO", titulo: "Alvenaria — Elevação de Paredes", descricao: "Levantamento de paredes com cavaletes/andaime — quedas, esforço repetitivo e descarga de blocos.",
    norma: "NR-18 + NR-17", categoria: "LIVRE",
    pontosChave: ["Andaime apoiado >1,2m exige guarda-corpo", "Carga máxima por cavalete respeitada (450 kgf)", "Descarga de blocos com 2 pessoas ou paleteira", "Revezamento a cada 2h (coluna lombar)", "Argamassa: luva nitrílica (alcalina, queima a pele)"],
    reforco: "Cavalete bambo + 5 fiadas = queda de 1,5m. Já tetraplegiou pedreiro." },
  { codigo: "OBRA-REBOCO-EMBOCO", titulo: "Reboco, Emboço e Massa Única", descricao: "Aplicação de argamassa em parede — projeção, ergonomia e respiração de poeira.",
    norma: "NR-18 + NR-15 Anexo 12 (poeira mineral)", categoria: "LIVRE",
    pontosChave: ["Máscara PFF2 ao misturar cimento seco (silicose)", "Óculos ampla visão (respingo de argamassa)", "Luva nitrílica (alcalinidade)", "Andaime/cavalete estável e nivelado", "Pausas a cada 1h pro ombro (movimento repetitivo)"],
    reforco: "Cimento seco respira = pulmão branco em 10 anos. PFF2 sempre." },
  { codigo: "OBRA-CONTRAPISO", titulo: "Contrapiso e Regularização", descricao: "Execução de contrapiso e regularização de piso — ergonomia ajoelhada e poeira.",
    norma: "NR-17 + NR-15", categoria: "LIVRE",
    pontosChave: ["Joelheira obrigatória (bursite/menisco)", "Tapete EVA p/ tempo prolongado no chão", "Revezamento a cada 1h", "Hidratação reforçada (perda de líquido alta)", "Máscara PFF2 em corte de piso com makita"],
    reforco: "Bursite no joelho aposenta pedreiro aos 50. Joelheira não é frescura." },
  { codigo: "OBRA-REVESTIMENTO-CERAMICO", titulo: "Revestimento Cerâmico e Porcelanato", descricao: "Assentamento e corte de cerâmica/porcelanato — corte molhado e poeira de rejunte.",
    norma: "NR-18 + NR-15", categoria: "LIVRE",
    pontosChave: ["Serra mármore com lubrificação a água (poeira de sílica)", "Óculos ampla visão (estilhaço de porcelanato)", "Luva anti-corte na manipulação de peça quebrada", "Joelheira no assentamento de piso", "Descarte de estilhaço em caçamba específica"],
    reforco: "Estilhaço de porcelanato corta tendão. Luva anti-corte vale R$15." },
  { codigo: "OBRA-COBERTURA-TELHADO", titulo: "Execução de Cobertura e Telhado", descricao: "Montagem de cobertura (telha cerâmica, fibrocimento, metálica) — queda, vento e telha frágil.",
    norma: "NR-18 + NR-35 + NBR 15575", categoria: "LIVRE",
    pontosChave: ["Linha de vida e cinto paraquedista 100% do tempo", "Tábua de caminhamento sobre fibrocimento (NÃO PISE NA TELHA)", "Suspender atividade com vento >40 km/h", "2 ancoragens (jugular + linha de vida)", "Acesso por escada amarrada, NUNCA pulando"],
    reforco: "Telha fibrocimento NÃO suporta peso humano. Pisou = caiu 8m." },
  { codigo: "OBRA-IMPERMEABILIZACAO", titulo: "Impermeabilização (Manta Asfáltica)", descricao: "Aplicação de manta asfáltica com maçarico — fogo, gás GLP e queimaduras.",
    norma: "NR-18 + NR-20 + NR-23", categoria: "LIVRE",
    pontosChave: ["PT — Permissão de Trabalho a Quente OBRIGATÓRIA", "Extintor PQS 6kg a 5m de distância", "GLP em vasilhame na posição vertical, com cinta", "Vigia de fogo (1h pós-término)", "Calça e camisa em algodão (não sintético — derrete na pele)"],
    reforco: "Tecido sintético + chama = queimadura de 3º grau. Algodão sempre." },
  { codigo: "OBRA-DEMOLICAO", titulo: "Demolição Manual e Mecanizada", descricao: "Demolição de estruturas — risco de desabamento, poeira e queda de objetos.",
    norma: "NR-18.5 (Demolição)", categoria: "LIVRE",
    pontosChave: ["Plano de demolição assinado por engenheiro responsável", "Desligamento de água/luz/gás ANTES do início", "Demolir de cima para baixo, peça por peça", "Aspersão de água para abater poeira", "Isolamento total do entorno (3x altura da estrutura)"],
    reforco: "Demolição sem plano = parede caindo na rua = morte de terceiro." },
  { codigo: "OBRA-CONFINADO-SILO", titulo: "Entrada em Silo, Reservatório ou Cisterna", descricao: "Entrada em espaço confinado — atmosfera deficiente, presa, soterramento.",
    norma: "NR-33", categoria: "NR",
    pontosChave: ["PET — Permissão de Entrada e Trabalho obrigatória", "Medição de O2 (>=20,9%), explosividade (<10% LIE), gases tóxicos", "Vigia externo treinado, NUNCA entra", "Tripé com guincho para resgate", "Comunicação contínua (rádio ou linha vital)"],
    reforco: "Entrou sem PET = pode morrer em 30s. SEM PET, SEM ENTRADA." },
  { codigo: "OBRA-SOLDA-LOCAL", titulo: "Solda Elétrica em Estrutura Metálica", descricao: "Soldagem elétrica em obra — radiação UV, fumos metálicos, fogo e choque.",
    norma: "NR-18 + NR-34 + ABNT NBR 14606", categoria: "LIVRE",
    pontosChave: ["Máscara de solda automática (tom 11) — UV cega em 1s", "Ventilação forçada em local fechado (fumos metálicos = pulmão)", "PT a Quente + vigia de fogo + extintor", "Aterramento da peça soldada (choque)", "Roupa de raspa (avental + perneira + manga)"],
    reforco: "1 segundo olhando arco sem máscara = ceratite UV (dor 24h)." },
  { codigo: "OBRA-MOVIMENTACAO-CARGA", titulo: "Movimentação Manual de Cargas", descricao: "Carregamento manual de sacos, blocos, vergalhão — coluna, pegada e equipe.",
    norma: "NR-17 + Lei 6.514/77", categoria: "LIVRE",
    pontosChave: ["Limite legal homem: 60 kg; mulher: 25 kg (NR-17.2.7)", "Pegada: agachar com coluna reta, levantar com pernas", "2 pessoas para >40 kg ou peça volumosa", "Distância máxima 60m sem mecanização", "Cinta lombar NÃO substitui técnica correta"],
    reforco: "Hérnia de disco aos 35 = aposentadoria. Agacha com a perna." },

  // ───────────────────── ESCAVAÇÃO E FUNDAÇÃO (ESC-*) ─────────────────────
  { codigo: "ESC-VALA-PROFUNDA", titulo: "Escavação de Vala Profunda (>1,25m)", descricao: "Escavação manual ou mecanizada de vala — soterramento por desbarrancamento.",
    norma: "NR-18.6.5 + ABNT NBR 9061", categoria: "NR",
    pontosChave: ["Vala >1,25m exige escoramento OU talude com inclinação segura", "NUNCA descer em vala sem escora — colega segura no topo NÃO funciona", "Material escavado a >1m da borda (sobrecarga = colapso)", "Acesso por escada a cada 25m de vala", "Inspeção pré-turno após chuva (terra encharcada cai)"],
    reforco: "1 m³ de terra pesa 1.800 kg. Soterra adulto em 60 segundos." },
  { codigo: "ESC-ESTACA-HELICE", titulo: "Estaca Hélice Contínua e Strauss", descricao: "Execução de estacas — torque do equipamento, descarga e isolamento.",
    norma: "NR-18 + NR-12", categoria: "LIVRE",
    pontosChave: ["Isolamento da área de giro da hélice (corte fatal)", "Comunicação visual entre operador e ajudante", "EPI obrigatório: capacete jugular, óculos, bota com biqueira", "Concretagem: distância da boca da bomba", "Inspeção do cabo de aço diariamente"],
    reforco: "Hélice em giro decapita. Isolamento NUNCA é exagero." },
  { codigo: "ESC-BATE-ESTACA-PRECOMP", titulo: "Bate-Estaca Pré-Moldada", descricao: "Cravação de estaca pré-moldada com bate-estaca — ruído, vibração, içamento.",
    norma: "NR-18 + NR-15 (ruído)", categoria: "LIVRE",
    pontosChave: ["Protetor auricular tipo concha + plug (duplo) — >115 dB", "Isolamento de 1x altura da torre", "Estabilizadores da torre verificados pré-turno", "Cabo de içamento inspecionado (não pode ter fio rompido)", "Comunicação radio entre operador e equipe"],
    reforco: "Estaca pesa 3 toneladas. Cai = morte de quem está no raio." },
  { codigo: "ESC-FUNDACAO-DIRETA", titulo: "Fundação Direta (Sapata, Bloco)", descricao: "Execução de sapata/bloco — armação no fundo, concretagem e cura.",
    norma: "NR-18 + projeto estrutural", categoria: "LIVRE",
    pontosChave: ["Escora lateral da cava se profundidade >1,25m", "Acesso por escada (NÃO pular)", "Descida de armação com cordas-guia (não em queda livre)", "Concretagem com vibrador adensando", "Cura mínima antes de carga"],
    reforco: "Cava sem escora desaba na chuva. Espere o solo escorar." },
  { codigo: "ESC-CONTENCAO-TIRANTES", titulo: "Cortina Atirantada e Contenção", descricao: "Execução de cortina com tirantes — perfuração, injeção, protensão.",
    norma: "NR-18 + NR-35 + ABNT NBR 5629", categoria: "LIVRE",
    pontosChave: ["Plataforma de trabalho com guarda-corpo (queda)", "Perfuração: jato de água/ar = projeção (óculos)", "Injeção de calda: pressão alta (ruptura de mangueira)", "Protensão: NUNCA na frente do macaco (chicote do cabo)", "Cabo testemunho de carga a cada N tirantes"],
    reforco: "Chicote de cabo de tirante decapita. NUNCA na frente do macaco." },

  // ───────────────────── ACABAMENTO (ACAB-*) ─────────────────────
  { codigo: "ACAB-GESSO", titulo: "Aplicação de Gesso (Parede e Forro)", descricao: "Aplicação de gesso liso ou acartonado — poeira fina, ergonomia ombro/cervical.",
    norma: "NR-18 + NR-17 + NR-15", categoria: "LIVRE",
    pontosChave: ["Máscara PFF2 (poeira fina = bronquite)", "Óculos ampla visão (caída no rosto)", "Andaime/cavalete estável p/ teto", "Revezamento a cada 1h (ombro/pescoço)", "Hidratação reforçada"],
    reforco: "Forro de gesso aplicado por 8h direto = bursite no ombro garantida." },
  { codigo: "ACAB-PINTURA-INTERNA", titulo: "Pintura Interna (Látex, Esmalte)", descricao: "Pintura de paredes e portas — vapores químicos, escada, ergonomia.",
    norma: "NR-18 + NR-15 Anexo 13 (químicos)", categoria: "LIVRE",
    pontosChave: ["Ventilação obrigatória (esmalte = COV)", "Máscara PFF2 + cartucho químico em esmalte", "Escada amarrada (NÃO sobre cadeira/balde)", "Luva nitrílica e óculos ampla visão", "Pausa do pulso (rolagem repetitiva)"],
    reforco: "Esmalte em local fechado = intoxicação aguda. Janela aberta sempre." },
  { codigo: "ACAB-PINTURA-EXTERNA", titulo: "Pintura de Fachada e Externa", descricao: "Pintura em fachada com balancim/cadeira suspensa — altura, vento, intempérie.",
    norma: "NR-35 + NR-18", categoria: "NR",
    pontosChave: ["Cinto paraquedista + 2 talabartes (tipo Y)", "Treinamento NR-35 8h + reciclagem", "Suspender com vento >40 km/h", "Linha de vida vertical INDEPENDENTE da estrutura do balancim", "ASO específico para trabalho em altura"],
    reforco: "Caiu do 5º andar = não tem 2ª chance. 2 ancoragens sempre." },
  { codigo: "ACAB-VIDRO-INSTALACAO", titulo: "Instalação de Vidro e Esquadria", descricao: "Içamento e instalação de vidros — corte, queda da peça, ergonomia.",
    norma: "NR-18 + NR-11 (içamento)", categoria: "LIVRE",
    pontosChave: ["Luva anti-corte nível 5 obrigatória", "Ventosa testada antes do içamento", "2 pessoas mínimo p/ vidro >1m²", "Isolamento da área inferior (queda da peça)", "Capacete jugular + óculos (estilhaço)"],
    reforco: "Vidro de 6mm corta tendão em 1 segundo. Luva anti-corte salva mão." },
  { codigo: "ACAB-HIDRAULICA", titulo: "Instalação Hidráulica e Sanitária", descricao: "Execução de tubulação PVC/PEX — solvente, calor (PEX), corte de tubo.",
    norma: "NR-18 + NR-15", categoria: "LIVRE",
    pontosChave: ["Solvente PVC: ventilação + máscara cartucho", "PEX com termofusão: queimadura por contato", "Serra para PVC: sem luva no disco (engata)", "Teste de pressão: isolamento (rebente)", "Limpeza de cola no piso (escorregadio)"],
    reforco: "Solvente PVC inalado por horas = dor de cabeça + náusea. Ventile." },

  // ───────────────────── RISCOS FÍSICOS (RISCO-*) ─────────────────────
  { codigo: "RISCO-QUEDA-MESMO-NIVEL", titulo: "Queda no Mesmo Nível (Tropeço)", descricao: "Quedas no mesmo nível por desorganização, piso molhado ou cabo solto — 30% dos acidentes leves.",
    norma: "NR-18 + NR-8", categoria: "LIVRE",
    pontosChave: ["Cabos elétricos suspensos a >2m ou em canaleta", "Mangueiras enroladas após uso", "Sinalização de piso molhado", "Iluminação adequada em circulação", "Calçados com solado antiderrapante"],
    reforco: "Torção de tornozelo afasta 15 dias. Cabo no chão é convite ao INSS." },
  { codigo: "RISCO-QUEDA-OBJETO", titulo: "Queda de Objetos de Altura", descricao: "Queda de ferramenta/material de andaime ou pavimento superior — atinge cabeça.",
    norma: "NR-18 + NR-35", categoria: "LIVRE",
    pontosChave: ["Rodapé de 20cm em todo guarda-corpo", "Tela de proteção fechada em andaime", "Ferramenta com fitilho de segurança em altura", "Sinalização e isolamento da projeção", "Capacete jugular SEMPRE (sem queixeira não vale)"],
    reforco: "Chave de fenda de 8º andar atinge a 200 km/h. Mata na hora." },
  { codigo: "RISCO-PROJECAO-PARTICULA", titulo: "Projeção de Partículas (Esmeril, Lixa, Corte)", descricao: "Estilhaços e partículas em corte/esmeril/lixa — olhos, face, vias respiratórias.",
    norma: "NR-6 + NR-12", categoria: "LIVRE",
    pontosChave: ["Óculos ampla visão TODOS os trabalhos com projeção", "Protetor facial em esmeril/lixadeira (óculos não basta)", "Máscara PFF2 em corte de mineral", "Disco compatível com a ferramenta (rotação máxima)", "Isolamento da área (3m no entorno)"],
    reforco: "Estilhaço no olho = cegueira possível. Óculos custa R$15." },
  { codigo: "RISCO-PRENSAMENTO", titulo: "Prensamento, Esmagamento e Pinçamento", descricao: "Prensamento por máquina, parede, carga pendular — dedos, mãos, tronco.",
    norma: "NR-12 + NR-11", categoria: "LIVRE",
    pontosChave: ["Distância segura de carga içada (NUNCA sob)", "Mãos longe de pontos de aperto de máquina", "Sinalização sonora antes de movimentar", "Travamento de carga em descida", "Treinamento de sinaleiro autorizado"],
    reforco: "Carga balançando esmaga em fração de segundo. Saia do raio." },
  { codigo: "RISCO-RUIDO-CONTINUO", titulo: "Exposição a Ruído Contínuo", descricao: "Ruído contínuo de máquinas (>85 dB) — perda auditiva irreversível.",
    norma: "NR-15 Anexo 1 + NR-7", categoria: "NR",
    pontosChave: ["Limite: 85 dB(A) por 8h jornada", "Atenuação real do EPI (Nível de Atenuação Real)", "Protetor concha + plug em >100 dB", "Audiometria anual obrigatória (PCMSO)", "Sinalização de áreas obrigatórias de uso"],
    reforco: "Perda auditiva é silenciosa e NÃO tem cura. Use o protetor." },
  { codigo: "RISCO-CALOR-OCUPACIONAL", titulo: "Calor Ocupacional (IBUTG)", descricao: "Exposição a calor em obra a céu aberto — desidratação, insolação, hipertermia.",
    norma: "NR-15 Anexo 3 + NR-21", categoria: "NR",
    pontosChave: ["IBUTG calculado e exposto na frente", "Pausas obrigatórias em ciclo trabalho/descanso", "Hidratação: 200 ml a cada 30min (NÃO esperar sede)", "Sombreamento na área de descanso", "Soro em casos de tontura/cãibra"],
    reforco: "Insolação mata em minutos. Sede já é desidratação." },
  { codigo: "RISCO-FRIO", titulo: "Exposição a Frio (Obras Sul/Inverno)", descricao: "Exposição a frio em obras no Sul ou madrugada — hipotermia, doenças respiratórias.",
    norma: "NR-15 Anexo 9 + NR-21", categoria: "NR",
    pontosChave: ["Vestuário em camadas (térmico + impermeável)", "Luvas térmicas em metal frio", "Bebida quente disponível", "Identificar sintomas: tremor, fala arrastada, sonolência", "Acolhimento em vestiário aquecido"],
    reforco: "Hipotermia confunde com cansaço. Tremor é sinal de alerta." },
  { codigo: "RISCO-RAIO-TEMPESTADE", titulo: "Trabalho Durante Tempestade Elétrica", descricao: "Risco de descarga atmosférica em obra — paralisação obrigatória.",
    norma: "NR-18 + NBR 5419", categoria: "LIVRE",
    pontosChave: ["Paralisação ao primeiro trovão (raio percorre 15 km)", "Afastamento de estruturas metálicas e guindastes", "Abrigar em local com SPDA (para-raios)", "NÃO usar celular em campo aberto", "Retorno após 30min sem trovão"],
    reforco: "Raio atinge a 270 km. Trovão é seu aviso de 15s." },
  { codigo: "RISCO-CHUVA-FORTE", titulo: "Trabalho na Chuva e Lama", descricao: "Operação em obra com chuva forte — escorregão, choque elétrico, soterramento.",
    norma: "NR-18 + análise de risco", categoria: "LIVRE",
    pontosChave: ["Paralisação de altura, içamento e elétrico em chuva forte", "Capa de chuva sem prejudicar visão/movimento", "Reforço de calçado antiderrapante", "Inspeção de talude/vala (encharcamento)", "Quadro elétrico com tampa e DR"],
    reforco: "Vala encharcada cai sem aviso. Inspeção pré-turno após chuva." },
  { codigo: "RISCO-ESPACO-QUENTE", titulo: "Trabalho em Cobertura/Laje Exposta", descricao: "Trabalho em laje exposta ao sol — calor radiante intenso + altura.",
    norma: "NR-15 + NR-35", categoria: "LIVRE",
    pontosChave: ["IBUTG considera radiação direta", "Ciclo 45min trabalho / 15min descanso na sombra", "Hidratação 250 ml a cada 30min", "Chapéu árabe sob o capacete", "EPI altura mesmo em laje >2m"],
    reforco: "Laje a 60°C derrete tênis e desidrata em 1h. Pausa na sombra." },

  // ───────────────────── ELÉTRICA (ELET-*) ─────────────────────
  { codigo: "ELET-CHOQUE-INDIRETO", titulo: "Choque Elétrico por Massa Energizada", descricao: "Choque por contato com massa metálica energizada por falha — aterramento e DR.",
    norma: "NR-10 + NBR 5410", categoria: "NR",
    pontosChave: ["DR (Diferencial Residual) em tomada/quadro de obra", "Aterramento de carcaça de máquina/quadro", "Inspeção visual do cabo (capa íntegra)", "Equipotencialização em quadro", "NUNCA improvisar 'gambiarra' em pontos elétricos"],
    reforco: "30 mA por 0,5s = parada cardíaca. DR é R$50 que salva vida." },
  { codigo: "ELET-LOTO", titulo: "Bloqueio e Etiquetagem (LOTO)", descricao: "Lock-Out/Tag-Out — bloqueio de fonte de energia para manutenção segura.",
    norma: "NR-10 + NR-12 + NR-33", categoria: "NR",
    pontosChave: ["Bloqueio físico (cadeado individual)", "Etiqueta com nome e data do trabalhador", "Teste de ausência de tensão APÓS bloqueio", "Reenergização só pelo próprio que bloqueou", "Treinamento de procedimento"],
    reforco: "Sem LOTO, alguém ligou de volta = morte. Cadeado é a sua vida." },
  { codigo: "ELET-PROXIMIDADE-REDE", titulo: "Trabalho Próximo a Rede Energizada", descricao: "Operação de guindaste/escada/andaime próximo a rede aérea — afastamento mínimo.",
    norma: "NR-10 + NR-18 + NBR 5434", categoria: "NR",
    pontosChave: ["Afastamento mínimo BT: 1,5m; AT: 5m (até 69 kV)", "Solicitar desenergização à concessionária", "Sinaleiro orienta operador", "Lança/escada metálica = condutor (NUNCA aproxime)", "EPI: capacete classe B, calçado isolante"],
    reforco: "Andaime metálico encostou em rede = morte instantânea da equipe." },
  { codigo: "ELET-QUADRO-OBRA", titulo: "Quadro Elétrico de Obra", descricao: "Quadro de distribuição na frente de serviço — DR, aterramento, IP44.",
    norma: "NR-10 + NR-18 + NBR 5410", categoria: "LIVRE",
    pontosChave: ["Quadro com grau de proteção IP44 mínimo (chuva)", "DR de 30 mA em circuitos de tomada", "Disjuntor por circuito (não junta tudo)", "Aterramento eficaz (haste)", "Tampa fechada e cadeado"],
    reforco: "Quadro de obra aberto na chuva mata. IP44 + tampa fechada." },
  { codigo: "ELET-EXTENSAO-CABO", titulo: "Extensões, Tomadas e Cabos", descricao: "Uso correto de extensões e tomadas — bitola, T, conexão.",
    norma: "NR-10 + NBR 14136", categoria: "LIVRE",
    pontosChave: ["Bitola compatível com a carga (cabo aquece se subdimensionado)", "NUNCA usar T (benjamim) — sobrecarga", "Tomada padrão NBR 14136 (3 pinos)", "Cabo íntegro (sem emenda com fita)", "Desconectar pela tomada, não puxar pelo cabo"],
    reforco: "Benjamim sobrecarregado = incêndio. Tomadas individuais." },

  // ───────────────────── FERRAMENTAS MANUAIS (FERR-*) ─────────────────────
  { codigo: "FERR-MARTELO", titulo: "Martelo e Marreta", descricao: "Uso seguro de martelo/marreta — cabo, posição da mão, estilhaço.",
    norma: "NR-12 + boas práticas", categoria: "LIVRE",
    pontosChave: ["Cabo íntegro e firme (folgado = projétil)", "Ângulo de batida correto (não inclinado)", "Mão de apoio longe da linha de impacto", "Óculos ampla visão (estilhaço de prego)", "Ferramenta certa para tarefa (não martelar com chave)"],
    reforco: "Cabo de martelo solto vira lança. Confira antes de bater." },
  { codigo: "FERR-CHAVE-FIXA-INGLESA", titulo: "Chaves Fixa, Estrela e Inglesa", descricao: "Uso correto de chaves manuais — alavancagem, ajuste, prevenção de escorregão.",
    norma: "NR-12 + boas práticas", categoria: "LIVRE",
    pontosChave: ["Tamanho exato da chave (folga = escorrega + arranha junta)", "Puxar (não empurrar) — escorrego não machuca", "Chave inglesa com folga zero antes de aplicar força", "NUNCA prolongar com cano (alavanca = quebra)", "Inspeção: chave gasta vai pro descarte"],
    reforco: "Chave folgada escorrega e racha dedo no concreto. Tamanho exato." },
  { codigo: "FERR-FACA-ESTILETE", titulo: "Faca e Estilete (Corte Manual)", descricao: "Uso de faca/estilete em obra — corte de fio, sacaria, embalagem.",
    norma: "NR-12 + boas práticas", categoria: "LIVRE",
    pontosChave: ["Cortar SEMPRE longe do corpo (não em direção à mão)", "Lâmina retrátil em estilete (após uso, recolher)", "Luva anti-corte na mão de apoio", "Não usar estilete como chave de fenda", "Descarte de lâmina em recipiente rígido"],
    reforco: "Corte de estilete vai fundo. 80% dos casos é mão de apoio." },
  { codigo: "FERR-SERROTE-MANUAL", titulo: "Serrote e Serra Manual", descricao: "Uso de serrote/arco de serra — dentes, marcação, postura.",
    norma: "NR-12", categoria: "LIVRE",
    pontosChave: ["Dentes na direção correta", "Marcação antes de cortar (não improvisar)", "Mão de apoio com luva anti-corte", "Tábua presa em cavalete (não no joelho)", "Postura ereta (não curvar pra forçar)"],
    reforco: "Serrote no joelho corta tendão. Cavalete sempre." },
  { codigo: "FERR-PISTOLA-FINCA", titulo: "Pistola Finca-Pino (Tiro)", descricao: "Pistola de fixação a pólvora — operador habilitado, isolamento, ricochete.",
    norma: "NR-18 + manual fabricante", categoria: "LIVRE",
    pontosChave: ["Operador com curso específico (não improvisar)", "EPI: capacete, óculos, protetor auricular, luva", "Isolamento de 3m no entorno (ricochete)", "Cartucho compatível com a base", "Armazenamento da munição em armário trancado"],
    reforco: "Tiro de finca-pino atravessa madeira de 5cm. Ricochete mata." },

  // ───────────────────── QUÍMICOS (QUI-*) ─────────────────────
  { codigo: "QUI-CIMENTO-PELE", titulo: "Cimento e Cal — Queimadura Química", descricao: "Cimento e cal molhados queimam a pele (alcalinidade pH>12) — dermatite, queimadura.",
    norma: "NR-6 + NR-15 + FISPQ", categoria: "LIVRE",
    pontosChave: ["Luva nitrílica em manipulação de argamassa/concreto", "Bota PVC em concretagem (entrar na massa)", "Lavagem imediata com água em respingo na pele", "Não esperar 'arder' para lavar (queimadura é silenciosa)", "Creme barreira como reforço"],
    reforco: "Cimento queima a pele em 1h sem que você sinta. Luva sempre." },
  { codigo: "QUI-DESMOLDANTE", titulo: "Desmoldante e Solvente Industrial", descricao: "Aplicação de desmoldante em forma e solvente — vapores, inflamabilidade, pele.",
    norma: "NR-15 + FISPQ", categoria: "LIVRE",
    pontosChave: ["Ventilação obrigatória em local fechado", "Máscara semifacial com cartucho químico", "Luva nitrílica + óculos ampla visão", "Inflamável: longe de chama/solda", "FISPQ disponível na bancada"],
    reforco: "Desmoldante respirado horas a fio = vertigem + náusea. Ventile." },
  { codigo: "QUI-ADITIVO-CONCRETO", titulo: "Aditivos de Concreto (Plastificante, Acelerador)", descricao: "Manipulação de aditivo químico para concreto — alcalinos, corrosivos.",
    norma: "NR-6 + FISPQ", categoria: "LIVRE",
    pontosChave: ["EPI: luva nitrílica + óculos + máscara em manuseio", "Diluição conforme dosagem do projeto (não improvisar)", "Tambor em bacia de contenção (vazamento)", "Lavagem de mãos APÓS manuseio (antes de comer)", "FISPQ lida e treinada"],
    reforco: "Aditivo respinga no olho = córnea queimada. Óculos sempre." },
  { codigo: "QUI-EPOXI-RESINA", titulo: "Resina Epóxi e Poliuretano", descricao: "Aplicação de resina epóxi em piso/impermeabilização — sensibilização alérgica.",
    norma: "NR-15 Anexo 13 + FISPQ", categoria: "LIVRE",
    pontosChave: ["Sensibilização gera dermatite vitalícia", "Luva butílica (nitrílica passa)", "Máscara cartucho químico (vapor)", "Roupa de Tyvek descartável", "Lavagem rigorosa pós-aplicação"],
    reforco: "Dermatite por epóxi NÃO some. Uma vez sensível, pra sempre." },

  // ───────────────────── SAÚDE OCUPACIONAL FÍSICA (SAUDE-*) ─────────────────────
  { codigo: "SAUDE-LOMBALGIA", titulo: "Lombalgia e Hérnia de Disco", descricao: "Dor lombar e hérnia de disco — causa nº1 de afastamento na construção civil.",
    norma: "NR-17 + Manual MTE", categoria: "LIVRE",
    pontosChave: ["Levantar agachado (perna, não coluna)", "Carga máx individual 60 kg (NR-17)", "Mecanização sempre que possível (paleteira, carrinho)", "Ginástica laboral pré-turno", "Procurar médico ao primeiro alerta (não esperar piorar)"],
    reforco: "Hérnia de disco aposenta aos 40. Agacha pra levantar." },
  { codigo: "SAUDE-LER-DORT", titulo: "LER/DORT (Lesão por Esforço Repetitivo)", descricao: "Lesão por esforço repetitivo em punho, ombro, cotovelo — pintor, pedreiro, soldador.",
    norma: "NR-17 + INSS", categoria: "LIVRE",
    pontosChave: ["Identificar tarefa repetitiva crítica", "Revezamento entre tarefas a cada 2h", "Pausa ativa (alongamento) a cada 1h", "Ferramentas ergonômicas (cabo macio, peso reduzido)", "Não ignorar formigamento/dor inicial"],
    reforco: "Formigamento no punho hoje = cirurgia em 2 anos. Não ignore." },
  { codigo: "SAUDE-SILICOSE", titulo: "Silicose (Sílica Cristalina)", descricao: "Doença pulmonar irreversível por inalação de sílica (corte de pedra, concreto, cerâmica).",
    norma: "NR-15 Anexo 12 + NR-22", categoria: "NR",
    pontosChave: ["Corte SEMPRE com lubrificação a água (abate poeira)", "Máscara PFF3 em corte de mineral", "Aspiração local na ferramenta (lixadeira c/ aspirador)", "Audiometria + espirometria periódica", "Doença NÃO TEM CURA — só prevenção"],
    reforco: "Silicose mata sufocado em 10 anos. PFF3 + água sempre." },
  { codigo: "SAUDE-DERMATITE", titulo: "Dermatite de Contato (Cimento, Tinta, Solvente)", descricao: "Dermatite alérgica e irritativa por contato com químicos da obra.",
    norma: "NR-6 + NR-7 + FISPQ", categoria: "LIVRE",
    pontosChave: ["Luva adequada AO produto (FISPQ orienta)", "Creme barreira antes do turno", "Lavagem suave pós-turno (sabão neutro)", "Não usar solvente para limpar a pele", "Procurar médico ao surgir mancha/coceira"],
    reforco: "Dermatite crônica afasta do ofício. Luva certa salva carreira." },
  { codigo: "SAUDE-DESIDRATACAO", titulo: "Desidratação em Obra", descricao: "Perda de líquido por suor em obra a céu aberto — risco de insolação e queda.",
    norma: "NR-21 + NR-24", categoria: "LIVRE",
    pontosChave: ["Beber 200 ml a cada 30min (sem esperar sede)", "Soro de reidratação em dia >35°C", "Identificar sintomas: tontura, urina amarelo-escura, cãibra", "Acolhimento imediato em sombra", "Bebedouro próximo à frente (max 50m)"],
    reforco: "Tontura no andaime = queda. Hidratação não é luxo." },
  { codigo: "SAUDE-PERDA-AUDITIVA", titulo: "Perda Auditiva Induzida por Ruído (PAIR)", descricao: "Perda auditiva irreversível por exposição a ruído — silenciosa e progressiva.",
    norma: "NR-15 + NR-7", categoria: "NR",
    pontosChave: ["Áreas >85 dB com sinalização e EPI obrigatório", "Protetor concha + plug em >100 dB", "Audiometria ocupacional anual", "Atenuação do EPI (NRR) considerada", "NÃO usar fone de música sob o protetor"],
    reforco: "Surdez ocupacional não dá direito a aposentadoria especial. Use o protetor." },

  // ───────────────────── TRÂNSITO E LOGÍSTICA (TRAN-*) ─────────────────────
  { codigo: "TRAN-CAMINHAO-OBRA", titulo: "Trânsito de Caminhões no Canteiro", descricao: "Manobra de caminhões na obra — atropelamento de pedestre, sinaleiro.",
    norma: "NR-18 + CTB", categoria: "LIVRE",
    pontosChave: ["Sinaleiro autorizado em toda manobra à ré", "Faixa de pedestre e separação física do tráfego", "Velocidade máx 20 km/h em canteiro", "Alarme sonoro de ré obrigatório", "Ponto cego conhecido por todos (afastar)"],
    reforco: "Caminhão à ré não vê quem está atrás. Sinaleiro = vida." },
  { codigo: "TRAN-BETONEIRA-RUA", titulo: "Caminhão Betoneira em Via Pública", descricao: "Posicionamento de betoneira na rua — trânsito, pedestre, cone.",
    norma: "CTB + Resolução CONTRAN 160", categoria: "LIVRE",
    pontosChave: ["Sinalização viária com cones e bandeirinha", "Apoio em local plano (sapata estável)", "Sinaleiro para fluxo de pedestre", "Lançamento de calha controlado (queda do cone)", "Comunicação com a guarnição de trânsito local"],
    reforco: "Pedestre desviando de obstáculo na rua morre atropelado. Sinalize." },
  { codigo: "TRAN-MOTO-DESLOCAMENTO", titulo: "Motociclista — Deslocamento Casa-Obra", descricao: "Risco do colaborador motoqueiro em deslocamento — capacete, regra das mãos.",
    norma: "CTB + NR-1 (deslocamento equiparado em alguns casos)", categoria: "LIVRE",
    pontosChave: ["Capacete certificado (NBR) com viseira", "Luva, jaqueta e calça reforçada", "Não circular entre carros em movimento (corredor)", "Respeitar limite de velocidade (estatística pesada)", "Manutenção dos freios e pneus em dia"],
    reforco: "Acidente de moto a caminho da obra = empresa investiga. Cuide-se." },
  { codigo: "TRAN-CARONA-CARROCERIA", titulo: "Carona em Carroceria de Caminhão", descricao: "PROIBIÇÃO TOTAL de carona em carroceria — risco extremo de queda em movimento.",
    norma: "CTB Art. 235 + NR-11", categoria: "LIVRE",
    pontosChave: ["Carona em carroceria é INFRAÇÃO GRAVÍSSIMA (CTB)", "Transporte de pessoas SÓ em cabine ou ônibus", "Ônibus fretado da obra com cinto", "Recusar se mandarem — você morre, não eles", "Reportar ao SESMT/CIPA imediatamente"],
    reforco: "Carroceria em movimento = caixão aberto. RECUSE." },

  // ───────────────────── CONDIÇÕES DO CANTEIRO (COND-*) ─────────────────────
  { codigo: "COND-AGUA-POTAVEL", titulo: "Água Potável no Canteiro", descricao: "Disponibilidade de água potável conforme NR-24 — qualidade, distância, copos.",
    norma: "NR-24 + Portaria 2.914/2011", categoria: "NR",
    pontosChave: ["Água potável a no máximo 100m da frente", "Análise de potabilidade periódica", "Bebedouro com jato inclinado (não copo coletivo)", "Garrafa individual identificada (NÃO compartilhar)", "Reservatório limpo e tampado"],
    reforco: "Água contaminada = surto na obra. Análise é direito." },
  { codigo: "COND-BANHEIRO-CANTEIRO", titulo: "Banheiro e Vestiário no Canteiro", descricao: "Instalações sanitárias e vestiário conforme NR-24 — quantidade, limpeza, privacidade.",
    norma: "NR-24", categoria: "NR",
    pontosChave: ["1 vaso para cada 20 trabalhadores", "Limpeza no mínimo 2x ao dia", "Vestiário com armário individual", "Chuveiro com água quente (insalubres)", "Separação por gênero"],
    reforco: "Banheiro precário = doença + abandono. NR-24 não é sugestão." },
  { codigo: "COND-REFEITORIO", titulo: "Refeitório e Local de Refeição", descricao: "Refeitório conforme NR-24 — área, ventilação, mesa, lavatório.",
    norma: "NR-24", categoria: "NR",
    pontosChave: ["1m² por trabalhador no horário de pico", "Mesas, bancos e lavatório próximos", "Ventilação adequada (ou ar-condicionado)", "PROIBIDO comer na frente de serviço (NR-24)", "Aquecedor de marmita disponível"],
    reforco: "Comer no chão atrai rato e leptospirose. Use o refeitório." },
  { codigo: "COND-ALOJAMENTO", titulo: "Alojamento em Obra", descricao: "Alojamento conforme NR-18/NR-24 — quando é obrigatório e condições mínimas.",
    norma: "NR-18.4 + NR-24", categoria: "NR",
    pontosChave: ["Cama com colchão (não beliche triplo)", "5m² por trabalhador no dormitório", "Banheiro separado por gênero", "Lavanderia disponível", "Vedado fogão dentro do dormitório (incêndio)"],
    reforco: "Alojamento ruim adoece equipe. NR-18 detalha mínimo." },

  // ───────────────────── LIDERANÇA E CULTURA (LIDER-*) ─────────────────────
  { codigo: "LIDER-EXEMPLO", titulo: "Líder como Exemplo de Segurança", descricao: "Liderança pelo exemplo — encarregado/mestre dá o tom da cultura de segurança.",
    norma: "Boas práticas + NR-1", categoria: "LIVRE",
    pontosChave: ["Líder SEMPRE de EPI completo (mesmo só passando)", "Repreender comportamento inseguro NA HORA (sem hostilidade)", "Reconhecer publicamente bom comportamento", "Participar de DDS (não delegar)", "Reportar próprio quase-acidente (humildade)"],
    reforco: "Equipe imita o líder. Tira o capacete uma vez, 10 tiram amanhã." },
  { codigo: "LIDER-DDS-EFETIVO", titulo: "Como Conduzir um DDS Efetivo", descricao: "Técnicas para tornar o DDS engajador e útil — não burocrático.",
    norma: "Boas práticas", categoria: "LIVRE",
    pontosChave: ["Duração máx 15min (foco vai embora depois)", "Tema da frente do dia (não genérico)", "Perguntar — não monologar", "Caso real (próprio ou da empresa) > teoria", "Registrar presença + tema (mas SEM virar burocracia)"],
    reforco: "DDS lido em 3min é teatro. Conversa real salva vidas." },
  { codigo: "LIDER-RECUSA-INSEGURO", titulo: "Direito de Recusa ao Trabalho Inseguro", descricao: "Direito do trabalhador de recusar tarefa com risco grave e iminente (CLT Art. 161).",
    norma: "CLT Art. 161 + NR-1", categoria: "LIVRE",
    pontosChave: ["Trabalhador PODE recusar tarefa com risco grave e iminente", "Recusa NÃO é insubordinação", "Comunicar imediatamente ao SESMT/CIPA", "Empresa deve avaliar antes de cobrar", "Demissão por recusa pode ser revertida na justiça"],
    reforco: "Você pode dizer NÃO se for morrer. CLT te protege." },
  { codigo: "LIDER-DENUNCIA-CANAL", titulo: "Canal de Denúncia e Whistleblower", descricao: "Canal interno para reportar irregularidades de segurança sem retaliação.",
    norma: "Boas práticas + Lei 14.457/2022", categoria: "LIVRE",
    pontosChave: ["Canal anônimo (telefone, app, urna)", "Garantia de não-retaliação por escrito", "Investigação imparcial", "Devolutiva ao denunciante (sem identificá-lo)", "Reuniões periódicas com indicadores"],
    reforco: "Sem canal seguro, ninguém denuncia até alguém morrer." },
  { codigo: "LIDER-INTEGRACAO", titulo: "Integração de Novo Colaborador (NR-18.28)", descricao: "Treinamento admissional obrigatório de 6h antes do início — riscos do canteiro.",
    norma: "NR-18.28 + NR-1", categoria: "NR",
    pontosChave: ["Mínimo 6h antes da primeira atividade", "Riscos específicos da obra (não genérico)", "EPI entregue com recibo assinado", "Localização de bebedouro, banheiro, refeitório, brigada", "Recalcitra de NR-18 a cada 6 meses"],
    reforco: "Recém-chegado morre mais. 6h de integração é a lei." },
  { codigo: "LIDER-FEEDBACK-POSITIVO", titulo: "Feedback Positivo de Segurança", descricao: "Reforço positivo de comportamento seguro — mais eficaz que punição.",
    norma: "BBS (Behavior-Based Safety)", categoria: "LIVRE",
    pontosChave: ["Elogio público > correção privada (inversão do RH)", "Especificar o comportamento (não 'parabéns', mas 'parabéns pelo cinto')", "Recompensa simbólica (camiseta, café especial)", "Quadro de reconhecimento mensal", "Líder treinado para dar feedback"],
    reforco: "Elogio sincero motiva 10x mais que repreensão. Use." },

  // ───────────────────── EMERGÊNCIA ESPECÍFICA (EMERG-* novos) ─────────────────────
  { codigo: "EMERG-AFOGAMENTO", titulo: "Afogamento (Cisterna, Açude, Vala Inundada)", descricao: "Resgate e prevenção de afogamento em obras com água acumulada.",
    norma: "NR-18 + boas práticas resgate", categoria: "LIVRE",
    pontosChave: ["Isolamento físico de poços/cisternas (cobertura)", "Boia ou corda no entorno", "Resgate com objeto flutuante (não entrar)", "Avisar Bombeiros (193) imediatamente", "RCP após retirar da água"],
    reforco: "Cisterna aberta mata criança e adulto. Cobertura sempre." },
  { codigo: "EMERG-SOTERRAMENTO", titulo: "Soterramento em Vala", descricao: "Procedimento de resgate em soterramento — não escavar diretamente.",
    norma: "NR-18 + Defesa Civil", categoria: "LIVRE",
    pontosChave: ["Acionar Bombeiros (193) IMEDIATAMENTE", "Liberar via aérea da vítima (cabeça) com cuidado", "NÃO retirar o corpo até estabilização (síndrome de esmagamento)", "Isolar a área (novo desabamento)", "Soro fisiológico se possível"],
    reforco: "Soterrado vivo pode morrer ao ser retirado (esmagamento). Espere Bombeiros." },
  { codigo: "EMERG-AMPUTACAO", titulo: "Amputação Traumática", descricao: "Primeiros socorros em amputação — preservar membro e conter hemorragia.",
    norma: "NR-7 + Manual SAMU", categoria: "LIVRE",
    pontosChave: ["Conter hemorragia com compressão direta (não torniquete improvisado)", "Embrulhar membro em pano úmido (soro), em saco plástico, em gelo INDIRETO", "Acionar SAMU (192) imediatamente", "Manter vítima consciente e aquecida", "Membro tem 6h para reimplante"],
    reforco: "Reimplante salva carreira. Membro conservado certo até hospital." },
  { codigo: "EMERG-CONVULSAO", titulo: "Convulsão (Epilepsia, AVC, Hipoglicemia)", descricao: "Primeiros socorros em crise convulsiva — proteger a vítima durante a crise.",
    norma: "Manual SAMU + boas práticas", categoria: "LIVRE",
    pontosChave: ["NÃO segurar a vítima nem colocar nada na boca", "Proteger cabeça (almofada/pano)", "Afastar objetos do entorno", "Cronometrar duração (>5min é emergência)", "Pós-crise: lateralizar e chamar SAMU (192)"],
    reforco: "Mito de 'pôr colher na boca' já matou. Só proteja a cabeça." },
  { codigo: "EMERG-MORDIDA-PICADA", titulo: "Picada de Cobra, Aranha, Escorpião", descricao: "Procedimento em picada de animal peçonhento — frequente em obra rural/desmate.",
    norma: "Manual MS + boas práticas", categoria: "LIVRE",
    pontosChave: ["NÃO cortar, sugar ou aplicar torniquete", "Imobilizar o membro abaixo do coração", "Levar a vítima ao hospital IMEDIATAMENTE", "Fotografar o animal SE seguro (ID do soro)", "Limpar com água e sabão, sem álcool"],
    reforco: "Soro antiofídico tem 6h efetivos. Hospital sempre, sucção nunca." },
];
