// Rev. 1861 — Biblioteca expandida de temas DDS (170 temas únicos).
// Plugada em `seedTemasPadrao` (router dds.ts). Códigos com prefixo temático
// (NR-XX, OBRA-, EQP-, EPI-, SAUDE-, MENTAL-, RISCO-, EMERG-, TRAN-, DOC-,
// CULT-) para facilitar busca na UI. ZERO sobreposição com CAMPANHAS_GOV
// (12), VACINACAO_PNI (8) ou NRS_CONSTRUCAO (13) — checado por código.
//
// Cada tema gera um roteiro estruturado padrão via `buildRoteiroLib` —
// markdown nas mesmas seções dos roteiros detalhados (Objetivo / Por que
// importa / Pontos-chave / Aplicação / Perguntas / Reforço final).

export type TemaBiblioteca = {
  codigo: string;
  titulo: string;
  descricao: string;
  norma: string;
  categoria: "NR" | "LIVRE";
  pontosChave: string[];
  reforco: string;
};

export function buildRoteiroLib(t: TemaBiblioteca): string {
  return `## Objetivo
${t.descricao}

## Por que importa
- Tema crítico para a segurança e a saúde da equipe na operação diária.
- Erro neste ponto pode resultar em acidente, doença ocupacional ou autuação.

## Pontos-chave a abordar
${t.pontosChave.map((p, i) => `${i + 1}. ${p}`).join("\n")}

## Aplicação prática na obra
- Inspecionar a frente de serviço de hoje à luz dos pontos acima.
- Comunicar ao líder qualquer condição insegura observada AGORA.
- Documentar (foto + APR) toda intervenção de risco antes de executar.

## Perguntas pra equipe
- "Alguém já presenciou ou viveu uma situação parecida? Como terminou?"
- "Olhando nossa frente agora, o que precisamos ajustar?"

## Reforço final
**${t.reforco}**

---
*Referência normativa: ${t.norma}*`;
}

export const TEMAS_BIBLIOTECA: TemaBiblioteca[] = [
  // ───────────────────── NRs adicionais (categoria=NR) ─────────────────────
  { codigo: "NR-02", titulo: "NR-02 — Inspeção Prévia", descricao: "Inspeção prévia do estabelecimento antes do início das atividades para liberação pelo órgão regional do MTE.",
    norma: "NR-02 (Portaria 3.214/78)", categoria: "NR",
    pontosChave: ["Documentação obrigatória antes da abertura", "Vistoria do MTE quando aplicável", "Layout aprovado e instalações mínimas", "Quem responde administrativamente"],
    reforco: "Sem inspeção prévia regularizada, a obra opera em situação irregular." },
  { codigo: "NR-03", titulo: "NR-03 — Embargo e Interdição", descricao: "Procedimentos de embargo de obra ou interdição de máquina/setor por risco grave e iminente.",
    norma: "NR-03 (Portaria SEPRT 1.068/2019)", categoria: "NR",
    pontosChave: ["O que é risco grave e iminente", "Quem pode embargar/interditar (auditor fiscal)", "Consequências para empresa e responsável técnico", "Como recorrer e regularizar"],
    reforco: "Embargo é a última barreira do Estado para evitar morte — não é burocracia." },
  { codigo: "NR-04", titulo: "NR-04 — SESMT", descricao: "Serviços Especializados em Engenharia de Segurança e Medicina do Trabalho — dimensionamento conforme grau de risco e nº de empregados.",
    norma: "NR-04 (Portaria SEPRT 1.245/2019)", categoria: "NR",
    pontosChave: ["Como saber o grau de risco da empresa (CNAE)", "Quem compõe o SESMT (Eng., Téc. Seg., Médico, Enfermeiro)", "Atribuições e atendimento na obra", "Quando é obrigatório por nº de funcionários"],
    reforco: "SESMT não é luxo — é exigência legal e técnica para grandes obras." },
  { codigo: "NR-05", titulo: "NR-05 — CIPA", descricao: "Comissão Interna de Prevenção de Acidentes — eleição, mandato, mapeamento de riscos e investigação de acidentes.",
    norma: "NR-05 (Portaria MTP 422/2021)", categoria: "NR",
    pontosChave: ["Quem pode ser cipeiro e como votar", "Atribuições mensais da CIPA", "Mapa de riscos do canteiro", "Estabilidade do cipeiro (não pode ser dispensado sem justa causa)"],
    reforco: "CIPA é a voz do trabalhador na segurança — participe das eleições." },
  { codigo: "NR-07", titulo: "NR-07 — PCMSO", descricao: "Programa de Controle Médico de Saúde Ocupacional — exames admissional, periódico, retorno, mudança de função e demissional.",
    norma: "NR-07 (Portaria MTP 6.734/2020)", categoria: "NR",
    pontosChave: ["Quais exames são obrigatórios e quando", "Validade do ASO (1 ano para insalubres, 2 anos demais)", "Direito do trabalhador à 2ª opinião médica", "Sigilo médico e LGPD"],
    reforco: "ASO atualizado é direito seu — sem ele você não pode trabalhar." },
  { codigo: "NR-08", titulo: "NR-08 — Edificações", descricao: "Requisitos mínimos de edificações no canteiro (pé-direito, iluminação, ventilação, escadas, pisos).",
    norma: "NR-08 (Portaria 3.214/78)", categoria: "NR",
    pontosChave: ["Pé-direito mínimo 3,0m", "Pisos antiderrapantes em áreas molhadas", "Iluminação adequada por atividade", "Sinalização de circulação"],
    reforco: "Estrutura ruim mata em silêncio: queda, choque, atropelamento começam aí." },
  { codigo: "NR-09", titulo: "NR-09 — Avaliação e Controle de Exposições", descricao: "Avaliação de exposições ocupacionais a agentes físicos, químicos e biológicos. Limites de tolerância e medidas de controle.",
    norma: "NR-09 (Portaria SEPRT 6.735/2020)", categoria: "NR",
    pontosChave: ["O que é Limite de Tolerância (LT)", "Hierarquia de controle (eliminar > substituir > engenharia > administrativo > EPI)", "Direito à informação sobre os riscos do posto", "Monitoramento periódico documentado"],
    reforco: "EPI é a última barreira — exija também controles coletivos." },
  { codigo: "NR-13", titulo: "NR-13 — Caldeiras, Vasos de Pressão e Tubulações", descricao: "Operação segura de caldeiras, vasos de pressão e tubulações. Inspeção periódica e habilitação do operador.",
    norma: "NR-13 (Portaria SEPRT 1.082/2018)", categoria: "NR",
    pontosChave: ["Categorias de caldeiras (A, B, C)", "Operador habilitado (curso 40h + estágio)", "Inspeções (interna, externa, hidrostática)", "PMTA e prontuário"],
    reforco: "Vaso de pressão sem inspeção é uma bomba — explosão mata em segundos." },
  { codigo: "NR-14", titulo: "NR-14 — Fornos", descricao: "Construção, operação e manutenção segura de fornos industriais. Riscos de calor, incêndio e gases.",
    norma: "NR-14 (Portaria 3.214/78)", categoria: "NR",
    pontosChave: ["Isolamento térmico adequado", "Sistemas de exaustão e ventilação", "Procedimento de partida e parada", "EPI específico (luva térmica, avental, viseira)"],
    reforco: "Calor radiante queima sem você encostar — distância e barreira sempre." },
  { codigo: "NR-15", titulo: "NR-15 — Atividades e Operações Insalubres", descricao: "Caracterização e adicional de insalubridade (10/20/40%) por exposição acima dos limites de tolerância.",
    norma: "NR-15 (Portaria 3.214/78 + alterações)", categoria: "NR",
    pontosChave: ["Anexos da NR-15 (ruído, calor, químicos, biológico)", "Cálculo do adicional (% sobre salário mínimo)", "Laudo técnico de insalubridade (LTCAT)", "Eliminação > redução > adicional"],
    reforco: "Adicional não compensa doença — exija eliminação do agente quando possível." },
  { codigo: "NR-16", titulo: "NR-16 — Atividades e Operações Perigosas", descricao: "Adicional de periculosidade (30%) por exposição a explosivos, inflamáveis, eletricidade, segurança patrimonial ou radiações.",
    norma: "NR-16 (Portaria 3.214/78 + alterações)", categoria: "NR",
    pontosChave: ["Atividades enquadradas (eletricitários, postos de combustível, vigilantes, motociclistas)", "Adicional 30% sobre salário base", "Não cumulativo com insalubridade", "Laudo técnico obrigatório"],
    reforco: "Periculosidade significa risco de morte súbita — adicional é só o reconhecimento." },
  { codigo: "NR-19", titulo: "NR-19 — Explosivos", descricao: "Depósito, manuseio e transporte de explosivos em canteiro de obras (detonação, demolição com explosivos).",
    norma: "NR-19 (Portaria 3.214/78)", categoria: "NR",
    pontosChave: ["Licença de blaster habilitado pelo Exército", "Paiol homologado e isolado", "Plano de fogo aprovado", "Sinalização de área de evacuação"],
    reforco: "Explosivo não dá segunda chance — só blaster com licença manuseia." },
  { codigo: "NR-21", titulo: "NR-21 — Trabalho a Céu Aberto", descricao: "Proteções contra intempéries (sol, chuva, vento, frio) em frentes de obra a céu aberto.",
    norma: "NR-21 (Portaria 3.214/78)", categoria: "NR",
    pontosChave: ["Abrigo para refeição e descanso", "Água potável fresca abundante", "Protetor solar e camisa manga longa UV", "Pausas em horário de pico de calor"],
    reforco: "Sol e chuva são riscos como qualquer outro — não trabalhe sem proteção." },
  { codigo: "NR-22", titulo: "NR-22 — Mineração", descricao: "Segurança e saúde em atividades de mineração a céu aberto e subterrânea (cavas, pedreiras, túneis).",
    norma: "NR-22 (Portaria SIT 2.037/1999)", categoria: "NR",
    pontosChave: ["PGR específico para mineração", "Ventilação e atmosfera em subterrâneo", "Sinalização de tráfego de equipamentos", "Treinamento admissional de 40h"],
    reforco: "Subterrâneo não perdoa atalho — siga procedimento, sempre." },
  { codigo: "NR-25", titulo: "NR-25 — Resíduos Industriais", descricao: "Destinação adequada de resíduos sólidos, líquidos e gasosos gerados na obra (entulho, óleo, sucata, químicos).",
    norma: "NR-25 (Portaria SEPRT 1.083/2019)", categoria: "NR",
    pontosChave: ["Segregação na origem (lixeiras coloridas)", "PGRCC obrigatório (Plano Gestão de Resíduos)", "Empresa licenciada para coleta", "Manifesto de transporte de resíduos perigosos"],
    reforco: "Resíduo descartado errado vira multa, contaminação e processo." },
  { codigo: "NR-28", titulo: "NR-28 — Fiscalização e Penalidades", descricao: "Como funciona a fiscalização do MTE: notificação, autuação, multa, embargo e recursos.",
    norma: "NR-28 (Portaria 3.214/78)", categoria: "NR",
    pontosChave: ["Direitos e deveres durante fiscalização", "Tipos de infração (leve, média, grave, gravíssima)", "Valores de multa por infração", "Prazo para defesa e recurso"],
    reforco: "Fiscalização é oportunidade de regularizar — colabore e documente." },
  { codigo: "NR-29", titulo: "NR-29 — Trabalho Portuário", descricao: "Segurança em operações portuárias (carga/descarga, navio, terminal). Aplicável a obras em portos.",
    norma: "NR-29 (Portaria SEPRT 1.084/2019)", categoria: "NR",
    pontosChave: ["Embarque e desembarque seguro", "Iluminação noturna", "Sinalização de tráfego de máquinas pesadas", "Salva-vidas em trabalho próximo à água"],
    reforco: "Cair na água com bota e capacete = afogamento em segundos." },
  { codigo: "NR-30", titulo: "NR-30 — Trabalho Aquaviário", descricao: "Segurança em embarcações e plataformas (pesca, transporte, offshore). Treinamento STCW.",
    norma: "NR-30 (Portaria SIT 34/2002)", categoria: "NR",
    pontosChave: ["Curso STCW obrigatório para tripulantes", "Coletes salva-vidas certificados", "Plano de abandono e simulado", "Comunicação com Capitania dos Portos"],
    reforco: "Mar não tem sinalização — preparação é a única defesa." },
  { codigo: "NR-31", titulo: "NR-31 — Agricultura, Pecuária, Silvicultura", descricao: "Segurança em atividades rurais. Aplicável a obras em propriedade rural ou paisagismo de grande porte.",
    norma: "NR-31 (Portaria SEPRT 1.069/2019)", categoria: "NR",
    pontosChave: ["Manuseio seguro de agrotóxicos", "Uso de tratores e implementos", "Trabalho com animais grandes", "Insolação e desidratação no campo"],
    reforco: "Campo isolado = socorro lento. Previna sempre." },
  { codigo: "NR-32", titulo: "NR-32 — Segurança em Serviços de Saúde", descricao: "Aplicável a obras em hospitais, clínicas e laboratórios — risco biológico, perfurocortantes, químicos hospitalares.",
    norma: "NR-32 (Portaria MTE 485/2005)", categoria: "NR",
    pontosChave: ["Vacinação obrigatória (Hep. B, dT, Tríplice Viral)", "Gestão de perfurocortantes (caixa rígida)", "Risco biológico classes 1-4", "Quimioterápicos e gases medicinais"],
    reforco: "Em hospital o risco invisível é maior que o visível — biossegurança total." },
  { codigo: "NR-34", titulo: "NR-34 — Construção e Reparo Naval", descricao: "Segurança em estaleiros e oficinas navais (soldagem em casco, espaços confinados navais, içamento de blocos).",
    norma: "NR-34 (Portaria SIT 200/2011)", categoria: "NR",
    pontosChave: ["Permissão de Trabalho para soldagem em casco", "Atmosfera em tanques e porões", "Andaimes em curva (casco)", "Líder de equipe habilitado"],
    reforco: "Casco não perdoa erro de PT — sempre confirme atmosfera antes." },
  { codigo: "NR-36", titulo: "NR-36 — Indústria de Abate e Processamento de Carnes", descricao: "Aplicável a obras em frigoríficos. Riscos de frio, ruído, postura forçada, perfurocortantes.",
    norma: "NR-36 (Portaria MTE 555/2013)", categoria: "NR",
    pontosChave: ["Pausa térmica obrigatória em câmara fria", "Rodízio de função para evitar LER/DORT", "Piso antiderrapante (gordura)", "Facas e serras com proteção"],
    reforco: "Frigorífico tem 4 riscos somados — atenção redobrada em qualquer reparo." },
  { codigo: "NR-37", titulo: "NR-37 — Plataformas de Petróleo", descricao: "Segurança em plataformas marítimas (offshore). Aplicável a obras de manutenção e ampliação.",
    norma: "NR-37 (Portaria MT 1.186/2018)", categoria: "NR",
    pontosChave: ["Curso CBSP/HUET obrigatório", "PT integrada (hot work, espaço confinado, altura, içamento)", "Helideck e procedimentos de evacuação", "Comunicação com sala de controle"],
    reforco: "Offshore = isolamento total. Procedimento é lei, não recomendação." },
  { codigo: "NR-38", titulo: "NR-38 — Limpeza Urbana e Manejo de Resíduos", descricao: "Segurança para coletores e operadores de varrição, coleta seletiva, aterros e usinas de triagem.",
    norma: "NR-38 (Portaria MTP 4.219/2022)", categoria: "NR",
    pontosChave: ["Risco biológico em coleta domiciliar", "Atropelamento (caminhão de coleta)", "Vacinação obrigatória", "EPI específico (luva anticorte, bota PVC, máscara)"],
    reforco: "Resíduo tem agulha, vidro, químico — luva nunca é exagero." },

  // ───────────────────── Atividades de obra (LIVRE) ─────────────────────
  { codigo: "OBRA-ESCAVACAO-MANUAL", titulo: "Escavação Manual de Vala", descricao: "Riscos e procedimentos seguros para escavação manual de valas até 1,25m de profundidade.",
    norma: "NR-18.13 + NR-12 Anexo VII", categoria: "LIVRE",
    pontosChave: ["Inclinação do talude conforme tipo de solo", "Escoramento obrigatório acima de 1,25m", "Sinalização e isolamento da escavação", "Saída de emergência (escada cada 25m)"],
    reforco: "Solo aparentemente firme pode desabar em 3 segundos — escora sempre." },
  { codigo: "OBRA-ESCAVACAO-MEC", titulo: "Escavação Mecanizada", descricao: "Operação segura de retroescavadeira, mini-escavadeira e bate-estaca em frente de serviço.",
    norma: "NR-12 + NR-18", categoria: "LIVRE",
    pontosChave: ["Operador habilitado (NR-11/12)", "Raio de ação isolado e sinalizado", "Comunicação visual/rádio com sinaleiro", "Verificação de redes subterrâneas (gás, energia, água)"],
    reforco: "Esmagamento por máquina é instantâneo — fique fora do raio de giro." },
  { codigo: "OBRA-DEMOLICAO-MAN", titulo: "Demolição Manual", descricao: "Demolição com marreta, ponteira, pá e carrinho — riscos de queda de materiais, projeção e poeira.",
    norma: "NR-18.5 + NR-15 Anexo 12 (poeira)", categoria: "LIVRE",
    pontosChave: ["Demolir de cima para baixo", "Isolar área externa (queda de cacos)", "Umectação para abater poeira", "Inspeção de estabilidade após cada etapa"],
    reforco: "Ordem reversa da construção. Improvisar = enterro." },
  { codigo: "OBRA-DEMOLICAO-MEC", titulo: "Demolição Mecânica", descricao: "Demolição com martelete pneumático, rompedor, marreta hidráulica em escavadeira.",
    norma: "NR-18.5 + NR-12", categoria: "LIVRE",
    pontosChave: ["Plano de demolição assinado por engenheiro", "Isolamento mínimo 2x altura da estrutura", "Análise estrutural antes de remover apoios", "Sinaleiro permanente"],
    reforco: "Estrutura demolida é imprevisível — todo movimento é cálculo, não chute." },
  { codigo: "OBRA-ICAMENTO-CARGA", titulo: "Içamento de Cargas (Manobra)", descricao: "Procedimento de içamento com guindaste, grua, talha — peso, ângulo, eslingas, sinaleiro.",
    norma: "NR-11 + NR-18.14", categoria: "LIVRE",
    pontosChave: ["Verificar peso x capacidade (carta de carga)", "Acessórios certificados (eslinga, manilha, gancho)", "Ângulo entre pernas máx. 60°", "Ninguém sob a carga suspensa"],
    reforco: "Carga suspensa = bomba pendular. Saia de baixo SEMPRE." },
  { codigo: "OBRA-ALVENARIA", titulo: "Alvenaria de Vedação e Estrutural", descricao: "Assentamento de blocos cerâmicos/concreto — postura, cargas, ergonomia, andaime fachadeiro.",
    norma: "NR-17 + NR-18", categoria: "LIVRE",
    pontosChave: ["Bandeja de argamassa na altura da cintura", "Andaime regularizado (NR-18 Anexo IV)", "EPI: luva, óculos, máscara para cimento", "Pausas a cada 50min"],
    reforco: "Coluna não se reconstrói — postura correta agora poupa anos depois." },
  { codigo: "OBRA-GESSO-DRYWALL", titulo: "Gesso e Drywall", descricao: "Instalação de placas de gesso, drywall, perfis metálicos — corte, fixação, acabamento.",
    norma: "NR-6 + NR-18", categoria: "LIVRE",
    pontosChave: ["Máscara PFF2 contra pó de gesso", "Luva anticorte para perfis metálicos", "Estilete com lâmina retrátil", "Iluminação suficiente para corte preciso"],
    reforco: "Pó de gesso seca via aérea — máscara não é opção." },
  { codigo: "OBRA-PINTURA", titulo: "Pintura (Tinta, Solvente, Verniz)", descricao: "Aplicação de tintas látex, esmalte, verniz, primer — riscos químicos, postura, andaime.",
    norma: "NR-15 Anexo 11 + NR-18", categoria: "LIVRE",
    pontosChave: ["Ventilação cruzada em área fechada", "Máscara semifacial com filtro orgânico", "Não comer/beber/fumar próximo à tinta", "Descarte correto de embalagens"],
    reforco: "Solvente é veneno via pulmão — ventilação e máscara, sempre." },
  { codigo: "OBRA-IMPERM", titulo: "Impermeabilização", descricao: "Aplicação de manta asfáltica, asfalto a quente, emulsão, poliuretano — calor, queimadura, fumos tóxicos.",
    norma: "NR-15 + NR-18", categoria: "LIVRE",
    pontosChave: ["Maçarico só com PT (Permissão Trabalho a Quente)", "Extintor de PQS próximo", "Luva térmica para asfalto quente", "Ventilação para fumos de poliuretano"],
    reforco: "Asfalto a 200°C gruda na pele e queima até a carne — luva térmica certificada." },
  { codigo: "OBRA-TELHADO", titulo: "Telhado e Cobertura", descricao: "Trabalho em telhados (telha cerâmica, fibrocimento, metálica) — risco principal: queda de altura.",
    norma: "NR-35 + NR-18", categoria: "LIVRE",
    pontosChave: ["Linha de vida horizontal antes de subir", "Cinto paraquedista + talabarte duplo", "Tábuas de circulação (telha não pisa)", "Isolamento da projeção embaixo"],
    reforco: "Telha quebra com 60kg em ponto errado. Linha de vida = sua vida." },
  { codigo: "OBRA-FACHADA", titulo: "Revestimento de Fachada", descricao: "Revestimento de fachada com argamassa, cerâmica, ACM, pastilha — andaime suspenso, balancim.",
    norma: "NR-18 + NR-35", categoria: "LIVRE",
    pontosChave: ["Andaime suspenso só com projeto e ART", "Cinto + talabarte ancorado em ponto INDEPENDENTE", "Isolamento do solo (queda de objeto)", "Inspeção diária dos cabos"],
    reforco: "Balancim cai. Cinto independente é sua segunda vida." },
  { codigo: "OBRA-ELET-INST", titulo: "Instalação Elétrica de Obra", descricao: "Instalação de quadros, eletrodutos, fiação provisória do canteiro — risco de choque, arco.",
    norma: "NR-10 + NBR 5410", categoria: "LIVRE",
    pontosChave: ["Profissional habilitado (eletricista com NR-10)", "DR (Diferencial Residual) em todos os circuitos", "Aterramento de todas as estruturas metálicas", "Cabos protegidos contra abrasão"],
    reforco: "Choque mata em 1 segundo — habilitação NR-10 é obrigatória, não burocracia." },
  { codigo: "OBRA-HIDR-INST", titulo: "Instalação Hidráulica e Sanitária", descricao: "Instalação de tubulações de água, esgoto, gás — riscos de corte, queda em poço, gases.",
    norma: "NR-18 + NBR 5626", categoria: "LIVRE",
    pontosChave: ["Teste de estanqueidade antes de fechar", "Espaço confinado em poço de visita = NR-33", "Cola PVC em local ventilado", "Não soldar PEAD próximo a inflamável"],
    reforco: "Poço fechado vira armadilha — sempre PT antes de descer." },
  { codigo: "OBRA-LAJE", titulo: "Concretagem de Laje", descricao: "Concretagem de laje protendida, maciça, nervurada — bombeamento, vibração, cura, escoramento.",
    norma: "NR-18 + NBR 14931", categoria: "LIVRE",
    pontosChave: ["Escoramento conferido por engenheiro", "Mangueira de bomba com cabo-guia", "Vibrador de imersão com proteção dupla isolação", "Não pisar na ferragem solta"],
    reforco: "Laje cai antes do concreto curar — escora não é decoração." },
  { codigo: "OBRA-FORMAS", titulo: "Montagem e Desforma", descricao: "Montagem de formas de madeira/metálica e desforma após cura — risco de prego, queda, esmagamento.",
    norma: "NR-18", categoria: "LIVRE",
    pontosChave: ["Pregos virados ou retirados", "Desforma só após resistência mínima (28 dias para laje)", "Formas grandes só com içamento", "EPI: luva, óculos, capacete"],
    reforco: "Prego no pé = tétano. dT em dia + bota anti-perfuração." },
  { codigo: "OBRA-ARMACAO", titulo: "Armação de Aço (CA-50/60)", descricao: "Corte, dobra e montagem de ferragens — risco de corte, projeção, postura, lança-pontas.",
    norma: "NR-12 + NR-18", categoria: "LIVRE",
    pontosChave: ["Pontas de vergalhão com cogumelo plástico", "Luva anticorte para amarração", "Óculos para corte com policorte", "Postura ao dobrar (joelho, não coluna)"],
    reforco: "Vergalhão sem cogumelo + queda = empalamento. Cobre TODA ponta." },
  { codigo: "OBRA-CONCRETAGEM", titulo: "Concretagem com Caminhão Bomba", descricao: "Recebimento e lançamento de concreto via bomba — pressão, queda, projeção.",
    norma: "NR-18 + NR-12", categoria: "LIVRE",
    pontosChave: ["Bomba só com operador habilitado", "Mangueira de saída com cabo-guia (chicote)", "Sinaleiro entre bomba e frente de lançamento", "Não posicionar mão na boca da mangueira"],
    reforco: "Chicote da mangueira amputa em 1 piscar — distância de 1,5m sempre." },
  { codigo: "OBRA-VIBRADOR", titulo: "Vibrador de Imersão", descricao: "Adensamento do concreto com vibrador elétrico ou pneumático — choque, vibração mão-braço.",
    norma: "NR-12 + NR-15 Anexo 8", categoria: "LIVRE",
    pontosChave: ["Cabo elétrico íntegro (sem emendas)", "Aterramento + DR no circuito", "Pausas a cada 30min (vibração)", "Não usar em poça de água sem isolação"],
    reforco: "Vibrador molhado + emenda exposta = morte por choque." },
  { codigo: "OBRA-ESCORAMENTO", titulo: "Escoramento Provisório", descricao: "Montagem e desmontagem de escoras metálicas e de madeira para lajes e paredes.",
    norma: "NR-18", categoria: "LIVRE",
    pontosChave: ["Cálculo do escoramento por engenheiro", "Travamento horizontal entre escoras", "Inspeção diária (afundamento, deslocamento)", "Desforma só após resistência calculada"],
    reforco: "Escora sem travamento é só uma vara — colapso da laje em segundos." },
  { codigo: "OBRA-CERAMICA", titulo: "Assentamento de Cerâmica e Porcelanato", descricao: "Assentamento de revestimentos cerâmicos — corte com policorte, postura, pó.",
    norma: "NR-17 + NR-18", categoria: "LIVRE",
    pontosChave: ["Policorte com guarda fixa e óculos", "Postura ajoelhado com joelheira", "Máscara contra pó de cerâmica/cimento", "Iluminação adequada para nivelamento"],
    reforco: "Sílica do corte = silicose lenta e mortal. Máscara PFF2 sempre." },
  { codigo: "OBRA-MARMORARIA", titulo: "Marmoraria e Bancadas", descricao: "Corte e assentamento de mármore, granito, quartzo — peso, sílica, transporte.",
    norma: "NR-18 + NR-15 Anexo 12", categoria: "LIVRE",
    pontosChave: ["Içamento mecanizado (peso > 30kg)", "Corte com refrigeração a água (abate sílica)", "Máscara PFF3 + óculos ampla visão", "Bota com biqueira de aço"],
    reforco: "Silicose não tem cura. Água + máscara não é opção." },
  { codigo: "OBRA-ESQ-ALU", titulo: "Esquadrias de Alumínio", descricao: "Montagem de portas e janelas de alumínio — corte, peso, vidros, queda em vão.",
    norma: "NR-6 + NR-18 + NR-35", categoria: "LIVRE",
    pontosChave: ["Vão fechado provisoriamente até instalar a esquadria", "Cinto + talabarte para janela em altura", "Luva anticorte para manuseio de vidro", "Equipe de 2 para esquadria > 1,5m"],
    reforco: "Vão aberto + tropeço = queda livre. Fechamento provisório SEMPRE." },
  { codigo: "OBRA-VIDRACARIA", titulo: "Vidraçaria e Pele de Vidro", descricao: "Manuseio, transporte e instalação de vidros — corte, queda, projeção em quebra.",
    norma: "NR-6 + NR-18", categoria: "LIVRE",
    pontosChave: ["Luva anticorte nível 5", "Manga longa e calça grossa", "Transporte com ventosas certificadas", "Isolamento embaixo durante içamento"],
    reforco: "Vidro quebra em estilhaço cortante — luva e manga, sem exceção." },
  { codigo: "OBRA-SOLDAGEM", titulo: "Soldagem (Eletrodo, MIG, MAG, TIG)", descricao: "Soldagem elétrica e a gás — radiação UV, queimadura, fumos metálicos, choque, incêndio.",
    norma: "NR-10 + NR-15 Anexo 11 + NR-23", categoria: "LIVRE",
    pontosChave: ["Permissão de Trabalho a Quente (PT)", "Máscara automática + avental + perneira", "Exaustão local para fumos", "Extintor PQS próximo + monitor de fogo"],
    reforco: "Centelha viva 3m de distância. PT + monitor de fogo, sempre." },
  { codigo: "OBRA-OXICORTE", titulo: "Oxicorte e Goivagem", descricao: "Corte com maçarico oxiacetilênico — gases inflamáveis, projeção de escória, retorno de chama.",
    norma: "NR-15 + NR-23", categoria: "LIVRE",
    pontosChave: ["Válvula corta-chama em ambos os cilindros", "Cilindros amarrados na vertical", "PT a Quente assinada", "Roupa de couro + viseira"],
    reforco: "Cilindro deitado vira foguete em incêndio. Vertical e amarrado." },
  { codigo: "OBRA-PLASMA", titulo: "Corte com Plasma", descricao: "Corte de chapas metálicas com plasma — risco elétrico, ruído, fumos, projeção.",
    norma: "NR-10 + NR-15", categoria: "LIVRE",
    pontosChave: ["Equipamento aterrado + DR", "Protetor auricular plug + concha", "Máscara para fumos metálicos", "Mesa de corte com aspiração"],
    reforco: "Plasma a 30.000°C — qualquer falha de proteção é queimadura grave." },
  { codigo: "OBRA-PAISAGISMO", titulo: "Paisagismo e Jardinagem", descricao: "Atividades de paisagismo — corte de grama, poda, plantio, agrotóxicos, picadas.",
    norma: "NR-31 + NR-15", categoria: "LIVRE",
    pontosChave: ["Roçadeira com cinto e protetor", "EPI químico para agrotóxico (luva nitrílica, macacão)", "Bota de cano longo (cobra/escorpião)", "Hidratação constante (sol)"],
    reforco: "Mato esconde bicho — bota e calça grossa não negociam." },
  { codigo: "OBRA-LAJOTAS-PAVI", titulo: "Pavimentação com Lajotas", descricao: "Assentamento de lajotas/pavi/intertravado em piso — peso, postura, máquina compactadora.",
    norma: "NR-12 + NR-17", categoria: "LIVRE",
    pontosChave: ["Compactador placa com proteção anti-vibração", "Joelheira + luva", "Pausa a cada 50min", "Sinalização de tráfego (obra em via)"],
    reforco: "Mão de obra agachada o dia inteiro = problema de joelho aos 40. Pausa." },
  { codigo: "OBRA-PRE-MOLD", titulo: "Montagem de Pré-Moldados", descricao: "Içamento e montagem de pilares, vigas, lajes pré-moldadas — peso elevado, queda, esmagamento.",
    norma: "NR-18 + NR-11", categoria: "LIVRE",
    pontosChave: ["Plano de rigging com engenheiro", "Eslingas e manilhas certificadas", "Travamento provisório imediato após posicionar", "Monitor de içamento (ART)"],
    reforco: "Pré-moldado errado vira dominó — travamento provisório é vida." },

  // ───────────────────── Equipamentos e ferramentas (LIVRE) ─────────────────────
  { codigo: "EQP-ESMERILHADEIRA", titulo: "Esmerilhadeira Angular", descricao: "Operação segura de esmerilhadeira (lixadeira angular) — projeção, ruído, vibração.",
    norma: "NR-12 + NR-15", categoria: "LIVRE",
    pontosChave: ["Disco compatível com RPM da máquina", "Guarda fixa SEMPRE instalada", "Óculos ampla visão + face shield", "Não usar disco trincado"],
    reforco: "Disco a 11.000 RPM trincado vira faca. Inspeção visual antes de cada corte." },
  { codigo: "EQP-SERRA-CIRC", titulo: "Serra Circular de Bancada", descricao: "Operação de serra circular para madeira — corte de mão, projeção, ruído.",
    norma: "NR-12 Anexo I", categoria: "LIVRE",
    pontosChave: ["Cutelo divisor + coifa de proteção", "Empurrador para peças pequenas", "Nunca remover proteção 'pra agilizar'", "Disco afiado e limpo"],
    reforco: "Serra de bancada arranca dedo em milésimo. Empurrador é obrigatório." },
  { codigo: "EQP-SERRA-MARMORE", titulo: "Serra Mármore (Makita)", descricao: "Corte de cerâmica, granito, mármore com serra mármore portátil.",
    norma: "NR-12", categoria: "LIVRE",
    pontosChave: ["Refrigeração a água ligada", "Disco diamantado próprio para o material", "Óculos ampla visão + máscara PFF2", "Apoio firme da peça"],
    reforco: "Sem água = sílica voando livre. Refrigeração SEMPRE ligada." },
  { codigo: "EQP-FURADEIRA-IMP", titulo: "Furadeira de Impacto", descricao: "Furação em alvenaria e concreto com furadeira de impacto — vibração, projeção, choque.",
    norma: "NR-12 + NR-15", categoria: "LIVRE",
    pontosChave: ["Cabo de alimentação íntegro", "Aterramento + DR", "Óculos para projeção", "Pausa a cada 30min (vibração)"],
    reforco: "Vibração crônica = síndrome mão-braço. Pausa programada." },
  { codigo: "EQP-MARTELETE", titulo: "Martelete Demolidor", descricao: "Demolição com martelete pneumático ou elétrico — vibração, ruído extremo, projeção.",
    norma: "NR-12 + NR-15 Anexos 1 e 8", categoria: "LIVRE",
    pontosChave: ["Protetor auricular plug + concha (>110 dB)", "Luva antivibração", "Pausa de 10min a cada 50min", "Bota com biqueira"],
    reforco: "Martelete = ruído + vibração somados. Dupla proteção sempre." },
  { codigo: "EQP-PARAFUSADEIRA", titulo: "Parafusadeira e Atarrachadeira", descricao: "Uso de parafusadeira a bateria e atarrachadeira para fixação — torque, projeção.",
    norma: "NR-12", categoria: "LIVRE",
    pontosChave: ["Bit compatível e firme no mandril", "Ajuste de torque adequado", "Óculos para projeção (parafuso voador)", "Bateria carregada (motor não ‘queima’)"],
    reforco: "Bit solto a 3.000 RPM é projétil — confira mandril toda troca." },
  { codigo: "EQP-LIXADEIRA", titulo: "Lixadeira Orbital e Cinta", descricao: "Lixamento de superfícies com lixadeira orbital, cinta ou roto-orbital.",
    norma: "NR-12 + NR-15 Anexo 12", categoria: "LIVRE",
    pontosChave: ["Sistema de aspiração de pó", "Máscara PFF2 (sílica/madeira)", "Lixa adequada ao material", "Não forçar (queima motor)"],
    reforco: "Pó de lixa entra no pulmão — máscara não é frescura." },
  { codigo: "EQP-PLAINA", titulo: "Plaina e Tupia", descricao: "Aplainamento e moldura de madeira com plaina e tupia portátil ou de bancada.",
    norma: "NR-12 Anexo I", categoria: "LIVRE",
    pontosChave: ["Cutelo afiado e alinhado", "Coifa de proteção fixa", "Empurrador para peças curtas", "Manga ajustada (não pode prender)"],
    reforco: "Plaina é o equipamento que mais arranca dedo na obra. Empurrador SEMPRE." },
  { codigo: "EQP-BETONEIRA", titulo: "Betoneira", descricao: "Operação e manutenção de betoneira de canteiro — esmagamento, choque, queda.",
    norma: "NR-12", categoria: "LIVRE",
    pontosChave: ["Aterramento elétrico", "Proteção da coroa e pinhão", "Não introduzir mão/pá com tambor girando", "Travamento mecânico para limpeza"],
    reforco: "Tambor em movimento = mão arrancada. Pare e trave para limpar." },
  { codigo: "EQP-VIBRADOR-IMERSAO", titulo: "Vibrador de Imersão (Mangote)", descricao: "Adensamento de concreto com vibrador de imersão tipo mangote elétrico ou pneumático.",
    norma: "NR-12 + NR-10", categoria: "LIVRE",
    pontosChave: ["Cabo elétrico íntegro (sem emenda)", "Aterramento + DR obrigatório", "Bota de borracha em concretagem", "Pausa por vibração mão-braço"],
    reforco: "Mangote em poça + emenda = morte por choque. Inspecione cabo todo dia." },
  { codigo: "EQP-COMPACTADOR-PLACA", titulo: "Compactador de Placa Vibratória", descricao: "Compactação de solo com placa vibratória (sapinho) — vibração, ruído, gases de escape.",
    norma: "NR-12 + NR-15", categoria: "LIVRE",
    pontosChave: ["Protetor auricular plug + concha", "Luva antivibração", "Não usar em ambiente fechado (CO)", "Combustível com máquina FRIA"],
    reforco: "Motor 4 tempos em local fechado = monóxido em silêncio. Ventilação total." },
  { codigo: "EQP-ROLO-COMP", titulo: "Rolo Compactador (Vibratório)", descricao: "Operação de rolo compactador para terraplenagem e pavimentação.",
    norma: "NR-12 + NR-11", categoria: "LIVRE",
    pontosChave: ["Operador com habilitação adequada", "Sinaleiro em mudança de direção", "Cinto de segurança no cockpit", "ROPS (proteção contra capotagem)"],
    reforco: "Capotagem em rolo é instantânea — cinto + ROPS são vida." },
  { codigo: "EQP-BATE-ESTACA", titulo: "Bate-Estaca", descricao: "Cravação de estacas com bate-estaca (a queda livre, hidráulico ou diesel).",
    norma: "NR-12 + NR-18", categoria: "LIVRE",
    pontosChave: ["Operador habilitado + sinaleiro", "Isolamento total da área de cravação", "Cabos de aço inspecionados diariamente", "Verificação de inclinação da torre"],
    reforco: "Estaca caindo de 5m = morte instantânea. Isolamento absoluto." },
  { codigo: "EQP-BOMBA-LANCA", titulo: "Caminhão Bomba (Lança)", descricao: "Caminhão bomba de concreto com lança hidráulica — chicote da mangueira, contato com rede elétrica.",
    norma: "NR-12 + NR-10", categoria: "LIVRE",
    pontosChave: ["Distância mínima de 3m de rede elétrica energizada", "Cabo-guia (chicote) na ponta da mangueira", "Sapatas niveladas e calçadas", "Operador permanente no pedestal"],
    reforco: "Lança encostando em rede = explosão de arco. 3m mínimos, sempre." },
  { codigo: "EQP-GUINCHO-COLUNA", titulo: "Guincho de Coluna (Manual e Elétrico)", descricao: "Içamento vertical com guincho de coluna em obra (mudança, materiais).",
    norma: "NR-11 + NR-18", categoria: "LIVRE",
    pontosChave: ["Capacidade de carga visível", "Inspeção diária do cabo de aço", "Travamento no pavimento (não improviso)", "Sinaleiro entre patamares"],
    reforco: "Guincho amador = morte previsível. Equipamento certificado, sempre." },
  { codigo: "EQP-TALHA-ELET", titulo: "Talha Elétrica e Manual", descricao: "Içamento horizontal/vertical com talha elétrica ou de corrente manual.",
    norma: "NR-11", categoria: "LIVRE",
    pontosChave: ["Capacidade x peso da carga", "Inspeção da corrente (elos)", "Botoeira pendente íntegra", "Não passar por baixo da carga"],
    reforco: "Corrente desgastada arrebenta sem aviso — inspeção mensal documentada." },
  { codigo: "EQP-BALANCIM", titulo: "Balancim Manual e Elétrico", descricao: "Plataforma suspensa para fachada (balancim) — tipos manual e elétrico.",
    norma: "NR-18 Anexo IV + NR-35", categoria: "LIVRE",
    pontosChave: ["Projeto + ART do balancim", "Cinto + talabarte em ponto INDEPENDENTE", "Inspeção diária (cabos, motor, freio)", "Carga máx. 250kg + 2 trabalhadores"],
    reforco: "Balancim cai. Talabarte em ponto INDEPENDENTE — não no balancim." },
  { codigo: "EQP-PLATAF-TESOURA", titulo: "Plataforma Elevatória Tesoura", descricao: "PEMT tipo tesoura para trabalho em altura interna ou externa.",
    norma: "NR-18 + NR-35", categoria: "LIVRE",
    pontosChave: ["Operador habilitado IPAF/curso interno", "Inspeção pré-uso (checklist)", "Solo nivelado e firme", "Cinto de segurança no cesto"],
    reforco: "Tesoura tomba se solo cede. Verificação de piso é obrigatória." },
  { codigo: "EQP-PLATAF-ARTIC", titulo: "Plataforma Elevatória Articulada", descricao: "PEMT articulada (lança) para trabalho em altura com alcance horizontal.",
    norma: "NR-18 + NR-35", categoria: "LIVRE",
    pontosChave: ["Operador IPAF certificado", "Cinto + talabarte ANCORADO no cesto", "Não estender braço fora do cesto", "Velocidade do vento < 12,5 m/s"],
    reforco: "Cesto não é varanda. Cinto ancorado e dois pés no chão." },
  { codigo: "EQP-GERADOR", titulo: "Gerador a Diesel/Gasolina", descricao: "Operação de grupo gerador no canteiro — combustível, ruído, gases, choque.",
    norma: "NR-10 + NR-23", categoria: "LIVRE",
    pontosChave: ["Aterramento obrigatório", "Local ventilado (gases)", "Tanque com bacia de contenção", "Extintor PQS próximo"],
    reforco: "Gerador em local fechado = monóxido invisível. Ventilação total." },
  { codigo: "EQP-COMPRESSOR", titulo: "Compressor de Ar", descricao: "Operação de compressor de ar para ferramentas pneumáticas — pressão, ruído, óleo.",
    norma: "NR-13 (pequenos vasos) + NR-12", categoria: "LIVRE",
    pontosChave: ["Reservatório com prontuário (NR-13)", "Válvula de segurança testada", "Drenagem diária do reservatório", "Mangueira com travas de segurança"],
    reforco: "Reservatório vence — explode como bomba. Inspeção NR-13 em dia." },
  { codigo: "EQP-MANGUEIRA-PRES", titulo: "Mangueira de Alta Pressão", descricao: "Uso de mangueiras de ar comprimido, água ou hidrojato — chicote, projeção.",
    norma: "NR-12", categoria: "LIVRE",
    pontosChave: ["Travas de segurança (whip check)", "Não apontar para colega 'de brincadeira'", "Inspeção visual antes de cada uso", "Pressão de trabalho conferida"],
    reforco: "Mangueira solta vira chicote a 200km/h. Trava em toda conexão." },
  { codigo: "EQP-LAVADORA-AP", titulo: "Lavadora de Alta Pressão", descricao: "Limpeza com lavadora de alta pressão (até 200 bar) — corte da pele, projeção.",
    norma: "NR-12 + NR-6", categoria: "LIVRE",
    pontosChave: ["Não apontar para o corpo (corta a pele)", "Bota de borracha + óculos ampla visão", "Cabo elétrico afastado da água", "Distância mínima da superfície"],
    reforco: "200 bar abre a pele em 3cm — distância e EPI sempre." },
  { codigo: "EQP-MAKITA-PERFO", titulo: "Martelete Perfurador (Makita HR)", descricao: "Perfuração e leve demolição em concreto com martelete perfurador.",
    norma: "NR-12 + NR-15", categoria: "LIVRE",
    pontosChave: ["Broca SDS travada corretamente", "Aterramento + DR", "Óculos ampla visão", "Não usar para alavancar (broca quebra)"],
    reforco: "Broca SDS mal encaixada voa — checagem antes de cada furo." },

  // ───────────────────── EPI específico (LIVRE) ─────────────────────
  { codigo: "EPI-CAPACETE", titulo: "Capacete de Segurança (Tipo I/II)", descricao: "Uso correto, inspeção e higienização do capacete de segurança Classe A/B com jugular.",
    norma: "NR-6 + ABNT NBR 8221", categoria: "LIVRE",
    pontosChave: ["CA válido (consultar gov.br)", "Jugular sempre afivelada", "Carneira ajustada (1 dedo entre cabeça e topo)", "Trocar ao primeiro impacto"],
    reforco: "Capacete sem jugular é boné — voa no susto que mais precisa." },
  { codigo: "EPI-OCULOS-AV", titulo: "Óculos Ampla Visão", descricao: "Óculos de proteção ampla visão para projeção, pó e químicos leves.",
    norma: "NR-6", categoria: "LIVRE",
    pontosChave: ["Vedação total (sem fresta lateral)", "Lente policarbonato", "Antiembaçante para uso prolongado", "Higienização com pano macio"],
    reforco: "Ampla visão substitui óculos comum — protege ângulo lateral." },
  { codigo: "EPI-OCULOS-SOLDA", titulo: "Óculos/Máscara de Solda", descricao: "Proteção visual para solda elétrica e oxicorte — radiação UV/IV intensa.",
    norma: "NR-6 + NR-15 Anexo 7", categoria: "LIVRE",
    pontosChave: ["Tonalidade adequada ao processo (solda elétrica DIN 11+)", "Máscara automática quando possível", "Avental + perneira de couro", "Proteção do auxiliar"],
    reforco: "Olhar arco descoberto = ‘mal de ferro’ noturno. Máscara automática salva." },
  { codigo: "EPI-AUR-PLUG", titulo: "Protetor Auricular Tipo Plug", descricao: "Proteção auditiva tipo plug (espuma ou silicone) para ruído contínuo até 110 dB.",
    norma: "NR-6 + NR-15 Anexo 1", categoria: "LIVRE",
    pontosChave: ["Inserção correta (puxar orelha para cima/trás)", "Higienização do tipo silicone", "Trocar espuma quando perder elasticidade", "Não usar emprestado (ouvido externo)"],
    reforco: "Plug torto = proteção zero. Veja vídeo de inserção correta." },
  { codigo: "EPI-AUR-CONCHA", titulo: "Protetor Auricular Tipo Concha", descricao: "Proteção auditiva tipo concha para ruído impacto e contínuo > 110 dB.",
    norma: "NR-6 + NR-15 Anexo 1", categoria: "LIVRE",
    pontosChave: ["Vedação completa nos lados", "Conchas adaptáveis a barba (cabelo curto)", "Combinação plug + concha em ruído > 105 dB", "Higienização semanal"],
    reforco: "Surdez é silenciosa e definitiva — proteção dupla em ruído alto." },
  { codigo: "EPI-PFF1", titulo: "Máscara Descartável PFF1", descricao: "Máscara semifacial descartável tipo PFF1 contra poeira de baixa toxicidade.",
    norma: "NR-6 + NR-15", categoria: "LIVRE",
    pontosChave: ["Adequada para varredura, lixamento leve", "Vedação ajustada (sem barba)", "Trocar quando suja ou ao final do turno", "Não substitui PFF2/PFF3 para sílica"],
    reforco: "PFF1 não vale para sílica/cimento — escolha certa salva pulmão." },
  { codigo: "EPI-PFF2", titulo: "Máscara PFF2 (N95)", descricao: "Máscara semifacial tipo PFF2 (N95) para poeiras finas, sílica, biológicos.",
    norma: "NR-6 + NR-15 Anexo 12", categoria: "LIVRE",
    pontosChave: ["Adequada para sílica, cimento, gesso, COVID-19", "Teste de vedação (pressão negativa)", "Trocar a cada turno ou quando úmida", "Sem barba (vedação)"],
    reforco: "PFF2 é mínimo para sílica e biológico — não economize aqui." },
  { codigo: "EPI-PFF3", titulo: "Máscara PFF3", descricao: "Máscara semifacial PFF3 para poeiras altamente tóxicas (chumbo, amianto, sílica intensa).",
    norma: "NR-6 + NR-15", categoria: "LIVRE",
    pontosChave: ["Filtragem 99% de partículas", "Verificação de vedação obrigatória", "Trocar conforme manual ou por umidade", "Combinar com óculos vedados"],
    reforco: "Asbesto e chumbo matam décadas depois — PFF3 não é exagero." },
  { codigo: "EPI-MASC-FACIAL", titulo: "Máscara Facial Inteira c/ Filtro", descricao: "Respirador facial inteiro com filtros químicos — tintas, solventes, vapores orgânicos.",
    norma: "NR-6 + NR-15 Anexo 11", categoria: "LIVRE",
    pontosChave: ["Filtro adequado (orgânico, ácido, amônia)", "Validade do filtro (data)", "Higienização interna semanal", "Treinamento de uso e manutenção"],
    reforco: "Filtro vencido = sem proteção. Confira data antes de cada uso." },
  { codigo: "EPI-LUVA-VAQUETA", titulo: "Luva de Vaqueta (Couro)", descricao: "Luva de couro vaqueta para serviços gerais, transporte de materiais, abrasão.",
    norma: "NR-6", categoria: "LIVRE",
    pontosChave: ["Não usar em equipamento rotativo (enroscamento)", "Trocar quando ressecada/rasgada", "Não molhar (encolhe e endurece)", "CA válido"],
    reforco: "Vaqueta protege de abrasão, NÃO de corte. Anticorte é outra história." },
  { codigo: "EPI-LUVA-NITRIL", titulo: "Luva Nitrílica (Química)", descricao: "Luva nitrílica para manuseio de óleos, solventes, produtos químicos.",
    norma: "NR-6 + NR-15", categoria: "LIVRE",
    pontosChave: ["Verificar compatibilidade química (FISPQ)", "Não furar/rasgar (re-exposição)", "Higienizar entre usos", "Espessura adequada ao produto"],
    reforco: "Nitrílica fina rasga em prego — combine com vaqueta sobreposta." },
  { codigo: "EPI-LUVA-ANTICORTE", titulo: "Luva Anticorte (Nível 5)", descricao: "Luva anticorte de fios sintéticos para manuseio de chapas, vidros, ferramentas cortantes.",
    norma: "NR-6 + EN 388", categoria: "LIVRE",
    pontosChave: ["Nível EN 388 adequado (5 = máxima)", "Trocar quando rasgada (perde proteção)", "Não usar em fonte de calor (queima fios)", "Higienização suave"],
    reforco: "Anticorte nível 5 = vidro, chapa, lâmina. Comum não serve." },
  { codigo: "EPI-CINTO-PARAQUEDISTA", titulo: "Cinto Tipo Paraquedista", descricao: "Cinto de segurança tipo paraquedista para trabalho em altura > 2m.",
    norma: "NR-35 + NR-6", categoria: "LIVRE",
    pontosChave: ["Inspeção visual ANTES de cada uso", "Ajuste correto (4 dedos no peito)", "Anel D dorsal para queda", "Trocar após 1 queda (mesmo se aparenta ok)"],
    reforco: "Cinto não inspecionado = corda velha. Toque, puxe, olhe TODA fivela." },
  { codigo: "EPI-TALABARTE-Y", titulo: "Talabarte em Y (Duplo)", descricao: "Talabarte duplo (Y) para trabalho em altura com deslocamento — sempre 1 ponto ancorado.",
    norma: "NR-35", categoria: "LIVRE",
    pontosChave: ["Ancorar UM gancho antes de soltar o outro", "Absorvedor de energia integrado", "Comprimento + altura de queda < pé do operador", "Inspeção mosquetão (trava + corpo)"],
    reforco: "Mover só com 1 ponto solto — outro SEMPRE ancorado." },
  { codigo: "EPI-TRAVA-QUEDAS", titulo: "Trava-Quedas Retrátil", descricao: "Trava-quedas tipo retrátil em linha de vida horizontal/vertical.",
    norma: "NR-35", categoria: "LIVRE",
    pontosChave: ["Compatível com a linha de vida", "Inspeção do mecanismo de trava", "Posição vertical (não inclinada)", "Não usar para sustentação contínua"],
    reforco: "Retrátil é freio de queda, não para descer rapel. Use o equipamento certo." },

  // ───────────────────── Saúde física (LIVRE) ─────────────────────
  { codigo: "SAUDE-HIDRATACAO", titulo: "Hidratação no Trabalho", descricao: "Importância da hidratação contínua — risco de desidratação, cãibras, insolação.",
    norma: "NR-21 + NR-24", categoria: "LIVRE",
    pontosChave: ["Mínimo 2L/dia + 500ml/hora em calor", "Água potável fresca disponível", "Sinais de desidratação (urina escura, tontura)", "Eletrolítico em jornada longa em calor"],
    reforco: "Sede é tarde. Beba ANTES de sentir sede." },
  { codigo: "SAUDE-ALIMENTACAO", titulo: "Alimentação Balanceada", descricao: "Hábitos alimentares saudáveis para desempenho e prevenção de doenças.",
    norma: "OMS + Guia Alimentar População Brasileira", categoria: "LIVRE",
    pontosChave: ["Café da manhã reforçado", "Reduzir ultraprocessados", "Frutas e verduras diárias", "Não pular refeições (hipoglicemia + acidente)"],
    reforco: "Estômago vazio = atenção zero = acidente. Almoce sempre." },
  { codigo: "SAUDE-SONO", titulo: "Qualidade do Sono", descricao: "Importância do sono reparador para segurança operacional — fadiga e acidentes.",
    norma: "OMS + NR-7 (PCMSO)", categoria: "LIVRE",
    pontosChave: ["7-9 horas/noite para adulto", "Evitar tela 1h antes de dormir", "Quarto escuro e silencioso", "Sonolência diurna = avise líder"],
    reforco: "Trabalhar com sono = dirigir bêbado. Avise se não dormiu." },
  { codigo: "SAUDE-TABAGISMO", titulo: "Tabagismo (Cigarro e Vaper)", descricao: "Riscos do tabagismo (incluindo eletrônicos) — câncer, pulmão, coração, segurança em obra.",
    norma: "Lei 9.294/96 + Lei 12.546/2011", categoria: "LIVRE",
    pontosChave: ["Proibido fumar em locais fechados", "Risco de incêndio próximo a inflamáveis", "Cigarro eletrônico = nicotina + químicos", "Programa de cessação (SUS gratuito)"],
    reforco: "Cigarro mata 1 a cada 6 segundos no mundo. SUS oferece tratamento grátis." },
  { codigo: "SAUDE-ALCOOLISMO", titulo: "Alcoolismo e Trabalho", descricao: "Riscos do consumo abusivo de álcool — acidente, dependência, demissão.",
    norma: "CLT + NR-1", categoria: "LIVRE",
    pontosChave: ["Trabalhar embriagado é justa causa", "Álcool zero ao volante (Lei 11.705)", "Sinais de dependência (tremor matinal, esquecimento)", "Apoio do RH e CAPS-AD"],
    reforco: "Álcool no sangue = reflexo lento + julgamento ruim. Não negocie." },
  { codigo: "SAUDE-DROGAS", titulo: "Drogas Ilícitas", descricao: "Riscos de substâncias ilícitas no ambiente de trabalho — segurança coletiva, demissão.",
    norma: "Lei 11.343/2006 + CLT", categoria: "LIVRE",
    pontosChave: ["Proibido qualquer substância na obra", "Apoio confidencial via RH", "Programa de Assistência ao Empregado (PAE)", "Justa causa por reincidência"],
    reforco: "Sua segurança e a do colega valem mais que qualquer 'baseado'." },
  { codigo: "SAUDE-ALONGAMENTO", titulo: "Alongamento Antes do Trabalho (Ginástica Laboral)", descricao: "Alongamento e ginástica laboral 5-10min antes do início — prevenção LER/DORT.",
    norma: "NR-17 + NR-22", categoria: "LIVRE",
    pontosChave: ["Alongar grandes grupos musculares", "Não doer ao alongar (dor = pare)", "Frequência diária", "Combinar com aquecimento"],
    reforco: "5 minutos de alongamento poupam 5 anos de coluna ruim." },
  { codigo: "SAUDE-POSTURA", titulo: "Postura Correta no Trabalho", descricao: "Postura correta para diferentes atividades — sentado, em pé, agachado, levantando.",
    norma: "NR-17", categoria: "LIVRE",
    pontosChave: ["Levantar com as pernas, não com a coluna", "Carga próxima ao corpo", "Coluna reta, joelho dobrado", "Pausa a cada 50min em postura forçada"],
    reforco: "Coluna não tem peça de reposição — postura correta agora ou cirurgia depois." },
  { codigo: "SAUDE-LER-DORT", titulo: "Prevenção de LER/DORT", descricao: "Lesão por Esforço Repetitivo / Distúrbio Osteomuscular Relacionado ao Trabalho.",
    norma: "NR-17 + INSS", categoria: "LIVRE",
    pontosChave: ["Rodízio de função em movimento repetitivo", "Pausas curtas e frequentes", "Sinais precoces (formigamento, dor noturna)", "AET (Análise Ergonômica) atualizada"],
    reforco: "LER/DORT começa silenciosa — comunique dor LOGO no início." },
  { codigo: "SAUDE-COLUNA", titulo: "Saúde da Coluna Vertebral", descricao: "Cuidados específicos com a coluna — hérnia de disco, lombalgia, escoliose.",
    norma: "NR-17", categoria: "LIVRE",
    pontosChave: ["Levantamento manual máx. 25kg (homem) / 15kg (mulher)", "Carga > 25kg sempre 2 pessoas ou equipamento", "Cinto lombar não substitui técnica", "Exercício de fortalecimento (CORE)"],
    reforco: "Hérnia de disco = aposentadoria precoce. Levante com perna, não coluna." },
  { codigo: "SAUDE-HIPERTENSAO", titulo: "Hipertensão Arterial", descricao: "Pressão alta — silenciosa, mata. Importância do controle e medicação contínua.",
    norma: "Política Nacional de Saúde (SUS)", categoria: "LIVRE",
    pontosChave: ["Aferir pressão periodicamente (PCMSO)", "Medicação contínua (não parar sem médico)", "Reduzir sal, açúcar, álcool", "Atividade física 30min/dia"],
    reforco: "Pressão alta não dói — só mata. Aferição trimestral mínimo." },
  { codigo: "SAUDE-DIABETES", titulo: "Diabetes Mellitus", descricao: "Diabetes tipo 1 e 2 — controle glicêmico, sintomas, complicações.",
    norma: "Política Nacional de Saúde (SUS)", categoria: "LIVRE",
    pontosChave: ["Hipoglicemia em obra = acidente grave", "Lanche regular para diabético", "Medição glicêmica regular", "Comunicar líder se diabético (preparar lanche extra)"],
    reforco: "Diabético sem comer há 4h = perigo iminente. Preventivo, sempre." },
  { codigo: "SAUDE-COLESTEROL", titulo: "Colesterol e Triglicérides", descricao: "Controle de colesterol e triglicérides — prevenção de infarto e AVC.",
    norma: "OMS", categoria: "LIVRE",
    pontosChave: ["Exame de sangue anual (PCMSO)", "Reduzir frituras, embutidos, açúcar", "Atividade física aeróbica", "Medicação se prescrita"],
    reforco: "Infarto avisa pouco — controle de exames é prevenção real." },
  { codigo: "SAUDE-ALERGIA", titulo: "Alergias Respiratórias", descricao: "Rinite, asma, sinusite no ambiente de obra — pó, mofo, ácaro.",
    norma: "NR-15", categoria: "LIVRE",
    pontosChave: ["Comunicar alergia ao SESMT", "Máscara PFF2 mesmo em pó leve", "Evitar varredura a seco (umectar)", "Inalador (bombinha) se prescrito"],
    reforco: "Crise de asma em obra = emergência. SESMT precisa saber." },
  { codigo: "SAUDE-HIGIENE-PESSOAL", titulo: "Higiene Pessoal", descricao: "Higiene básica diária — banho, mãos, alimentação, EPI compartilhado.",
    norma: "NR-24", categoria: "LIVRE",
    pontosChave: ["Lavar mãos antes de comer (cimento, químico)", "Banho ao final do turno", "Não compartilhar capacete/protetor sem higienização", "Roupa de trabalho separada da pessoal"],
    reforco: "Cimento na mão + comida = irritação intestinal. Lave SEMPRE." },

  // ───────────────────── Saúde mental (LIVRE) ─────────────────────
  { codigo: "MENTAL-SAUDE-GERAL", titulo: "Saúde Mental no Trabalho", descricao: "Importância da saúde mental — produtividade, segurança, vida.",
    norma: "Lei 14.556/2023 + NR-1", categoria: "LIVRE",
    pontosChave: ["Saúde mental é tema legítimo no DDS", "Sintomas físicos podem ser psicológicos", "CAPS gratuito no SUS", "PAE (Programa Assistência Empregado) confidencial"],
    reforco: "Sua mente é tão importante quanto seu braço. Cuide igual." },
  { codigo: "MENTAL-ANSIEDADE", titulo: "Ansiedade", descricao: "Transtornos de ansiedade — sintomas, manejo, quando buscar ajuda.",
    norma: "OMS + Lei 14.556/2023", categoria: "LIVRE",
    pontosChave: ["Sinais (taquicardia, insônia, irritação)", "Técnica de respiração 4-7-8", "Reduzir cafeína", "CAPS é gratuito e sigiloso"],
    reforco: "Ansiedade não é frescura — é doença com tratamento. Procure ajuda." },
  { codigo: "MENTAL-DEPRESSAO", titulo: "Depressão", descricao: "Reconhecer sinais de depressão em si e no colega — apoio e encaminhamento.",
    norma: "OMS + Lei 14.556/2023", categoria: "LIVRE",
    pontosChave: ["Sintomas (tristeza > 2 semanas, sem energia, isolamento)", "Não é 'preguiça' nem 'frescura'", "CAPS, médico família ou psiquiatra", "Apoio do colega: escutar sem julgar"],
    reforco: "Depressão tem tratamento. Procure ajuda — não enfrente sozinho." },
  { codigo: "MENTAL-ESTRESSE", titulo: "Estresse Ocupacional", descricao: "Estresse no trabalho — causas, sintomas, manejo individual e organizacional.",
    norma: "NR-17 + NR-1", categoria: "LIVRE",
    pontosChave: ["Carga de trabalho realista", "Pausas e desligamento fora do expediente", "Sinais físicos (gastrite, dor de cabeça, insônia)", "Comunicar líder sobre sobrecarga"],
    reforco: "Estresse crônico mata — é igual hipertensão silenciosa." },
  { codigo: "MENTAL-BURNOUT", titulo: "Síndrome de Burnout", descricao: "Esgotamento profissional — reconhecimento, prevenção, tratamento (CID-11 oficial).",
    norma: "OMS CID-11 + NR-1", categoria: "LIVRE",
    pontosChave: ["3 sinais: exaustão, cinismo, ineficácia", "Direito a afastamento (B91 INSS)", "Não confundir com depressão", "Causa é organizacional, tratamento é multifatorial"],
    reforco: "Burnout é doença ocupacional reconhecida. Não se culpe — busque ajuda." },
  { codigo: "MENTAL-SUICIDIO", titulo: "Prevenção ao Suicídio (Setembro Amarelo)", descricao: "Reconhecer sinais de risco suicida em si e no colega — abordagem segura.",
    norma: "Lei 13.819/2019", categoria: "LIVRE",
    pontosChave: ["Sinais de alerta (despedidas, isolamento, doação de pertences)", "CVV 188 (24h gratuito)", "Falar sobre não 'plantar a ideia'", "CAPS é porta de entrada"],
    reforco: "Perguntar não induz. Calar pode matar. CVV 188." },
  { codigo: "MENTAL-ASSEDIO-MORAL", titulo: "Assédio Moral no Trabalho", descricao: "O que é, como identificar, como denunciar assédio moral — repetitivo, hierárquico ou horizontal.",
    norma: "Lei 14.612/2023 + CLT", categoria: "LIVRE",
    pontosChave: ["Definição: humilhação repetida e prolongada", "Não confundir com cobrança legítima", "Canais (RH, sindicato, MPT)", "Documentar tudo (data, hora, testemunhas)"],
    reforco: "Cobrança severa ≠ assédio. Mas humilhação repetida É crime." },
  { codigo: "MENTAL-ASSEDIO-SEXUAL", titulo: "Assédio Sexual", descricao: "Definição, exemplos, denúncia e zero tolerância para assédio sexual.",
    norma: "Lei 10.224/2001 + Lei 14.457/2022", categoria: "LIVRE",
    pontosChave: ["Definição: constrangimento por superior hierárquico", "Não precisa ser físico (verbal/visual conta)", "Canal de denúncia obrigatório (Lei 14.457)", "Testemunha tem dever de comunicar"],
    reforco: "Zero tolerância. Denúncia é direito — sigilo é garantido." },
  { codigo: "MENTAL-RACISMO", titulo: "Combate ao Racismo no Trabalho", descricao: "Racismo estrutural, racismo recreativo, igualdade racial — Lei Caó.",
    norma: "Lei 7.716/89 + Lei 14.532/2023", categoria: "LIVRE",
    pontosChave: ["Racismo é CRIME (não comparável a injúria)", "‘Brincadeira’ racista também é racismo", "Denúncia: Disque 100, Polícia, MPT", "Política antirracista da empresa"],
    reforco: "Racismo é crime imprescritível. Tolerância zero, sempre." },
  { codigo: "MENTAL-LGBTQIA", titulo: "Diversidade e Inclusão LGBTQIA+", descricao: "Respeito à diversidade sexual e de gênero no ambiente de trabalho.",
    norma: "STF ADO 26/2019 + CLT", categoria: "LIVRE",
    pontosChave: ["Homofobia/transfobia = racismo (STF)", "Banheiro conforme identidade de gênero", "Nome social no crachá", "Política de combate à discriminação"],
    reforco: "Respeito é direito. Discriminação por orientação ou gênero é crime." },
  { codigo: "MENTAL-DIVERSIDADE", titulo: "Diversidade e Inclusão Geral", descricao: "Inclusão de pessoas com deficiência, LGBTQIA+, raças, idades, religiões.",
    norma: "Lei 8.213/91 (cota PCD) + CF", categoria: "LIVRE",
    pontosChave: ["Cota legal PCD (2-5% conforme porte)", "Acessibilidade física e atitudinal", "Treinamento de lideranças", "Indicadores de diversidade no RH"],
    reforco: "Diversidade não é favor — é direito e estratégia." },
  { codigo: "MENTAL-GRAVIDEZ", titulo: "Gravidez no Ambiente de Obra", descricao: "Direitos da gestante, restrições de exposição, mudança de função.",
    norma: "CLT + NR-7 + NR-15", categoria: "LIVRE",
    pontosChave: ["Comunicar gravidez ao SESMT/RH", "Estabilidade gestacional (5 meses pós-parto)", "Restrições (peso, altura, químicos, calor)", "Licença gestante 120 dias (180 se empresa cidadã)"],
    reforco: "Gestante na obra tem direito a função compatível. Comunique cedo." },
  { codigo: "MENTAL-PATERNIDADE", titulo: "Paternidade Ativa", descricao: "Licença paternidade, presença na criação, equilíbrio trabalho-família.",
    norma: "CLT + Lei 13.257/2016 (Marco da Primeira Infância)", categoria: "LIVRE",
    pontosChave: ["5 dias (geral) + 15 (empresa cidadã)", "Acompanhar pré-natal (direito de ausência)", "Consulta pediátrica até 6 anos (1/ano)", "Vínculo afetivo previne acidente doméstico"],
    reforco: "Pai presente forma criança segura. Use seu direito." },
  { codigo: "MENTAL-RETORNO-ACID", titulo: "Retorno ao Trabalho Após Acidente", descricao: "Reabilitação, readaptação e apoio psicológico no retorno após acidente de trabalho.",
    norma: "Lei 8.213/91 + NR-1", categoria: "LIVRE",
    pontosChave: ["Reabilitação profissional pelo INSS", "Estabilidade 12 meses pós-alta B91", "Função compatível com sequela", "Apoio psicológico (TEPT é comum)"],
    reforco: "Voltar ao trabalho é parte da cura. Receba o colega bem." },
  { codigo: "MENTAL-CNV", titulo: "Comunicação Não-Violenta (CNV)", descricao: "Princípios de CNV de Marshall Rosenberg para reduzir conflito no canteiro.",
    norma: "Boa prática gerencial", categoria: "LIVRE",
    pontosChave: ["4 passos: observação, sentimento, necessidade, pedido", "Falar de SI, não acusar o outro", "Escuta ativa (sem interromper)", "Linguagem que une, não que rotula"],
    reforco: "Conflito mal-resolvido vira acidente. Comunique sem agredir." },

  // ───────────────────── Riscos específicos (LIVRE) ─────────────────────
  { codigo: "RISCO-RUIDO-CONTINUO", titulo: "Ruído Contínuo", descricao: "Exposição a ruído contínuo (motor, máquina, betoneira) — limites e perda auditiva induzida.",
    norma: "NR-15 Anexo 1", categoria: "LIVRE",
    pontosChave: ["LT = 85 dB(A) para 8h", "Cada +3 dB reduz tempo pela metade", "PAIR (Perda Auditiva Induzida pelo Ruído) é insidiosa", "Audiometria periódica obrigatória (PCMSO)"],
    reforco: "Surdez por ruído não tem retorno. Plug + concha em > 85 dB." },
  { codigo: "RISCO-RUIDO-IMPACTO", titulo: "Ruído de Impacto", descricao: "Ruído de impacto (martelete, prensa, marreta) — limite de pico e proteção.",
    norma: "NR-15 Anexo 2", categoria: "LIVRE",
    pontosChave: ["Limite 130 dB (linear) ou 120 dB(C)", "Conjunto plug + concha obrigatório > 110 dB", "Distância da fonte reduz 6 dB por dobra de distância", "Pausa de exposição"],
    reforco: "Ruído de impacto rompe tímpano em 1 evento. Dupla proteção sempre." },
  { codigo: "RISCO-CALOR", titulo: "Exposição ao Calor", descricao: "Estresse térmico em frente de obra ao sol — IBUTG, hidratação, pausas.",
    norma: "NR-15 Anexo 3", categoria: "LIVRE",
    pontosChave: ["Medição do IBUTG (não confunda com termômetro)", "Pausa térmica conforme tabela NR-15", "Hidratação 500ml/hora + eletrolítico", "Aclimatização (2 semanas para novo)"],
    reforco: "Insolação mata em 1 hora — pausa em sombra é regra, não favor." },
  { codigo: "RISCO-FRIO", titulo: "Exposição ao Frio", descricao: "Trabalho em câmara fria, em alta altitude ou no inverno — hipotermia, ulceração.",
    norma: "NR-29 + NR-36", categoria: "LIVRE",
    pontosChave: ["Roupa térmica em camadas", "Pausa térmica em local aquecido", "Hidratação contínua (esquece-se no frio)", "Sinais de hipotermia (tremor, lentidão, confusão)"],
    reforco: "Frio engana — você não sente, mas a temperatura corporal cai." },
  { codigo: "RISCO-UMIDADE", titulo: "Umidade Excessiva", descricao: "Trabalho em ambiente úmido (porão, escavação, chuva) — dermatite, leptospirose, pneumonia.",
    norma: "NR-15 Anexo 10", categoria: "LIVRE",
    pontosChave: ["Bota PVC + luva impermeável", "Troca de roupa molhada IMEDIATA", "Cuidado com leptospirose (urina rato)", "Insalubridade 20% se caracterizado"],
    reforco: "Roupa molhada o dia inteiro = pneumonia + dermatite. Troque." },
  { codigo: "RISCO-VIB-MAO-BRACO", titulo: "Vibração Mão-Braço", descricao: "Vibração em ferramentas (martelete, esmerilhadeira, vibrador) — síndrome mão-braço.",
    norma: "NR-15 Anexo 8", categoria: "LIVRE",
    pontosChave: ["Limite de 5 m/s² (ação) e 2,5 m/s² (exposição)", "Luva antivibração", "Pausa 10min a cada 50min", "Sinais (formigamento, palidez dedos)"],
    reforco: "Síndrome mão-braço é IRREVERSÍVEL. Pausa salva movimento." },
  { codigo: "RISCO-VIB-CORPO-INT", titulo: "Vibração de Corpo Inteiro", descricao: "Vibração em operação de máquinas (rolo, escavadeira, caminhão) — coluna, órgãos.",
    norma: "NR-15 Anexo 8", categoria: "LIVRE",
    pontosChave: ["Banco com sistema de amortecimento", "Cinto + postura correta", "Manutenção preventiva da máquina", "Limite 1,1 m/s² (8h)"],
    reforco: "Vibração crônica = hérnia de disco. Banco amortecedor é obrigatório." },
  { codigo: "RISCO-RAD-UV", titulo: "Radiação UV (Sol)", descricao: "Exposição prolongada ao sol — câncer de pele, catarata, queimadura.",
    norma: "NR-21 + INCA", categoria: "LIVRE",
    pontosChave: ["Protetor solar FPS 30+ a cada 2h", "Camisa manga longa UPF (UV)", "Boné com aba ou capacete com aba", "Óculos com proteção UV"],
    reforco: "Câncer de pele é o mais comum — protetor solar é EPI." },
  { codigo: "RISCO-SILICA", titulo: "Sílica Cristalina", descricao: "Pó de sílica em corte de cerâmica, mármore, concreto — silicose, câncer pulmão.",
    norma: "NR-15 Anexo 12", categoria: "LIVRE",
    pontosChave: ["Corte úmido SEMPRE (água abate sílica)", "Máscara PFF2 ou PFF3", "Aspiração local em equipamento", "Audimetria + Rx tórax periódico"],
    reforco: "Silicose mata 1.000+ por ano no Brasil — sem cura. Água + máscara." },
  { codigo: "RISCO-PO-CIMENTO", titulo: "Pó de Cimento e Cal", descricao: "Pó de cimento e cal — irritação respiratória, dermatite, queimadura química.",
    norma: "NR-15", categoria: "LIVRE",
    pontosChave: ["Máscara PFF2", "Luva nitrílica + manga longa", "Lavar pele exposta IMEDIATAMENTE", "Hidratante após o turno"],
    reforco: "Cimento pH 12 = queima a pele. Lave assim que respingar." },
  { codigo: "RISCO-FUMO-METAL", titulo: "Fumos Metálicos (Solda)", descricao: "Fumos de soldagem (chumbo, manganês, cromo, ferro) — febre dos fumos, neurológico.",
    norma: "NR-15 Anexo 11", categoria: "LIVRE",
    pontosChave: ["Exaustão local na frente de solda", "Máscara PFF2 ou facial inteira c/ filtro", "Não soldar galvanizado sem proteção dobrada", "Exame periódico de chumbo no sangue"],
    reforco: "Fumo de solda galvanizada = febre + intoxicação. Exaustão SEMPRE." },
  { codigo: "RISCO-SOLVENTES", titulo: "Solventes Orgânicos", descricao: "Solventes (tinta, cola, removedor) — hepatotoxicidade, neurológico, irritação.",
    norma: "NR-15 Anexo 11", categoria: "LIVRE",
    pontosChave: ["Ventilação cruzada obrigatória", "Máscara facial c/ filtro orgânico", "Não comer/beber/fumar próximo", "Trocar roupa contaminada"],
    reforco: "Solvente entra pelo pulmão E pela pele. Proteja os dois." },
  { codigo: "RISCO-ACIDOS", titulo: "Ácidos e Álcalis (Químicos Fortes)", descricao: "Manuseio de ácidos (muriático, sulfúrico) e álcalis (soda) — queimadura química.",
    norma: "NR-15 + FISPQ", categoria: "LIVRE",
    pontosChave: ["Ler FISPQ antes de manusear", "EPI químico completo (luva, óculos, avental)", "Lavar com muita água em respingo", "Chuveiro de emergência próximo"],
    reforco: "Ácido na pele = lave 15min sem parar. Chuveiro é vida." },
  { codigo: "RISCO-BIO-ESGOTO", titulo: "Risco Biológico em Esgoto", descricao: "Exposição a esgoto e fossa — hepatite A, leptospirose, tétano, parasitas.",
    norma: "NR-15 Anexo 14", categoria: "LIVRE",
    pontosChave: ["Vacina Hep. A + B + dT em dia", "Bota PVC + luva nitrílica + macacão", "Não levar mão à boca", "Banho ao final do turno"],
    reforco: "Esgoto não é só sujeira — é doença concentrada. Vacina + EPI." },
  { codigo: "RISCO-DENGUE", titulo: "Dengue, Zika, Chikungunya, Febre Amarela", descricao: "Doenças transmitidas pelo Aedes aegypti — prevenção em canteiro.",
    norma: "MS + NR-31", categoria: "LIVRE",
    pontosChave: ["Eliminar água parada no canteiro (semanal)", "Repelente DEET 30%", "Calça e camisa manga longa", "Vacina febre amarela em área endêmica"],
    reforco: "Larva nasce em 7 dias — mutirão semanal salva vidas." },

  // ───────────────────── Emergência (LIVRE) ─────────────────────
  { codigo: "EMERG-PLANO", titulo: "Plano de Emergência da Obra", descricao: "Plano de emergência (incêndio, evacuação, primeiros socorros) — quem faz o quê.",
    norma: "NR-23 + NR-18", categoria: "LIVRE",
    pontosChave: ["Plano afixado em local visível", "Líder de evacuação por setor", "Ponto de encontro definido", "Simulado semestral"],
    reforco: "Em emergência não há tempo de pensar — só de executar o ensaiado." },
  { codigo: "EMERG-ABANDONO", titulo: "Procedimento de Abandono de Área", descricao: "Como abandonar a obra em emergência (incêndio, vazamento, terremoto, ameaça).",
    norma: "NR-23 + IT Bombeiros", categoria: "LIVRE",
    pontosChave: ["Sinal de abandono (sirene/sino contínuo)", "Rota de fuga sinalizada e desobstruída", "Não usar elevador", "Reunião no ponto de encontro + chamada"],
    reforco: "Saída desobstruída salva — nunca empilhe material em rota de fuga." },
  { codigo: "EMERG-PONTO-ENCONTRO", titulo: "Ponto de Encontro em Emergência", descricao: "Localização, sinalização e procedimento no ponto de encontro pós-evacuação.",
    norma: "NR-23 + IT Bombeiros", categoria: "LIVRE",
    pontosChave: ["Local seguro, fora da projeção da edificação", "Sinalização visível", "Chamada nominal por setor", "Espera autorização para retorno"],
    reforco: "Retorno antes da liberação = morte por desabamento secundário." },
  { codigo: "EMERG-BRIGADA", titulo: "Brigada de Incêndio", descricao: "Composição, treinamento e atuação da brigada de incêndio na obra.",
    norma: "NR-23 + NBR 14276", categoria: "LIVRE",
    pontosChave: ["% mínimo conforme NBR 14276", "Curso de 16h-40h conforme nível", "Inspeção mensal de extintores e hidrantes", "Treinamento prático anual"],
    reforco: "Brigadista forma 1ª linha de defesa — equipe consciente salva." },
  { codigo: "EMERG-RCP", titulo: "Reanimação Cardiopulmonar (RCP)", descricao: "Massagem cardíaca e ventilação em parada cardiorrespiratória.",
    norma: "AHA + Diretrizes SBC", categoria: "LIVRE",
    pontosChave: ["100-120 compressões/min (ritmo Stayin' Alive)", "Profundidade 5-6cm", "Não interromper > 10s", "DEA assim que disponível"],
    reforco: "RCP nos primeiros 4min triplica chance de sobrevida. Aprenda." },
  { codigo: "EMERG-HEMORRAGIA", titulo: "Controle de Hemorragia", descricao: "Pressão direta, elevação, torniquete em última instância — controle de sangramento.",
    norma: "Cartilha Primeiros Socorros - SAMU", categoria: "LIVRE",
    pontosChave: ["Pressão DIRETA com pano limpo", "Elevação do membro acima do coração", "Torniquete só se pressão não funcionar", "Acionar 192 (SAMU) imediato"],
    reforco: "Sangramento arterial mata em 5min — pressão direta primeiro." },
  { codigo: "EMERG-QUEIMADURA", titulo: "Queimaduras", descricao: "Primeiros socorros em queimaduras térmicas, químicas e elétricas.",
    norma: "Cartilha SAMU + AHA", categoria: "LIVRE",
    pontosChave: ["Água corrente fria 10-20min", "Não passar pasta de dente, manteiga, etc.", "Não furar bolha", "Cobrir com pano limpo + acionar 192"],
    reforco: "Água fria nos primeiros 3min reduz gravidade em 50%." },
  { codigo: "EMERG-FRATURAS", titulo: "Suspeita de Fratura", descricao: "Imobilização de fraturas e luxações até atendimento médico.",
    norma: "Cartilha SAMU", categoria: "LIVRE",
    pontosChave: ["NÃO movimentar a vítima sem necessidade", "Imobilizar como está (não tente realinhar)", "Tala improvisada (pranchinha, papelão)", "Acionar 192 e aguardar"],
    reforco: "Fratura mal manipulada vira lesão de medula. Imobilize como está." },
  { codigo: "EMERG-INTOXICACAO", titulo: "Intoxicação Química", descricao: "Conduta em intoxicação por inalação, ingestão ou contato cutâneo com químicos.",
    norma: "FISPQ + CIATox", categoria: "LIVRE",
    pontosChave: ["Retirar do ambiente contaminado", "NÃO induzir vômito sem orientação", "Lavar pele/olhos com muita água", "Acionar 0800-7223110 (CIATox) + 192"],
    reforco: "FISPQ na mão + CIATox no telefone = decisão certa em 30s." },
  { codigo: "EMERG-CHOQUE-ELET", titulo: "Choque Elétrico — Primeiros Socorros", descricao: "Conduta em vítima de choque elétrico — desligar fonte, RCP, transporte.",
    norma: "NR-10 + AHA", categoria: "LIVRE",
    pontosChave: ["DESLIGAR a chave geral PRIMEIRO (nunca tocar a vítima energizada)", "Afastar com material isolante (madeira seca)", "Verificar pulso e respiração — RCP se necessário", "Acionar 192"],
    reforco: "Tocar vítima energizada = duas vítimas. Desligue a chave PRIMEIRO." },

  // ───────────────────── Trânsito (LIVRE) ─────────────────────
  { codigo: "TRAN-DEFENSIVA", titulo: "Direção Defensiva", descricao: "Princípios da direção defensiva — antecipação, distância, atenção.",
    norma: "CTB + Resolução CONTRAN", categoria: "LIVRE",
    pontosChave: ["Distância de seguimento (regra 2 segundos)", "Espelhamento a cada 5-8 segundos", "Antecipar erro do outro", "Adaptar à condição (chuva, neblina, noite)"],
    reforco: "Defensiva é assumir que o outro vai errar. E você vai estar pronto." },
  { codigo: "TRAN-ALCOOL-ZERO", titulo: "Álcool Zero ao Volante", descricao: "Lei seca — qualquer concentração é infração + penalidade.",
    norma: "Lei 11.705/2008 + CTB", categoria: "LIVRE",
    pontosChave: ["0,05 mg/L já é multa + suspensão", "Crime de trânsito com pena de prisão", "Se vai beber, não dirija — chamar Uber/táxi", "Empresa pode ser corresponsável"],
    reforco: "1 cerveja já dá multa. Bebeu? Não pega o volante." },
  { codigo: "TRAN-CELULAR", titulo: "Celular ao Volante", descricao: "Uso do celular ao volante — risco, multa, distração equiparada à embriaguez.",
    norma: "CTB art. 252", categoria: "LIVRE",
    pontosChave: ["Multa GRAVÍSSIMA (R$ 293+) + 7 pontos", "Atenção desviada por 5s = 100m no escuro", "Bluetooth/viva-voz só para chamadas curtas", "WhatsApp parado SEMPRE"],
    reforco: "Celular ao volante mata mais que álcool hoje. Pare ou aguarde." },
  { codigo: "TRAN-CINTO", titulo: "Cinto de Segurança e CRLV", descricao: "Cinto obrigatório, documentação do veículo (CRLV digital), inspeção.",
    norma: "CTB art. 167 + 230", categoria: "LIVRE",
    pontosChave: ["Cinto em TODOS os bancos", "Cinto reduz mortalidade em 40-60%", "CRLV digital aceito (app CDT)", "Inspeção periódica (AVCB, IPVA, seguro)"],
    reforco: "Cinto poupa 5 segundos de incômodo e dá 50 anos de vida." },
  { codigo: "TRAN-CARGA", titulo: "Transporte de Carga em Caçamba", descricao: "Amarração e cobertura de carga em caminhão/caçamba — projeção, queda.",
    norma: "CTB art. 235 + Resolução CONTRAN", categoria: "LIVRE",
    pontosChave: ["Carga amarrada com cintas adequadas", "Cobertura com lona em entulho", "Não exceder altura/peso máximo", "Sinalização noturna (refletivos)"],
    reforco: "Pedra solta da caçamba = morte de motorista atrás. Lona + amarra." },

  // ───────────────────── Documentação e processos (LIVRE) ─────────────────────
  { codigo: "DOC-CAT", titulo: "CAT — Comunicação de Acidente de Trabalho", descricao: "Quando, como e quem emite a CAT — direito do trabalhador, obrigação da empresa.",
    norma: "Lei 8.213/91 + Decreto 3.048/99", categoria: "LIVRE",
    pontosChave: ["Emitir até 1° dia útil após o acidente", "Mesmo sem afastamento — obrigatório", "Acidente típico, doença ocupacional, trajeto", "INSS: B91 (auxílio acidentário)"],
    reforco: "CAT é direito seu — empresa é obrigada a emitir, mesmo sem afastamento." },
  { codigo: "DOC-ASO", titulo: "ASO — Atestado de Saúde Ocupacional", descricao: "Atestado obrigatório para admissão, periódico, retorno, mudança de função, demissão.",
    norma: "NR-7", categoria: "LIVRE",
    pontosChave: ["Validade 1 ano (insalubre) ou 2 anos (demais)", "Emitido por médico do trabalho", "Trabalhador recebe via", "Sem ASO válido = não pode trabalhar"],
    reforco: "ASO vencido = afastamento administrativo. Verifique antes do periódico." },
  { codigo: "DOC-PCMSO", titulo: "PCMSO — Programa de Controle Médico", descricao: "Programa de Controle Médico de Saúde Ocupacional — exames complementares por risco.",
    norma: "NR-7", categoria: "LIVRE",
    pontosChave: ["Documento técnico anual", "Exames específicos por agente (ruído→audiometria)", "Trabalhador tem direito ao laudo", "Coordenado por médico do trabalho"],
    reforco: "PCMSO sob medida = menos doença ocupacional. Cobre seu exame." },
  { codigo: "DOC-PGR", titulo: "PGR — Programa de Gerenciamento de Riscos", descricao: "Inventário de riscos e plano de ação — substituiu o antigo PPRA em 2022.",
    norma: "NR-1 + NR-9", categoria: "LIVRE",
    pontosChave: ["Inventário de riscos por função/setor", "Plano de ação com prazo e responsável", "Revisão a cada 2 anos ou após mudança", "Trabalhador tem direito de consulta"],
    reforco: "PGR é a 'CNH' da empresa em SST — exija acesso ao inventário." },
  { codigo: "DOC-PCMAT", titulo: "PCMAT — Programa Condições Meio Ambiente Trabalho", descricao: "PCMAT específico para construção civil > 20 trabalhadores — projeto SST do canteiro.",
    norma: "NR-18", categoria: "LIVRE",
    pontosChave: ["Obrigatório > 20 trabalhadores", "Inclui layout, fluxograma, EPC", "Elaborado por engenheiro de segurança", "Atualização conforme evolução da obra"],
    reforco: "Sem PCMAT, obra > 20 funcionários é irregular. Cobre do RT." },
  { codigo: "DOC-AET", titulo: "AET — Análise Ergonômica do Trabalho", descricao: "Estudo ergonômico das funções — postura, peso, repetição, ambiente.",
    norma: "NR-17", categoria: "LIVRE",
    pontosChave: ["Levantamento de queixas e LER/DORT", "Mensuração de carga e posto", "Plano de melhorias com prazo", "Revisão após mudança de processo"],
    reforco: "AET é o 'raio-X ergonômico' do seu posto — exija revisão." },
  { codigo: "DOC-APR", titulo: "APR — Análise Preliminar de Risco", descricao: "Análise tarefa-a-tarefa antes de iniciar serviço crítico — quem faz, quem aprova.",
    norma: "NR-1 + práticas internas", categoria: "LIVRE",
    pontosChave: ["Listar passos da tarefa", "Identificar perigos e riscos por passo", "Definir medidas de controle", "Assinatura da equipe + supervisor"],
    reforco: "APR não é papel — é segundos para pensar antes de morrer." },
  { codigo: "DOC-PT", titulo: "PT — Permissão de Trabalho", descricao: "Permissão de Trabalho para serviços de alto risco (altura, confinado, quente, eletricidade).",
    norma: "NR-33 + NR-35 + práticas internas", categoria: "LIVRE",
    pontosChave: ["Validade restrita (1 turno/24h)", "Assinaturas (executor, emitente, supervisor)", "Lock-out/Tag-out (LOTO) onde aplicável", "Encerramento documentado"],
    reforco: "PT vencida = serviço suspenso. Não improvise." },
  { codigo: "DOC-OS", titulo: "OS — Ordem de Serviço (NR-1)", descricao: "Ordem de Serviço da NR-1 — instrução por escrito sobre risco, EPI, procedimento.",
    norma: "NR-1 item 1.4.1.b", categoria: "LIVRE",
    pontosChave: ["Por função e por atividade", "Trabalhador deve assinar (recebido e ciente)", "Riscos e medidas de controle descritos", "Atualização em mudança de função"],
    reforco: "OS não assinada = sem orientação formal. Cobre do RH." },
  { codigo: "DOC-IT-FISPQ", titulo: "IT e FISPQ — Instrução e Ficha Química", descricao: "Instrução de Trabalho (IT) e Ficha de Informação de Segurança de Produto Químico (FISPQ).",
    norma: "NR-1 + ABNT NBR 14725", categoria: "LIVRE",
    pontosChave: ["FISPQ obrigatória para todo químico", "Disponível em local visível na bancada", "16 seções padronizadas (NBR)", "Treinamento de leitura"],
    reforco: "FISPQ é o 'manual de sobrevivência' do químico. Saiba ler." },

  // ───────────────────── Cultura e organização (LIVRE) ─────────────────────
  { codigo: "CULT-5S", titulo: "Programa 5S", descricao: "Senso de Utilização, Organização, Limpeza, Padronização e Disciplina.",
    norma: "Boas práticas (origem Japão)", categoria: "LIVRE",
    pontosChave: ["Seiri (descartar o que não usa)", "Seiton (organizar o que usa)", "Seiso (limpar o local)", "Seiketsu + Shitsuke (padronizar e manter)"],
    reforco: "5S não é faxina — é cultura. Reduz acidente em 30%." },
  { codigo: "CULT-ORDEM-LIMPEZA", titulo: "Ordem e Limpeza no Canteiro", descricao: "Importância da ordem e limpeza diária — quedas, tropeços, eficiência.",
    norma: "NR-18 + 5S", categoria: "LIVRE",
    pontosChave: ["Caçambas distribuídas e identificadas", "Final de turno = limpeza da frente", "Materiais empilhados estáveis", "Cabos elétricos suspensos"],
    reforco: "60% das quedas em canteiro são por desorganização. 15min/dia salvam." },
  { codigo: "CULT-SINALIZACAO", titulo: "Sinalização de Segurança no Canteiro", descricao: "Cores, símbolos, placas e fitas — sinalização eficaz de risco.",
    norma: "NR-26 + NR-18", categoria: "LIVRE",
    pontosChave: ["Vermelho = proibição/incêndio; Amarelo = atenção; Verde = segurança; Azul = obrigação", "Pictogramas universais (ISO 7010)", "Placas em posição visível", "Renovação se desbotada"],
    reforco: "Sinalização ruim = acidente cantado. Renove placas desbotadas." },
  { codigo: "CULT-RESIDUOS", titulo: "Segregação de Resíduos (Lixeiras Coloridas)", descricao: "Coleta seletiva no canteiro — papel, plástico, metal, madeira, perigoso.",
    norma: "NR-25 + Resolução CONAMA 307", categoria: "LIVRE",
    pontosChave: ["Azul=papel; Vermelho=plástico; Verde=vidro; Amarelo=metal; Marrom=orgânico; Preto=rejeito", "Resíduo perigoso (Classe I) separado", "PGRCC obrigatório", "Empresa licenciada para destinação"],
    reforco: "Resíduo misturado = multa + degradação. 5 lixeiras é o mínimo." },
  { codigo: "CULT-OLEO-DESCARTE", titulo: "Descarte de Óleo e Combustível", descricao: "Procedimento de descarte de óleo lubrificante, diesel, gasolina (Classe I).",
    norma: "NR-25 + Resolução CONAMA 362", categoria: "LIVRE",
    pontosChave: ["Tambor metálico identificado", "Bacia de contenção para vazamento", "Empresa coletora licenciada", "Manifesto de transporte emitido"],
    reforco: "Óleo no chão = solo morto por 30 anos. Tambor identificado." },
  { codigo: "CULT-GESTAO-VISUAL", titulo: "Gestão Visual da Obra", descricao: "Quadros, KPIs, indicadores expostos — transparência e engajamento.",
    norma: "Boa prática gerencial", categoria: "LIVRE",
    pontosChave: ["KPI exposto em local visível (TF, TG, dias sem acidente)", "Status de não-conformidades", "Reconhecimento público de boas práticas", "Atualização semanal"],
    reforco: "O que é medido e exposto melhora 3x mais rápido." },
  { codigo: "CULT-NEAR-MISS", titulo: "Quase-Acidente (Near Miss)", descricao: "Cultura de reportar quase-acidentes — aprendizado sem vítima.",
    norma: "Pirâmide de Heinrich + NR-1", categoria: "LIVRE",
    pontosChave: ["1 acidente grave = 30 leves = 600 quase-acidentes", "Reporte sem culpabilizar", "Análise de causa raiz", "Plano de ação imediato"],
    reforco: "Quase-acidente é aviso GRÁTIS. Reporte hoje, evite morte amanhã." },
  { codigo: "CULT-OBSERVACAO", titulo: "Observação Comportamental de Segurança (OCS)", descricao: "Programa de observação de comportamento seguro x inseguro — cultura BBS.",
    norma: "Behavior-Based Safety (BBS)", categoria: "LIVRE",
    pontosChave: ["Observador treinado por turma", "Foco em comportamento, não pessoa", "Feedback positivo > correção negativa", "Indicador mensal de comportamentos seguros"],
    reforco: "Comportamento mudado = acidente prevenido. Observe e dê feedback." },
  { codigo: "CULT-TF-TG", titulo: "Indicadores SST: TF e TG", descricao: "Taxa de Frequência e Taxa de Gravidade de acidentes — como calcular e interpretar.",
    norma: "ABNT NBR 14280 + INSS", categoria: "LIVRE",
    pontosChave: ["TF = (acidentes c/ afastamento × 1.000.000) / homem-hora", "TG = (dias perdidos × 1.000.000) / homem-hora", "Comparação com média do setor", "Meta anual com plano de ação"],
    reforco: "Indicador não medido é gestão no escuro. Acompanhe TF/TG mensal." },
  { codigo: "CULT-REUNIAO-CIPA", titulo: "Reunião Mensal da CIPA", descricao: "Pauta, ata e desdobramento de reunião mensal da CIPA — ferramenta de melhoria contínua.",
    norma: "NR-5", categoria: "LIVRE",
    pontosChave: ["Pauta enviada com 1 semana de antecedência", "Ata afixada em quadro visível", "Plano de ação com responsável e prazo", "Revisão dos ANTERIORES (não acumular)"],
    reforco: "CIPA sem ata viva é teatro. Cobre desdobramento das ações." },
];
