/**
 * Changelog centralizado do ERP.
 * Rev. 246 — Modal "Nova SC" redesenhado: layout compacto (sem scroll), tema definitivamente claro
 *            (style inline branco), 3 colunas Setor/Data/Prioridade, itens com scroll interno;
 *            todos os DialogContent de Compras (Solicitacoes, Cotacoes, Ordens) forçam bg branco.
 *
 * COMO USAR:
 * Ao criar uma nova revisão, basta adicionar uma entrada no final deste array.
 * O servidor sincroniza automaticamente com o banco de dados no startup.
 * Não é necessário inserir manualmente no banco — a função syncRevisions()
 * compara as versões e insere apenas as que faltam.
 * 
 * Lembre-se de atualizar também shared/version.ts com o novo número de versão.
 */

export type RevisionEntry = {
  version: number;
  titulo: string;
  descricao: string;
  tipo: 'feature' | 'bugfix' | 'melhoria' | 'seguranca' | 'performance';
  modulos: string;
  criadoPor: string;
  dataPublicacao: string; // formato: "YYYY-MM-DD HH:mm:ss"
};

export const CHANGELOG: RevisionEntry[] = [
  {
    version: 168,
    titulo: "Atualizar Controle de Revisões",
    descricao: "Adicionadas revisões 143 a 167 no Controle de Revisões do sistema, cobrindo todo o histórico de atualizações.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 06:00:00",
  },
  {
    version: 169,
    titulo: "Refazer Gestão de Competências como Wizard + Relatórios",
    descricao: "Gestão de Competências refeita como wizard passo a passo fullscreen. Cada passo ocupa tela inteira com barra de progresso no topo. Sistema mostra automaticamente o passo atual e avança sozinho. Detecção automática de inconsistências em batidas de ponto. Relatório de divergências automático.",
    tipo: "feature",
    modulos: "RH & DP,Folha de Pagamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 07:00:00",
  },
  {
    version: 170,
    titulo: "Importação DIXI Ponto Eletrônico",
    descricao: "Módulo completo de importação de arquivos DIXI do ponto eletrônico. Suporte a múltiplos relógios e obras. Parser robusto com detecção automática de formato. Visualização de batidas importadas com status por funcionário.",
    tipo: "feature",
    modulos: "RH & DP,Ponto Eletrônico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 08:00:00",
  },
  {
    version: 171,
    titulo: "Módulo Completo de Férias",
    descricao: "Módulo de gestão de férias com cálculo automático de período aquisitivo e concessivo. Controle de saldo de dias, programação de férias, abono pecuniário. Alertas de vencimento de período concessivo. Integração com folha de pagamento.",
    tipo: "feature",
    modulos: "RH & DP,Férias",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 09:00:00",
  },
  {
    version: 172,
    titulo: "Módulo de Aviso Prévio e Rescisão",
    descricao: "Gestão completa de avisos prévios com cálculo automático de datas e valores. Suporte a aviso trabalhado e indenizado. Previsão de rescisão com estimativa de valores. Notificações automáticas por email para DP e gestores.",
    tipo: "feature",
    modulos: "RH & DP,Aviso Prévio",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 10:00:00",
  },
  {
    version: 173,
    titulo: "Módulo de Convenções Coletivas",
    descricao: "Cadastro e gestão de convenções coletivas com vigência, pisos salariais e benefícios. Comparativo entre convenções via IA. Vinculação de convenção por empresa/obra. Alertas de vencimento de convenção.",
    tipo: "feature",
    modulos: "RH & DP,Convenções Coletivas",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 11:00:00",
  },
  {
    version: 174,
    titulo: "Módulo de Horas Extras e Solicitações",
    descricao: "Sistema de solicitação e aprovação de horas extras. Cálculo automático de adicional (50%, 100%). Integração com ponto eletrônico para detecção automática de HE. Relatório consolidado por obra e período.",
    tipo: "feature",
    modulos: "RH & DP,Horas Extras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 12:00:00",
  },
  {
    version: 175,
    titulo: "Módulo de Controle de Documentos",
    descricao: "Gestão centralizada de documentos trabalhistas com controle de validade. Upload e armazenamento em S3. Alertas automáticos de documentos vencidos ou próximos do vencimento. Categorização por tipo de documento.",
    tipo: "feature",
    modulos: "RH & DP,Documentos",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 13:00:00",
  },
  {
    version: 176,
    titulo: "Módulo Jurídico - Processos Trabalhistas",
    descricao: "Gestão completa de processos trabalhistas com análise de risco via IA. Controle de audiências, prazos e provisões. Dashboard jurídico com indicadores de risco. Upload de documentos processuais.",
    tipo: "feature",
    modulos: "Jurídico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 14:00:00",
  },
  {
    version: 177,
    titulo: "CIPA - Comissão Interna de Prevenção de Acidentes",
    descricao: "Módulo completo de CIPA com gestão de mandatos, eleições, atas de reunião e plano de ação. Controle de membros titulares e suplentes. Calendário de reuniões obrigatórias. Documentação conforme NR-5.",
    tipo: "feature",
    modulos: "SST,CIPA",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 15:00:00",
  },
  {
    version: 178,
    titulo: "Módulo de Terceiros e Conformidade",
    descricao: "Gestão de empresas terceiras com controle de documentação obrigatória. Painel de conformidade com status por empresa. Alertas automáticos de pendências. Obrigações mensais com checklist de entrega.",
    tipo: "feature",
    modulos: "SST,Terceiros",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 16:00:00",
  },
  {
    version: 179,
    titulo: "Avaliação de Desempenho e Pesquisas",
    descricao: "Módulo de avaliação de desempenho com pilares e critérios configuráveis. Pesquisas customizadas e clima organizacional. Avaliação 360° com participantes internos e externos. Relatórios individuais e consolidados.",
    tipo: "feature",
    modulos: "RH & DP,Avaliação de Desempenho",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 17:00:00",
  },
  {
    version: 180,
    titulo: "Correção de Erros TypeScript + Filtro de Permissões",
    descricao: "Correção de 27 erros TypeScript que bloqueavam publicação em 12 arquivos. Melhoria no filtro de permissões na Home (ModuleHub) e sidebar (DashboardLayout) para respeitar grupos de usuários.",
    tipo: "bugfix",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 18:00:00",
  },
  {
    version: 181,
    titulo: "Filtros na Tela de Processos Trabalhistas",
    descricao: "Adicionados filtros funcionais por Status e por Arquivo (com/sem anexo) na tela de Processos Trabalhistas. Botão Salvar na seção de Análise IA dos Processos.",
    tipo: "melhoria",
    modulos: "Jurídico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 19:00:00",
  },
  {
    version: 182,
    titulo: "Otimização de Performance do Sistema",
    descricao: "Implementação de code splitting e lazy loading em todas as rotas. Configuração de manual chunks no Vite para melhor caching de assets. Redução significativa do bundle inicial.",
    tipo: "performance",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 20:00:00",
  },
  {
    version: 183,
    titulo: "Reestruturação Estoque de EPI",
    descricao: "Criação de schema de estoque central (epi_estoque_central) e estoque por obra (epi_estoque_obra). Sistema de transferências do escritório para obra. Ajuste na entrega de EPI para descontar do estoque correto. Entrada direta de EPIs em obra.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 06:00:00",
  },
  {
    version: 184,
    titulo: "Validade de EPIs + Estoque Mínimo + Checklists",
    descricao: "Controle de validade de EPIs com alertas de vencimento. Configuração de estoque mínimo por EPI/obra com alertas automáticos. Checklists de inspeção de EPIs com templates configuráveis.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 07:00:00",
  },
  {
    version: 185,
    titulo: "Relatório de Custos de EPI + Dashboard EPIs",
    descricao: "Relatório detalhado de custos de EPI por obra, funcionário e período. Dashboard de EPIs com indicadores visuais: entregas, estoque, validade, custos. Gráficos interativos com drill-down.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 08:00:00",
  },
  {
    version: 186,
    titulo: "IA para Gestão de EPIs",
    descricao: "Assistente de IA para EPIs com sugestão automática de kits por função. Matching inteligente de EPIs do catálogo com entregas. Análise preditiva de consumo. Recomendações de compra baseadas em histórico.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 09:00:00",
  },
  {
    version: 187,
    titulo: "Capacidade de Contratação por EPI",
    descricao: "Análise de capacidade de contratação baseada no estoque de EPIs. Cálculo automático de quantos funcionários podem ser contratados por função. Alertas quando estoque está abaixo do necessário para novas contratações.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 10:00:00",
  },
  {
    version: 188,
    titulo: "Correção EpiCapacidade + Alertas Automáticos",
    descricao: "Correção de crash do EpiCapacidade em mobile/produção com null checks e loading states. Card 'Cap. Contratação' no dashboard principal de EPIs. Alertas automáticos por email quando capacidade abaixo do limiar configurável.",
    tipo: "bugfix",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 11:00:00",
  },
  {
    version: 189,
    titulo: "Kit Básico Automático + Desconto EPI em Folha",
    descricao: "Kit básico de contratação configurado automaticamente para cada empresa (EPIs padrão construção civil). Seed automático do kit ao acessar Capacidade. Emails de responsáveis de compras nos alertas. Desconto automático de EPI por mau uso/perda integrado à folha de pagamento.",
    tipo: "feature",
    modulos: "SST,EPIs,RH & DP",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 12:00:00",
  },
  {
    version: 190,
    titulo: "IA Assistente nos Campos de Configuração de EPIs",
    descricao: "Rotas de IA para sugestão de kits por função, cores de capacete (NR-6/NR-18), vida útil de EPIs e treinamentos obrigatórios (NR-6/10/18/33/35). Consulta automática de Regras de Ouro, funções e catálogo como contexto para a IA.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 13:00:00",
  },
  {
    version: 191,
    titulo: "Card Capacidade no Painel SST",
    descricao: "Card de Capacidade de Contratação adicionado ao Painel SST (painel inicial do módulo). Correção do filtro por obra na Capacidade.",
    tipo: "melhoria",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 14:00:00",
  },
  {
    version: 192,
    titulo: "Formatação pt-BR em Todos os Módulos + Fix Aniversariantes",
    descricao: "Função utilitária fmtNum() centralizada para formatação de números com separador de milhar pt-BR. Aplicada em 27 arquivos (110+ valores numéricos) — KPI cards, stats e contadores de todos os módulos. Correção do bug de aniversariantes que mostrava dia errado por usar UTC ao invés de GMT-3 (America/Sao_Paulo).",
    tipo: "bugfix",
    modulos: "Sistema,RH & DP,SST,Jurídico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 00:00:00",
  },
  {
    version: 193,
    titulo: "Remover Seção Administração da Sidebar",
    descricao: "Removida seção ADMINISTRAÇÃO completa da sidebar de todos os módulos (Usuários/Permissões, Grupos, Auditoria, Configurações, Revisões, Lixeira). Itens continuam acessíveis pela Home e rota direta. Também removida seção Administração do módulo Avaliação de Desempenho.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 01:00:00",
  },
  {
    version: 194,
    titulo: "Atalhos EPI na Sidebar SST",
    descricao: "Adicionados 4 atalhos de EPI à sidebar do módulo SST: Checklists EPI, Descontos EPI, Transferências EPI e Config EPI. Implementado suporte a navegação direta via ?tab= com listener navParamsUpdated para trocar aba sem recarregar a página.",
    tipo: "melhoria",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 02:00:00",
  },
  {
    version: 195,
    titulo: "Controle de Revisões Atualizado",
    descricao: "Inseridas 27 novas revisões (168 a 194) no banco de dados do Controle de Revisões. Histórico completo e atualizado.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 02:30:00",
  },
  {
    version: 196,
    titulo: "Auto-Sync de Revisões no Startup",
    descricao: "Automatização da inserção de revisões no banco de dados. Ao iniciar o servidor, o sistema compara o changelog em código com as revisões no banco e insere automaticamente as que faltam. Não é mais necessário inserir revisões manualmente no banco.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 03:00:00",
  },
  {
    version: 197,
    titulo: "Otimização de Performance + Reforço de Segurança",
    descricao: "Cache em memória com TTL de 5 min para dados estáticos (empresas, obras, funções). Rate limiting na API (200 req/min) e autenticação (20 req/min) contra brute force. Headers de segurança HTTP: X-Frame-Options, X-Content-Type-Options, HSTS, Referrer-Policy, Permissions-Policy. Proteção contra clickjacking, MIME sniffing e XSS.",
    tipo: "seguranca",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 04:00:00",
  },
  {
    version: 198,
    titulo: "Backup Automatizado + Aniversários de Empresa + Raio-X Clicável",
    descricao: "Backup automático diário do banco de dados às 03:00 (Brasília) com export JSON comprimido para S3 e notificação por e-mail/plataforma. Backup manual disponível em Configurações > Backup do Banco. Histórico de backups com download. Aniversários de empresa (anos de casa) na tela inicial. Aniversariantes clicáveis abrindo Raio-X do funcionário.",
    tipo: "feature",
    modulos: "Sistema,RH & DP",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 05:00:00",
  },
  {
    version: 199,
    titulo: "Módulo de Contratos CLT (Experiência e Indeterminado)",
    descricao: "Geração automática de contratos CLT (Experiência 30+30 ou 45+45 dias, e Indeterminado) com placeholders preenchidos automaticamente a partir do cadastro do funcionário. Valor por extenso calculado automaticamente. Horário de trabalho puxado do cadastro. Templates com LGPD, sigilo e segurança. Impressão em formato A4. Upload de contrato assinado (PDF/foto). Prorrogar e efetivar com um clique. Histórico completo na aba Contratos CLT do Raio-X do funcionário.",
    tipo: "feature",
    modulos: "RH & DP",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 08:00:00",
  },
  {
    version: 229,
    titulo: "Correção do Gráfico CronogramaFinanceiro (Planejamento)",
    descricao: "Corrigidos dois bugs críticos que impediam a exibição das barras no gráfico de Cronograma Financeiro do módulo Planejamento. (1) Bug de renderização Recharts: os elementos Bar e Line estavam envolvidos em React.Fragment dentro de ternário condicional — o Recharts v2 usa React.Children.forEach internamente e ignora fragmentos, tornando todas as barras invisíveis apesar dos dados corretos. Solução: substituir os fragments por condicionais individuais {cenario === 'lucro' && <Bar/>}. (2) Bug de timezone em mesesRange(): new Date('2026-02-01') é interpretado como UTC meia-noite, retornando Janeiro (mês 0) em navegadores UTC-3 (Brasil) em vez de Fevereiro, deslocando todos os meses por 1. Solução: usar new Date(y, m-1, 1) que cria data em horário local. Ambas as correções garantem exibição correta dos cenários Venda, Meta, Custo e Lucro com barras mensais e linhas de acumulado percentual.",
    tipo: "bugfix",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 14:33:00",
  },
  {
    version: 237,
    titulo: "Compras Fase 3 — SC Aprovação/Recebimento, OC Totais, Cotações Descrição",
    descricao: "Solicitações de Compra: widget de aprovação (Aguardando/Aprovar/Recusar), recebimento por item com barra de progresso, vínculo com Projeto/Obra, campo Título e Prioridade, KPI badges clicáveis, bug fix aprovando. Ordens de Compra: painel de totalizadores (Subtotal + Frete + Outras Despesas + Impostos - Desconto = Total), visualização da composição no detalhe. Cotações: campo Descrição no formulário e detalhe, dropdown de SC mostra título. Todos os novos campos persistidos no banco (schema Drizzle + DB).",
    tipo: "feature",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 18:00:00",
  },
  {
    version: 236,
    titulo: "Planejamento — Cores da barra: Amarelo Ouro + Azul Royal Escuro",
    descricao: "Barra Previsto agora usa Amarelo Ouro (#C9A000) com fundo crème e texto #B8860B. Barra Realizado usa Azul Royal Escuro (#1B3A8A) fixo em todas as faixas de progresso.",
    tipo: "melhoria",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:00:00",
  },
  {
    version: 235,
    titulo: "Compras — Modal Novo Fornecedor sem scroll",
    descricao: "Reorganização do formulário 'Novo Fornecedor' em layout compacto de grade (12 colunas). Todos os campos cabem na tela sem barra de rolagem: CNPJ + Razão Social + Nome Fantasia em uma linha; Endereço completo em uma linha com subcampos distribuídos; Contato em uma linha; Dados Bancários em uma linha; Categorias e Observações lado a lado. Inputs com height h-8 e texto xs para ocupar menos espaço vertical.",
    tipo: "melhoria",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:30:00",
  },
  {
    version: 234,
    titulo: "Planejamento — Barra dupla Previsto vs Realizado com Desvio",
    descricao: "O cabeçalho da tela de detalhe do projeto agora exibe duas barras de avanço físico em vez de uma: Previsto (âmbar) calculado com base no último ponto da curva planejada até hoje, e Realizado (azul/verde). Badge de desvio no canto direito: '+X.X% adiantado' (verde) ou '-X.X% atrasado' (vermelho). Se o desvio for < 0,1 pp exibe 'No prazo'. A barra previsto só aparece quando há dados de curva S disponíveis.",
    tipo: "melhoria",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:00:00",
  },
  {
    version: 233,
    titulo: "Módulo Compras — Fase 2: SC, Cotações e Ordens de Compra",
    descricao: "Implementação do fluxo completo de compras. Solicitações de Compra (SC): criação com itens (descrição/unidade/qtd), filtro por status, detalhamento e cancelamento; numeração automática SC-AAAA-NNNN. Cotações: vinculação opcional a uma SC, seleção de fornecedor, validade, condição de pagamento, prazo de entrega, itens com preço unitário e desconto percentual, cálculo automático do total; botão 'Aprovar e Gerar OC' que cria automaticamente a OC e atualiza status da SC/cotação. Ordens de Compra: criação automática via cotação aprovada ou manual, KPIs no topo (pendentes/aprovadas/entregues/total em R$), fluxo de status (pendente → aprovada → entrega parcial → entregue), detalhamento com itens e quantidade entregue. Tabelas novas: compras_solicitacoes, compras_solicitacoes_itens, compras_cotacoes, compras_cotacoes_itens, compras_ordens, compras_ordens_itens. Menu lateral reorganizado com 3 seções: Fluxo de Compras / Cadastros / Integrações.",
    tipo: "feature",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:00:00",
  },
  {
    version: 232,
    titulo: "Módulo Compras — Ativação no Hub e Menu Lateral",
    descricao: "Módulo Compras agora aparece no ModuleHub como ativo (card clicável com link para /compras/fornecedores). Menu lateral criado com seções: Compras (Fornecedores, Almoxarifado) e Integrações (Mas Controle ERP). Módulo registrado no seletor de módulos, contexto de rotas e temas do sistema (ícone ShoppingCart rosa). Ao clicar nas páginas de compras/integracoes, o sidebar muda automaticamente para o módulo Compras.",
    tipo: "melhoria",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 19:00:00",
  },
  {
    version: 231,
    titulo: "Integração Mas Controle ERP — Migração de Dados",
    descricao: "Módulo completo de integração e migração do Mas Controle ERP. Configuração de credenciais da API (Basic Auth); teste de conexão com detecção automática de URL base; importação via API REST (obras, fornecedores, insumos) com fallback automático; importação via CSV/Excel (método garantido) com parser que aceita vírgula ou ponto-e-vírgula como separador; mapeamento flexível de colunas com múltiplos candidatos de nome; importação idempotente por nome/CNPJ (nunca duplica dados); log completo por tipo de dado (encontrados, importados, duplicados, erros com detalhes); histórico de todas as migrações; marcação de migração como concluída. Tabelas: migration_logs, mas_controle_config. Rota: /integracoes/mas-controle (apenas admin_master).",
    tipo: "feature",
    modulos: "Integrações",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 17:00:00",
  },
  {
    version: 230,
    titulo: "Módulo de Compras — Fase 1: Fornecedores + Almoxarifado Central",
    descricao: "Implementação da Fase 1 do Módulo de Compras. Fornecedores: cadastro completo com busca automática de dados pela Receita Federal via CNPJ (BrasilAPI), dados de endereço, contato comercial, dados bancários/PIX, categorias de fornecimento e situação cadastral. Almoxarifado Central: cadastro de itens com unidades, categorias e estoque mínimo; movimentações de entrada/saída com validação de saldo; semáforo visual de estoque (OK/Baixo/Crítico); histórico completo de movimentações por item. Tabelas no banco: fornecedores, almoxarifado_itens, almoxarifado_movimentacoes. Rotas: /compras/fornecedores e /compras/almoxarifado.",
    tipo: "feature",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 16:00:00",
  },
  {
    version: 238,
    titulo: "Painel de Controle — Módulo de Compras",
    descricao: "Novo painel de controle centralizado do módulo Compras em /compras/painel. KPIs em tempo real: SCs pendentes e aguardando aprovação, Cotações pendentes, OCs em aberto e valor total. Seções: alertas de entregas vencidas, SCs aguardando aprovação, cotações pendentes, OCs recentes, gráfico de barras de gastos mensais, SCs recentes. Atualização automática a cada 60s. Menu Compras agora abre no Painel por padrão.",
    tipo: "feature",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:00:00",
  },
  {
    version: 239,
    titulo: "Botão Tela Inicial na barra de topo",
    descricao: "Adicionado botão 'Início' fixo na barra de topo (header) de todas as páginas internas do sistema, ao lado esquerdo do nome do módulo ativo. O botão exibe ícone Home e leva diretamente à tela inicial (Hub de Módulos). Visível em todos os módulos.",
    tipo: "improvement",
    modulos: "Global",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:10:00",
  },
  {
    version: 240,
    titulo: "Painel lateral adicionado em todas as páginas de Compras",
    descricao: "Correção de regra de ouro: todas as páginas do módulo Compras (Painel, Solicitações, Cotações, Ordens de Compra, Almoxarifado, Fornecedores) agora envolvem seu conteúdo com DashboardLayout, garantindo que o painel lateral de navegação esteja sempre visível em qualquer tela do módulo.",
    tipo: "fix",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:20:00",
  },
  {
    version: 241,
    titulo: "Painel de Compras totalmente interativo",
    descricao: "Refatoração do Painel de Compras para navegação SPA completa. KPI cards clicáveis com navegação direta para SC, Cotações e OC. Novos atalhos de navegação rápida (3 botões de acesso rápido). Todas as linhas das tabelas de SC, Cotações e OC clicáveis navegando para a página correta. Alertas de entrega clicáveis. Fornecedores ativos com link para página de fornecedores. Uso de useLocation (wouter) em vez de <a href> para navegação SPA sem recarregamento.",
    tipo: "improvement",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:30:00",
  },
  {
    version: 242,
    titulo: "Contas Bancárias removida do menu RH & DP",
    descricao: "Removido o item 'Contas Bancárias' da seção 'Financeiro' do menu lateral do módulo RH & DP (já existente no módulo Cadastro). Alteração aplicada tanto no menu salvo no banco de dados quanto no menu padrão do painel de personalização.",
    tipo: "fix",
    modulos: "RH & DP, Cadastro",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:40:00",
  },
  {
    version: 243,
    titulo: "Botão Voltar e sidebar na página Integração Mas Controle",
    descricao: "Adicionado botão 'Voltar' no cabeçalho da página de Integração Mas Controle ERP, que navega de volta ao Painel de Compras. Página agora utiliza DashboardLayout, exibindo o painel lateral de navegação do módulo Compras.",
    tipo: "improvement",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 20:50:00",
  },
  {
    version: 244,
    titulo: "Compras: tema claro + obraId obrigatório + fluxo no canvas",
    descricao: "Refatoração completa das páginas SC, Cotações e OC do módulo Compras: (1) Conversão total para tema claro (light theme) com fundo branco/cinza, bordas suaves e badges coloridos sólidos; (2) Campo 'Obra / Centro de Custo' obrigatório em todas as etapas do fluxo, usando obras ativas do cadastro; (3) obraId adicionado ao schema e banco de dados de compras_cotacoes e compras_ordens; (4) Backend atualizado para propagar obraId em criarCotacao, criarOrdemManual e criarOrdemDeCotacao; (5) Diagrama de fluxo integrado desenhado no canvas.",
    tipo: "feature",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:20:00",
  },
  {
    version: 245,
    titulo: "Compras: integração OC→Almoxarifado + obra no Painel",
    descricao: "Conexão automática entre módulos Compras e Almoxarifado: (1) Ao marcar OC como 'Entregue', os itens entram automaticamente no Almoxarifado com movimentação de entrada registrada, vinculada à obra; (2) SC itens atualizam quantidadeAtendida ao receber entrega da OC; (3) SC é marcada 'concluída' automaticamente quando todos os itens são atendidos; (4) Painel de Compras exibe o nome da obra vinculada em SCs e OCs; (5) Toast informativo no módulo OC confirma quantos itens foram enviados ao Almoxarifado.",
    tipo: "feature",
    modulos: "Compras, Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:00:00",
  },
  {
    version: 246,
    titulo: "Compras: modal Nova SC redesenhado — tema claro forçado + layout compacto",
    descricao: "Modal 'Nova Solicitação de Compra' completamente redesenhado: (1) Fundo branco forçado via style inline (bg: #ffffff) em todos os DialogContent de Compras (Solicitações, Cotações, Ordens), eliminando definitivamente o bug de tema escuro; (2) Layout 3 colunas para Setor/Data/Prioridade; (3) Inputs nativos HTML para evitar herança de tema; (4) Área de itens com scroll interno — modal inteiro não precisa rolar; (5) Mesma correção aplicada no modal Detalhe SC.",
    tipo: "fix",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:30:00",
  },
  {
    version: 247,
    titulo: "Almoxarifado: módulo independente com foto por produto",
    descricao: "Almoxarifado promovido a módulo autônomo do ERP: (1) Nova rota /almoxarifado independente do módulo Compras; (2) Módulo aparece no seletor de módulos da sidebar e no ModuleHub como ativo; (3) Vista em cards com foto do produto (upload com compressão automática para max 600x600px); (4) Vista em tabela clássica com miniatura da foto; (5) Foto do produto exibida no modal de movimentação; (6) Coluna foto_url adicionada ao banco de dados; (7) Router de Compras atualizado para CRUD de fotoUrl.",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:00:00",
  },
  {
    version: 248,
    titulo: "Fix: Notificações E-mail — erro ao adicionar destinatário",
    descricao: "Corrigido bug pré-existente na rota createRecipient das Notificações por E-mail: (1) Insert no banco estava sem .returning(), fazendo o Drizzle retornar um QueryResult não-iterável; (2) Desestruturação const [result] = ... lançava '(Intermediate value) is not iterable'; (3) O spread ...input incluía campo companyIds inexistente na tabela; (4) Agora o insert usa colunas explícitas + .returning() e retorna corretamente o id do destinatário criado.",
    tipo: "fix",
    modulos: "RH-DP, Configurações",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:30:00",
  },
  {
    version: 249,
    titulo: "Planejamento: barra de bloqueio visível na Configuração de Medição",
    descricao: "Adicionada barra de bloqueio permanente na seção Configuração de Medição do Planejamento: (1) Barra cinza/verde sempre visível abaixo dos parâmetros, fora da área de pointer-events-none; (2) Botão 'Bloquear' trava toda a configuração (modalidade + parâmetros) impedindo qualquer edição acidental; (3) Botão 'Salvar e Bloquear' quando ainda não há config gravada — salva e bloqueia em uma ação; (4) Botão 'Desbloquear' com borda verde para reativar a edição; (5) Mantido o botão 'Congelar/Descongelar' no cabeçalho escuro como ação secundária.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:45:00",
  },
  {
    version: 253,
    titulo: "Almoxarifado: cadastro de categorias com CRUD completo",
    descricao: "Criada tabela almoxarifado_categorias no banco de dados. Nova página /almoxarifado/categorias permite ao usuário criar, editar e excluir categorias. Pré-populada com 29 categorias dos insumos de construção civil (Aglomerantes, Agregados, Alvenarias, Aço Estrutural, EPIs, Ferramentas, Hidráulica, Elétrica, etc.). Campo Categoria no formulário de Novo Item agora é dropdown selecionável (não mais texto livre). Sidebar do Almoxarifado ganhou seção 'Configurações' com link para Categorias.",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 03:00:00",
  },
  {
    version: 252,
    titulo: "Notificações: mensagem de erro correta ao falhar envio de e-mail",
    descricao: "Corrigido bug no toast do 'Enviar Teste': quando o SMTP falha (enviados=0, erros>0), a mensagem mostrada era incorretamente 'Nenhum destinatário ativo para este tipo'. Agora exibe o erro real retornado pelo serviço (ex: 'SMTP não configurado. Defina SMTP_HOST, SMTP_EMAIL e SMTP_PASSWORD.'). O servidor passou a rastrear o primeiro erro de envio em primeiroErro e retorná-lo no campo erroMensagem. O cliente usa erros>0 para distinguir falha de SMTP de ausência de destinatários.",
    tipo: "bugfix",
    modulos: "Configurações / Notificações",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 02:00:00",
  },
  {
    version: 251,
    titulo: "REFIS: popup de visualização rápida ao clicar no Histórico",
    descricao: "Ao clicar em qualquer linha do 'Histórico de REFIs' na Visão Geral do projeto, abre um popup (modal) com os dados completos daquele REFIS: cabeçalho escuro com número e semana, cards de avanço previsto/realizado/desvio com barra de progresso colorida, índices SPI e CPI com semáforo, seção financeira (custo previsto vs realizado), avanço semanal e observações. Botão 'Ver REFIS Completo' navega para a aba REFIS já com a semana pré-selecionada. Linhas da tabela agora têm cursor pointer e highlight azul no hover.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 01:00:00",
  },
  {
    version: 250,
    titulo: "Planejamento: todas as abas do projeto acessíveis pela sidebar",
    descricao: "Ao navegar para um projeto no módulo Planejamento (/planejamento/:id), a sidebar exibe dinamicamente a seção 'Abas do Projeto' com todos os 14 itens de navegação (Visão Geral, Cronograma, Gantt, Linha de Balanços, Crono. Financeiro, Curva S, Avanço Semanal, Caminho Crítico, Compras, Prev. Medição, Prog. Semanal, Revisões, REFIS, IA Gestora). Clique em qualquer item da sidebar troca a aba imediatamente usando o padrão navParamsUpdated/sessionStorage já existente. Item ativo na sidebar é destacado corretamente (mesmo mecanismo sidebarActiveParam dos demais módulos). PlanejamentoDetalhe inicializa a aba a partir dos parâmetros de URL/sessionStorage ao montar.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 00:00:00",
  },
  {
    version: 254,
    titulo: "REFIS: bloqueio por consolidação — somente ADM pode cancelar",
    descricao: "Após emitir um REFIS, o usuário pode clicar em 'Consolidar' para travar o registro. Um REFIS consolidado exibe badge verde com cadeado e nome de quem consolidou. O botão 'Atualizar REFIS' fica desabilitado enquanto consolidado. Usuários comuns não veem o botão 'Cancelar Emissão' de um REFIS consolidado. Apenas administradores (isAdminMaster) visualizam os botões 'Desfazer Consolidação' (retorna ao status 'emitido') e 'Cancelar Emissão'. O servidor valida a permissão via ctx.user.role antes de executar. Colunas consolidado_por, consolidado_em, cancelado_por, cancelado_em adicionadas à tabela planejamento_refis para auditoria.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 10:00:00",
  },
  {
    version: 255,
    titulo: "Drag-and-drop global: sidebar e barras de ação",
    descricao: "Sidebar de todos os módulos suporta reordenação por drag-and-drop (itens ficam com cursor grab, drop target destacado com borda dourada). Ordem salva no localStorage por módulo. Componente DraggableCommandBar aplicado às barras de botões das páginas: Colaboradores, Empresas, Setores, Funções, Feriados, Aviso Prévio, Contas Bancárias, Dissídio, Relógios de Ponto, Usuários, Convenções Coletivas, SC/Cotações/OC/Fornecedores/Almoxarifado (Compras), Categorias do Almoxarifado, Planejamento (lista de projetos), Empresas/Funcionários/Obrigações Terceiras, Orçamentos, Parceiros. Cada barra persiste sua ordem de botões individualmente no localStorage.",
    tipo: "feature",
    modulos: "Global",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 11:00:00",
  },
  {
    version: 256,
    titulo: "Cronograma Financeiro: Lucro Previsto por BDI e Custo Total detalhado",
    descricao: "Cronograma Financeiro do Planejamento agora calcula o Lucro Previsto usando o percentual real do BDI (código L-01 Lucro Bruto da tabela orcamento_bdi) em vez da simples diferença Venda−Custo. Nova coluna 'Custo Total' exibe o custo completo incluindo Adm. Central (DI-01), Impostos/Tributos (DI-02 a DI-07), Risco (DI-08) e Comissão (DI-10), todos proporcionais à Venda mensal. Tooltip sobre o valor do Custo Total mostra o detalhamento: Material, Mão de Obra, Ind. Obra (CI), Adm. Central, Impostos, Risco, Comissão. Cabeçalho Lucro Previsto mostra '(BDI)' quando dados BDI estão disponíveis. KPI e gráfico também atualizados.",
    tipo: "fix",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 12:00:00",
  },
  {
    version: 257,
    titulo: "Avaliação de Fornecedores com Estrelas e Ranking",
    descricao: "Módulo Compras > Fornecedores ganhou sistema completo de avaliação: botão 'Avaliar' em cada fornecedor abre modal com seleção de 1 a 5 estrelas + comentário opcional e rótulo descritivo (Ruim/Regular/Bom/Muito Bom/Excelente). Nova aba 'Ranking de Avaliações' exibe os fornecedores ordenados por média de estrelas com medalhas (🥇🥈🥉). Tabela avaliacoes_fornecedor criada no banco para persistir histórico de avaliações.",
    tipo: "feature",
    modulos: "Compras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 13:00:00",
  },
  {
    version: 258,
    titulo: "REFIS BLOCO 5 — Colapso de Seções por Pavimento/Grupo",
    descricao: "Aba REFIS do Planejamento: cada card de grupo (Pavimento/Bloco) no BLOCO 5 (Avanço por Etapa) ganhou botão +/− no cabeçalho para expandir ou recolher o gráfico de barras. Clicar no cabeçalho todo também aciona o toggle. Todas as seções iniciam expandidas por padrão. Corrija também import incorreto de AuthContext em Fornecedores.tsx.",
    tipo: "melhoria",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:00:00",
  },
  {
    version: 282,
    titulo: "REFIS: eliminada sobreposição de texto nos gráficos de grupo e etapa",
    descricao: "Corrigida sobreposição de rótulos no eixo Y dos gráficos de barras 'Avanço Físico por Grupo' e 'Avanço por Etapa'. Implementado: (1) truncagem dinâmica dos nomes longos com reticências; (2) largura do eixo Y calculada automaticamente pelo comprimento máximo do label; (3) altura por linha aumentada de 48→64px (etapas) e 52→72px (grupos); (4) tooltip exibe o nome completo ao passar o mouse. Rótulos de percentual com casas decimais (.1) e peso bold.",
    tipo: "correcao",
    modulos: "Planejamento / REFIS",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 02:30:00",
  },
  {
    version: 281,
    titulo: "JULINHO: corrigido erro de validação em 'Alertas das próximas semanas'",
    descricao: "O JULINHO falhava ao clicar em Analisar no painel de Alertas das próximas 3 semanas com erro 'Invalid input: expected string, received null'. Causa: campos opcionais (recursoPrincipal, eapCodigo, dataInicio, dataFim, avancoPrevisto, avancoReal, atrasada) estavam definidos como z.string().optional() no schema Zod, que aceita undefined mas rejeita null. Corrigido para z.string().nullish() (aceita undefined E null) em todos os campos do array de atividades e insumos da rota alertasSemana.",
    tipo: "correcao",
    modulos: "Planejamento / IA (JULINHO)",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 02:00:00",
  },
  {
    version: 280,
    titulo: "Diagrama de Rede: filtro por semana, período e tela cheia",
    descricao: "Adicionados três recursos ao Diagrama de Rede / Hierarquia EAP: (1) Filtro por Semana do Projeto (Semana 01, Semana 02… calculadas automaticamente a partir das datas das atividades); (2) Filtro por Período Personalizado (campos 'De' e 'Até'); (3) Botão Tela Cheia que expande o diagrama para ocupar 100% da viewport, com saída via Esc ou botão 'Sair'. Os filtros de semana e período são mutuamente exclusivos e se limpam automaticamente.",
    tipo: "funcionalidade",
    modulos: "Planejamento / Diagrama de Rede",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 01:30:00",
  },
  {
    version: 279,
    titulo: "Obras: campo Cliente com combobox buscável",
    descricao: "Adicionado campo 'Cliente' no formulário de Nova/Editar Obra. Combobox buscável que carrega a lista do cadastro de Clientes. Permite seleção por nome ou razão social. O cliente selecionado é salvo na obra e exibido nos cards da listagem com ícone azul.",
    tipo: "funcionalidade",
    modulos: "Cadastro / Obras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:50:00",
  },
  {
    version: 278,
    titulo: "Clientes: corrigido erro na consulta automática de CNPJ",
    descricao: "A consulta de CNPJ no cadastro de Clientes passava pelo servidor (tRPC) e falhava intermitentemente. Migrada para fetch direto do browser para a BrasilAPI — mesmo padrão usado em Fornecedores, Parceiros, EPIs e outras telas. Agora ao digitar 14 dígitos o formulário é preenchido automaticamente com Razão Social, Endereço, Telefone, E-mail e Situação cadastral.",
    tipo: "correcao",
    modulos: "Cadastro / Clientes",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:30:00",
  },
  {
    version: 277,
    titulo: "REFIS PDF: layout tipo apresentação profissional",
    descricao: "Reorganizado o CSS de impressão do REFIS: (1) Corrigido bug que forçava todos os grids a 3 colunas, quebrando os 4 indicadores KPI — agora usam sm:grid-cols-4 corretamente; (2) Adicionadas quebras de página explícitas — Bloco 1+2 na pág 1, Curva S na pág 2, Grupos na pág 3+; (3) Blocos de etapa longos agora podem quebrar internamente (refis-block-tall); (4) Margens e espaçamentos compactados para eliminar páginas em branco ou com meia informação.",
    tipo: "melhoria",
    modulos: "Planejamento / REFIS",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:20:00",
  },
  {
    version: 276,
    titulo: "Visão Geral: indicadores KPI em faixa horizontal inferior",
    descricao: "Os 4 indicadores do bloco 'Evolução Física Global' (Avanço Semanal Previsto, Avanço Semanal Realizado, SPI e Desvio Físico) foram movidos da coluna lateral direita para uma faixa horizontal na parte inferior do card, exibidos lado a lado (grid 4 colunas). Responsivo: 2 colunas em telas pequenas, 4 colunas em sm+.",
    tipo: "melhoria",
    modulos: "Planejamento / Visão Geral",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:55:00",
  },
  {
    version: 275,
    titulo: "Clientes: busca CNPJ automática ao completar 14 dígitos",
    descricao: "Removido botão 'Buscar Receita'. Agora ao digitar o CNPJ completo (14 dígitos) a consulta na Receita Federal é feita automaticamente — spinner aparece durante a busca, checkmark verde quando dados foram preenchidos, alerta âmbar se situação não for 'Ativa', e mensagem em vermelho se CNPJ não for encontrado (permitindo preencher manualmente). Ao editar cliente existente, o campo não busca novamente.",
    tipo: "melhoria",
    modulos: "Cadastro / Clientes",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:45:00",
  },
  {
    version: 274,
    titulo: "Cronograma: botão Consolidar / Desconsolidar",
    descricao: "Adicionado botão 'Consolidar' na aba Cronograma do Planejamento. Quando o cronograma tem atividades, o botão aparece em verde (cadeado fechado) para consolidar e proteger contra cliques acidentais. Ao consolidar: botões Importar, Excluir e Editar ficam ocultos/desabilitados; badge 'Consolidado' aparece no título. O botão vira âmbar 'Desconsolidar' (cadeado aberto) com confirmação obrigatória para liberar. Estado salvo na coluna 'consolidado' da tabela planejamento_revisoes.",
    tipo: "feature",
    modulos: "Planejamento / Cronograma",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:30:00",
  },
  {
    version: 273,
    titulo: "Módulo Clientes: CRUD completo com auto-fetch CNPJ",
    descricao: "Novo módulo Clientes no cadastro. Tabela 'clientes' criada no banco (PJ/PF, CNPJ, CPF, endereço, contato). Router tRPC completo (list, criar, atualizar, excluir). Página Clientes.tsx com cards visuais, busca, modal de cadastro/edição com auto-preenchimento via Receita Federal (mesmo endpoint buscarCNPJ do módulo Compras). Link na sidebar Cadastro. Rota /clientes registrada.",
    tipo: "feature",
    modulos: "Cadastro / Clientes",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:00:00",
  },
  {
    version: 272,
    titulo: "Editar Projeto: campos pré-preenchidos da obra vinculada",
    descricao: "Ao abrir o modal Editar Projeto, os campos Cliente, Responsável, Local e Valor do Contrato agora são preenchidos automaticamente a partir do cadastro da obra vinculada (obraId) quando o projeto não os tem salvos. Garante que o usuário não veja campos em branco que já estão no cadastro.",
    tipo: "bugfix",
    modulos: "Planejamento / Lista de Projetos",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:10:00",
  },
  {
    version: 271,
    titulo: "Planejamento: botão Editar no card de projeto",
    descricao: "Adicionado botão Editar (ícone lápis, âmbar) nos cards da lista de projetos de planejamento. Ao clicar, abre modal com todos os campos editáveis: Nome, Cliente, Responsável, Local, Data Início, Término Contratual, Valor do Contrato, Status (dropdown Em andamento / Concluído / Suspenso / Atrasado / Planejamento) e Observações. Salva via mutation atualizarProjeto e atualiza o card imediatamente.",
    tipo: "feature",
    modulos: "Planejamento / Lista de Projetos",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:05:00",
  },
  {
    version: 270,
    titulo: "Prev. Medição: tooltip fixo e tabela sem barra de rolagem",
    descricao: "Tooltip 'Composição do Custo Total' deixava de aparecer porque o container da tabela tinha overflow-x-auto que cortava o popup absoluto. Solução: tooltip agora usa position:fixed renderizado no topo do componente (fora de qualquer overflow) via estado custoTooltip + onMouseEnter/Leave. Também removido overflow-x-auto da tabela e reduzido padding das células (py-1.5 px-2) e nomes de colunas (Custo Dir.→C. Dir., Prev.Acum%→Acum%, Real.Acum%→Real%) para que todas as colunas caibam sem barra de rolagem horizontal.",
    tipo: "bugfix",
    modulos: "Planejamento / Prev. Medição",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:55:00",
  },
  {
    version: 269,
    titulo: "Diagrama de Rede: setas aparecendo + import XML corrigido para UID→WBS",
    descricao: "Hierarquia EAP: grupos (isGrupo=true) agora são incluídos como nós pai (visual escuro distinto), gerando setas reais pai→filho. Antes: byEap filtrava grupos e zero setas eram criadas. Agora: buildHierarchyLayout recebe TODOS os itens; filtroStatus não esconde grupos em modo hierarquia. Import XML (MPP): corrigido para fazer dois passes — primeiro constrói mapa UID→WBS, depois converte referencias de UID para WBS, permitindo que predecessoras importadas apareçam no diagrama de rede. Import XLSX: já suportava leitura da coluna Predecessors nativamente.",
    tipo: "bugfix",
    modulos: "Planejamento / Diagrama de Rede / Importar Cronograma",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:45:00",
  },
  {
    version: 268,
    titulo: "Bugfix: ReferenceError user is not defined na Visão Geral",
    descricao: "Corrigido erro crítico na aba Visão Geral ao clicar em 'Ver detalhes' das Atividades em Atraso. A função VisaoGeral é definida fora do escopo do componente principal e portanto não tinha acesso ao objeto 'user' do useAuth(). Solução: prop 'user' adicionada ao componente VisaoGeral e passada no ponto de chamada, mantendo acesso a user?.name, user?.role e user?.email para o PrintHeader.",
    tipo: "bugfix",
    modulos: "Planejamento / Visão Geral",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:15:00",
  },
  {
    version: 267,
    titulo: "Diagrama de Rede — Reescrita completa: hierarquia EAP + rede CPM, filtros, setas, painel de detalhes",
    descricao: "DiagramaRede.tsx completamente reescrito. Dois modos: (1) Hierarquia EAP — árvore horizontal baseada nos códigos EAP, sempre disponível, setas pai→filho; (2) Rede de Precedências — diagrama CPM topológico baseado no campo predecessora, com indicador quando sem dependências cadastradas. Filtros: status em pills clicáveis, busca por nome/EAP, filtro de grupo dropdown. Interatividade: clique em nó destaca predecessoras/sucessoras com setas coloridas, dimming dos demais nós, painel lateral com detalhes completos (EAP, status, datas, progresso, desvio, lista de predecessoras/sucessoras clicáveis). Zoom/pan suave, fit-to-view automático, barra de status com contagem por categoria.",
    tipo: "feature",
    modulos: "Planejamento / Diagrama de Rede",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:00:00",
  },
  {
    version: 266,
    titulo: "REGRA DE OURO — Nova aba SEMPRE vai para a barra lateral; Diagrama de Rede adicionado",
    descricao: "Estabelecida regra de ouro: toda nova aba criada em qualquer módulo deve ser adicionada simultaneamente à barra de comando lateral (seção 'Abas do Projeto' para Planejamento, ou seção correspondente). Aplicação imediata: 'Diagrama de Rede' (tab=diagrama-rede) adicionado ao planTabItems em DashboardLayout com ícone Network, logo após 'Prog. Semanal'. Ícone Network importado do lucide-react.",
    tipo: "melhoria",
    modulos: "Menu Lateral / Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:15:00",
  },
  {
    version: 265,
    titulo: "Atividades em Atraso — Tela Cheia + Imprimir/PDF com dados do usuário (Regra de Ouro)",
    descricao: "O modal de Atividades em Atraso foi transformado em uma tela cheia profissional. Barra de ação sticky com: botão Voltar, Imprimir e Gerar PDF (A4). NOVA REGRA DE OURO: todo PDF/impressão gerado pelo sistema inclui obrigatoriamente o cabeçalho com logo da empresa, título do relatório, nome completo do usuário, cargo, e-mail e data/hora de geração (horário de Brasília). Layout dos cards redesenhado: borda esquerda vermelha, cabeçalho âmbar, barras de progresso mais espessas com valor interno, card de desvio em destaque. PrintHeader.tsx atualizado para aceitar dados do usuário.",
    tipo: "feature",
    modulos: "Planejamento / Visão Geral",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:00:00",
  },
  {
    version: 264,
    titulo: "Menu lateral — Drag-and-drop de seções com Ajuda fixada por último",
    descricao: "Cada seção do menu lateral (ex: PLANEJAMENTO, ABAS DO PROJETO) pode ser arrastada para reorganizar sua posição. Ao passar o mouse sobre o cabeçalho da seção, aparece um ícone de arrastar (⠿) na esquerda. Arrastar e soltar reordena as seções e persiste a ordem no localStorage (separado por módulo). A seção 'Ajuda' é sempre fixada por último e não pode ser movida — exibe '(fixo)' discretamente ao lado do título. Feedback visual: a seção sendo arrastada fica com opacidade reduzida; a zona de destino recebe destaque âmbar.",
    tipo: "melhoria",
    modulos: "Menu Lateral (todos os módulos)",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:45:00",
  },
  {
    version: 263,
    titulo: "REFIS — Redesign profissional do Bloco 'Evolução Física Global'",
    descricao: "Layout do bloco Evolução Física Global reformulado para apresentações e PDF: cabeçalho dark com gradiente, barras bullet com fundo colorido suave, marcadores de milestone em 25%/50%/75%, label 'Saldo' visível no espaço restante da barra, linha de referência do previsto sobreposta na barra do realizado, valores em tipografia bold, rodapé com datas da obra e SPI inline. Cards KPI reorganizados em grid vertical (desktop) com mini-barras de escala. Nenhum espaço em branco desperdiçado — layout preparado para impressão.",
    tipo: "melhoria",
    modulos: "Planejamento / REFIS",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:30:00",
  },
  {
    version: 262,
    titulo: "Planejamento — Nova aba Diagrama de Rede",
    descricao: "Adicionada aba 'Diagrama de Rede' no módulo de Planejamento. O diagrama renderiza as atividades como nós (retângulos) conectados por setas de dependência conforme o campo predecessora. Layout automático por níveis topológicos (BFS). Código de cores: Verde = Concluída (100%), Azul = Em andamento, Vermelho = Atrasada (prazo vencido e incompleta), Amarelo = Em risco (atrás do esperado proporcional). Funcionalidades: zoom por scroll, pan por arraste, filtro por status, toggle de grupos, painel de detalhes ao clicar em uma atividade (datas, progresso atual vs. esperado, desvio em pp), botão 'Encaixar na tela'. Legenda visual e barra de resumo por status.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:00:00",
  },
  {
    version: 261,
    titulo: "Programação Semanal — Badge 'Semana Atual' + Seletor de Quantidade de Semanas",
    descricao: "Na aba Programação Semanal do Planejamento: (1) Badge verde pulsante 'Semana Atual' aparece no navegador central quando a semana exibida corresponde à semana corrente do calendário. (2) No modo Relatório, botões 1 a 6 permitem ao usuário selecionar quantas semanas exibir no relatório; o botão principal reflete dinamicamente o número escolhido (ex: 'Relatório 4 Semanas'). Grid do relatório ajusta colunas automaticamente conforme o número de semanas.",
    tipo: "melhoria",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:30:00",
  },
  {
    version: 295,
    titulo: "Crono. Financeiro — Correção: erro ao salvar configuração de medição",
    descricao: "Substituído o padrão SELECT→INSERT/UPDATE por upsert atômico (ON CONFLICT DO UPDATE) na configuração de medição. Elimina falhas por race condition ao salvar pela primeira vez.",
    tipo: "bugfix",
    modulos: "Planejamento / Crono. Financeiro",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 01:30:00",
  },
  {
    version: 294,
    titulo: "REFIS — Correção: isAdminMaster não definido ao consolidar",
    descricao: "Corrigido ReferenceError ao clicar em 'Consolidar REFIS': a variável isAdminMaster não estava sendo passada como prop para o componente Refis. Agora é propagada corretamente do componente pai.",
    tipo: "bugfix",
    modulos: "Planejamento / REFIS",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 01:10:00",
  },
  {
    version: 293,
    titulo: "REFIS — Todos os blocos com colapso/expansão",
    descricao: "Adicionado botão de colapso/expansão (chevron) em todos os blocos do relatório REFIS: Evolução Física Global, Curva S Física, Curva S Financeira, Avanço Físico por Grupo, Faturamento do Mês e Histórico de Relatórios Emitidos. Clique no cabeçalho de qualquer seção para fechar ou expandir.",
    tipo: "feature",
    modulos: "Planejamento / REFIS",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 01:00:00",
  },
  {
    version: 292,
    titulo: "Obras — Cliente e Responsável somente leitura na edição",
    descricao: "Na tela 'Editar Projeto' de Obras, os campos Cliente e Engenheiro/Responsável agora são exibidos como texto não editável. O botão '+ Cadastrar cliente' e os comboboxes interativos aparecem apenas no cadastro de nova obra, evitando alterações acidentais.",
    tipo: "feature",
    modulos: "Cadastro / Obras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:40:00",
  },
  {
    version: 291,
    titulo: "Login — removidos botão OAuth e aviso de senha padrão",
    descricao: "Removidos da tela de login: botão 'Entrar com Manus OAuth', divisor 'ou' e texto 'Senha padrão para primeiro acesso: asdf1020'. Tela de login agora exibe apenas o formulário de e-mail e senha.",
    tipo: "feature",
    modulos: "Auth / Login",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:35:00",
  },
  {
    version: 290,
    titulo: "Menu RH & DP — link Colaboradores adicionado à seção Principal",
    descricao: "Adicionado atalho direto para a página de Colaboradores no menu lateral do módulo RH & DP, na seção Principal, ao lado do Painel RH. Facilita acesso imediato à lista de funcionários sem precisar ir ao módulo Cadastro.",
    tipo: "feature",
    modulos: "RH & DP",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:30:00",
  },
  {
    version: 289,
    titulo: "Obras — busca de colaboradores corrigida + responsavelId + timeline",
    descricao: "1) Corrigido bug de busca case-sensitive em Colaboradores (LIKE → ILIKE no PostgreSQL). 2) listLiderancas corrigido para usar status='Ativo' em vez de isActive=1 (campo inexistente). 3) Adicionada coluna responsavelId na tabela obras, armazenando o ID do colaborador selecionado. 4) Ao vincular responsável em uma obra, entra entrada 'gestor_obra' na timeline do colaborador (Efetivo nas Obras → histórico). 5) ObraEfetivo.tsx exibe tipo 'Responsável / Gestor' em verde.",
    tipo: "bugfix",
    modulos: "Cadastro / Obras / RH",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:00:00",
  },
  {
    version: 288,
    titulo: "Obras — Engenheiro Responsável vinculado a colaboradores RH",
    descricao: "O campo 'Engenheiro / Responsável' no formulário de Obras agora exibe um combobox buscável conectado ao banco de colaboradores. Somente funcionários com cargos/funções de liderança aparecem (Engenheiro, Encarregado, Mestre, Coordenador, Supervisor, Gerente, Diretor, Técnico, Arquiteto, Gestor, Líder). O nome selecionado é salvo no campo 'responsavel' da obra para rastreabilidade.",
    tipo: "feature",
    modulos: "Cadastro / Obras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:30:00",
  },
  {
    version: 287,
    titulo: "Obras — campo Cliente obrigatório + cadastro rápido inline",
    descricao: "Removido texto '(opcional)' do campo Cliente no formulário de obra. Adicionado botão '+ Cadastrar cliente' no label e opção ao final do dropdown. Ao clicar, abre mini-modal com campos: Razão Social (obrigatório), Nome Fantasia, Telefone e E-mail. Após salvar, o novo cliente é selecionado automaticamente na obra.",
    tipo: "feature",
    modulos: "Cadastro / Obras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:00:00",
  },
  {
    version: 286,
    titulo: "Fix IA Gestora — tab não rola mais a tela para baixo ao abrir",
    descricao: "O scroll automático do chat do JULINHO agora só é acionado quando há mensagens no histórico (historico.length > 0). Antes, o useEffect disparava ao montar o componente (mesmo sem mensagens) causando scroll indesejado para o final da tela ao clicar na aba IA Gestora.",
    tipo: "bugfix",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 00:00:00",
  },
  {
    version: 285,
    titulo: "Diagrama de Rede — card mostra Previsto/Realizado/Desvio",
    descricao: "Card de atividade no Diagrama de Rede ampliado (72→82px) com nova linha: 'Prev: XX% · Real: XX% · ±XXpp'. O desvio positivo aparece em verde e o negativo em vermelho. A barra de progresso ganhou um marcador vertical roxo indicando o % previsto esperado para hoje, enquanto a barra colorida representa o realizado.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:45:00",
  },
  {
    version: 284,
    titulo: "Dar Baixa — valor editável + saldo automático ao próximo mês",
    descricao: "Botão 'Dar Baixa' agora abre modal para digitar o valor efetivamente recebido (pré-preenchido com o previsto). Se o cliente pagar menos, o saldo pendente é exibido automaticamente na próxima competência como crédito a recuperar. Toast de sucesso informa o valor recebido e o saldo carregado. Confirmação também via Enter no campo.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:30:00",
  },
  {
    version: 283,
    titulo: "Fix 'Salvar Configuração' de Medição não salvava",
    descricao: "Botão 'Salvar Configuração' em Configuração de Medição movido para fora do bloco pointer-events-none (que bloqueava cliques quando cfgBloqueado era true). Adicionado type='button' para evitar submit acidental de form. Feedback de erro visível via toast quando a mutação falha, e toast de sucesso ao salvar corretamente.",
    tipo: "bugfix",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 23:00:00",
  },
  {
    version: 260,
    titulo: "Visão Geral — Remove card 'Dados do Projeto' redundante",
    descricao: "Removido o card 'Dados do Projeto' da aba Visão Geral do Planejamento, pois as mesmas informações já estão disponíveis no cabeçalho fixo da tela. O widget de Atividades em Atraso passou a ocupar largura total.",
    tipo: "melhoria",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 22:00:00",
  },
  {
    version: 259,
    titulo: "Atividades em Atraso — Progresso Esperado vs. Realizado + Modal Detalhado",
    descricao: "Widget 'Atividades em Atraso' na Visão Geral do Planejamento reformulado: cada card agora exibe duas barras de progresso — 'Deveria estar hoje' (cálculo proporcional ao cronograma entre dataInicio e dataFim) e 'Realizado hoje' (avanço físico lançado). A lógica de detecção de atraso foi expandida para incluir atividades ainda dentro do prazo mas abaixo do esperado. Ao clicar no título ou em qualquer card, um modal detalhado se abre mostrando, para cada atividade: nome, código EAP, datas de início e fim, dias de atraso, barras visuais com percentuais e desvio em pontos percentuais.",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-14 21:30:00",
  },
  {
    version: 296,
    titulo: "Programação Semanal — Mão de Obra, Materiais e EQUIPAMENTOS com disponibilidade no almoxarifado",
    descricao: "Seção de recursos da Prog. Semanal completamente remodelada: (1) Mão de Obra exibe apenas pessoas/ofícios detectados por palavras-chave (pedreiro, servente, armador etc.) em tabela clara com qtd e unidade; (2) Materiais listados em tabela com descrição, quantidade e unidade; (3) Nova seção EQUIPAMENTOS que separa automaticamente os equipamentos do orçamento (vibrador, betoneira, bomba, andaime etc.) da mão de obra pura, e cruza com o módulo Almoxarifado + Patrimônio para indicar disponibilidade em tempo real (verde = disponível / vermelho = indisponível / cinza = não cadastrado). Melhorias espelhadas também no Relatório de N Semanas (modo impressão).",
    tipo: "feature",
    modulos: "Planejamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 10:00:00",
  },
  {
    version: 297,
    titulo: "Módulo Almoxarifado — Comodato Diário, Inventário Semanal, Ações Rápidas Mobile",
    descricao: "Implementação completa do Módulo Almoxarifado: (1) 4 botões de ação rápida mobile-first na página principal (ENTRADA / SAÍDA / EMPRESTAR / FECHAR DIA) com confirmação visual verde/vermelha; (2) Comodato diário de ferramentas com busca por código JFCxxxx, exibe nome do funcionário, desconta estoque e registra movimentação; (3) Fechar Dia: lista empréstimos do dia com botão Devolver por item; (4) Nova página Movimentações com histórico completo, filtros por tipo e resumo; (5) Nova página Inventário Semanal com sessão semanal, barra de progresso, botões BATE/DIFERENTE por item, registro de divergências; (6) Novas tabelas warehouse_loans, warehouse_inventory_sessions, warehouse_inventory_session_items no PostgreSQL; (7) Router warehouse.ts com 15+ endpoints; (8) Menu do módulo atualizado com Movimentações e Inventário Semanal; (9) PWA habilitado (manifest.json, metas Apple/Android, banner de instalação); (10) Job de inventário semanal registrado.",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 11:00:00",
  },
  {
    version: 298,
    titulo: "Almoxarifado Central + por Obra — Estoque separado por contexto",
    descricao: "Almoxarifado agora suporta estoque separado por contexto: (1) Coluna obra_id adicionada à tabela almoxarifado_itens (NULL = Central, número = Obra específica); (2) Seletor de contexto horizontal na parte superior da página com pills coloridos: 🏢 Central (verde) e uma pill azul por obra ativa; (3) Ao trocar de contexto, a lista de itens é recarregada automaticamente mostrando apenas o estoque daquele almoxarifado; (4) Ao criar novo item, ele é associado ao contexto atual (Central ou Obra); (5) Título da página muda dinamicamente conforme o contexto selecionado; (6) Backend atualizado: listarItens filtra por obraId (IS NULL para Central, = X para Obra), criarItem aceita obraId.",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 12:00:00",
  },
  {
    version: 299,
    titulo: "Inventário Semanal por contexto — Central e por Obra com sessões independentes",
    descricao: "Inventário Semanal agora é separado por contexto de almoxarifado: (1) Seletor de contexto (pills Central / Obra) na página de Inventário igual ao da página principal; (2) Cada contexto tem sua própria sessão de inventário independente por semana; (3) Ao iniciar inventário, apenas os itens do contexto selecionado são carregados para conferência; (4) Título e subtítulo da sessão exibem o contexto atual; (5) Coluna obra_id adicionada à tabela warehouse_inventory_sessions no banco de dados.",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 13:00:00",
  },
  {
    version: 306,
    titulo: "Colaboradores — Busca por CPF/RG sem formatação",
    descricao: "A busca de colaboradores agora funciona com CPF/RG sem formatação (ex: '36250688854' encontra '362.506.888-54'). Usa regexp_replace no banco para comparar apenas os dígitos dos campos CPF e RG. Busca por nome, função, cargo, setor e código interno continuam funcionando normalmente.",
    tipo: "fix",
    modulos: "Colaboradores, RH",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 18:30:00",
  },
  {
    version: 305,
    titulo: "Colaboradores — Corrigido erro '(intermediate value) is not iterable' ao salvar",
    descricao: "db.execute() do Drizzle ORM retorna { rows: [...] } e não um array direto. Desestruturação const [x] = await db.execute() substituída pelo padrão correto exec.rows ?? exec. Corrigidas todas as ocorrências na função createEmployee e updateEmployee.",
    tipo: "fix",
    modulos: "Colaboradores, RH",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 18:00:00",
  },
  {
    version: 304,
    titulo: "Colaboradores — Corrigido erro ao salvar novo colaborador (código interno)",
    descricao: "Query SQL bruta que incrementa nextCodigoInterno da empresa não usava aspas nos nomes de coluna camelCase, causando erro no PostgreSQL. Corrigidas todas as referências a nextCodigoInterno, prefixoCodigo e numerosProibidos nas queries raw de geração de código JFCxxx.",
    tipo: "fix",
    modulos: "Colaboradores, RH",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 17:30:00",
  },
  {
    version: 303,
    titulo: "Colaboradores — Corrigido bloqueio de CPF de registro excluído",
    descricao: "A verificação de CPF duplicado agora ignora registros com deletedAt preenchido (excluídos). Antes, ao excluir um colaborador e tentar recadastrá-lo, o sistema bloqueava com erro 'CPF já cadastrado'. Registros fisicamente excluídos também são limpos do banco. Fix em checkDuplicateCpf: adicionado isNull(employees.deletedAt) às condições da query.",
    tipo: "fix",
    modulos: "Colaboradores, RH",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 17:00:00",
  },
  {
    version: 302,
    titulo: "Almoxarifado — Obra obrigatória na saída",
    descricao: "Campo 'Obra' nos modais de Registrar Saída (rápido) e Movimentação passou de campo de texto livre/opcional para select obrigatório com lista de obras ativas. Validação bloqueia confirmação sem obra selecionada. obraId e obraNome são gravados no histórico de movimentações.",
    tipo: "melhoria",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 16:00:00",
  },
  {
    version: 301,
    titulo: "Almoxarifado — Seletor de contexto como dropdown",
    descricao: "Substituição da barra de pills horizontais (que ficava apertada com muitas obras) por um select dropdown estilizado nas páginas de Almoxarifado e Inventário Semanal: ícone dinâmico (🏢 verde = Central, 🏗️ azul = Obra), opção 'Almoxarifado Central' no topo, obras agrupadas em optgroup, seleção nativa mobile-friendly.",
    tipo: "melhoria",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 15:00:00",
  },
  {
    version: 300,
    titulo: "Almoxarifado — Cadastro de Unidades de Medida",
    descricao: "Campo de unidade do item do almoxarifado agora usa um cadastro controlado: (1) Nova tabela almoxarifado_unidades no banco; (2) 22 unidades padrão pré-cadastradas automaticamente (un, kg, m, m², m³, L, cx, sc, rolo, barra, etc.); (3) Campo livre substituído por select controlado; (4) Modal 'Gerenciar Unidades' acessível pelo link 'Gerenciar' no formulário de item: exibe lista de unidades com botão excluir e formulário para adicionar nova unidade com sigla + descrição; (5) Proteção contra exclusão de unidade em uso por algum item.",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 14:00:00",
  },
  {
    version: 311,
    titulo: "Almoxarifado — Busca de item por foto com IA (Gemini Vision)",
    descricao: "Novo botão 'Foto IA' na barra de busca do almoxarifado: o usuário tira uma foto (câmera ou arquivo) do produto/ferramenta; o Gemini Vision analisa a imagem e retorna até 5 itens do catálogo mais prováveis em ordem de similaridade com porcentagem de match e justificativa; ao clicar no item identificado, a busca é preenchida automaticamente. Funciona no contexto atual (Almoxarifado Central ou por Obra).",
    tipo: "feature",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 18:00:00",
  },
  {
    version: 310,
    titulo: "Correção: campos booleanos como smallint ao salvar colaborador",
    descricao: "updateEmployee convertia campos booleanos (listaNegra, recebeComplemento, acordoHoraExtra, pensaoAlimenticia, licencaMaternidade, ddsParticipacao) para true/false JavaScript, mas as colunas no PostgreSQL são smallint (0/1). Agora a conversão usa 1/0, eliminando o erro 'Failed query' ao clicar em Salvar no cadastro de colaborador.",
    tipo: "bugfix",
    modulos: "Colaboradores",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 17:30:00",
  },
  {
    version: 309,
    titulo: "Upload de foto de funcionário via armazenamento local",
    descricao: "Substituído o upload de fotos de funcionários do storage proxy externo (BUILT_IN_FORGE_API_URL) por armazenamento local no servidor em server/uploads/photos/. As fotos são salvas em disco e servidas via rota estática /uploads/photos/{arquivo}. Elimina o erro 'Storage proxy credentials missing' que impedia o cadastro de fotos.",
    tipo: "bugfix",
    modulos: "Colaboradores",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 17:00:00",
  },
  {
    version: 320,
    titulo: "Almoxarifado — Controle de Equipamentos Locados (Alugado/Próprio)",
    descricao: "Novo campo 'Origem' no cadastro de itens: 'Próprio da Empresa' ou 'Alugado / Locado'. Quando alugado, exibe campos extras: Fornecedor/Locadora, Data Início, Data de Vencimento, Valor Mensal e Observações do Contrato. Badge 'LOCADO' (laranja) aparece nos cards. Contador de vencimento direto no card (verde > 7d, laranja ≤ 7d, vermelho vencido). Alerta no header do módulo quando há locações a vencer em até 30 dias. Botão de devolução (✓) por card para registrar a devolução ao fornecedor e desativar o item. Modal de confirmação de devolução com campo de observação.",
    tipo: "funcionalidade",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 22:00:00",
  },
  {
    version: 319,
    titulo: "Timeline — Empréstimos e Devoluções de ferramentas aparecem no Raio-X",
    descricao: "A timeline cronológica do funcionário agora exibe eventos de 'Empréstimo' (azul) quando o colaborador retira uma ferramenta/equipamento do almoxarifado, e 'Devolução' (cinza) quando devolve. Dados exibidos: item, quantidade, almoxarife responsável e data. Implementado via query em warehouseLoans.funcionarioId no endpoint raioX de controleDocumentos. Cor 'violet' adicionada ao mapa de cores da timeline no frontend.",
    tipo: "funcionalidade",
    modulos: "Almoxarifado, Colaboradores",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 21:30:00",
  },
  {
    version: 318,
    titulo: "Almoxarifado — Acesso rápido a Registros (Entradas, Saídas, Emprestados, Cadastros)",
    descricao: "Adicionada linha secundária de botões abaixo das ações principais (ENTRADA, SAÍDA, EMPRESTAR, FECHAR DIA) com acesso rápido a: ↓ Entradas, ↑ Saídas, 🔧 Emprestados, 📦 Cadastros. Cada botão abre um modal de tela cheia 'Registros do Almoxarifado' com 4 abas: Entradas mostra todas as movimentações de entrada com item, quantidade, responsável e data; Saídas mostra saídas com obra de destino; Emprestados lista empréstimos em aberto com botão de devolução direta; Cadastros lista todos os itens cadastrados com foto e estoque atual.",
    tipo: "funcionalidade",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 21:00:00",
  },
  {
    version: 317,
    titulo: "Correção — thinkingConfig no nível incorreto da API Gemini",
    descricao: "thinkingConfig estava no nível raiz do body da requisição (inválido) em vez de dentro de generationConfig. Corrigido o aninhamento para generationConfig.thinkingConfig.thinkingBudget=0, eliminando o erro 400 'Unknown name thinkingConfig: Cannot find field' ao analisar foto de produto.",
    tipo: "correcao",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 20:30:00",
  },
  {
    version: 316,
    titulo: "Almoxarifado — Modal Novo Item: remove Código Interno e corrige digitação de quantidade",
    descricao: "Removido campo 'Código Interno' do modal de cadastro de item (campo desnecessário para almoxarifado). Corrigidos os campos 'Qtd. Mínima (alerta)' e 'Quantidade Inicial em Estoque' que usavam type=number controlado e travavam ao digitar; substituídos por type=text com inputMode=decimal, aceitando vírgula e ponto como separador decimal.",
    tipo: "melhoria",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 20:00:00",
  },
  {
    version: 315,
    titulo: "Correção — IA de cadastro de item truncando JSON (tokens insuficientes)",
    descricao: "Corrigido erro 'Unterminated string in JSON' na análise de foto IA do cadastro de item. Causa: maxOutputTokens=250 era insuficiente para o Gemini 2.5 Flash (modelo 'thinking' que consome tokens internos). Solução: aumentado para 1024 e adicionado thinkingBudget=0 para desabilitar o modo de raciocínio desnecessário na tarefa. Extração do JSON agora usa regex /{[\s\S]*}/ para ser mais robusta mesmo se a resposta vier com markdown.",
    tipo: "correcao",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 19:30:00",
  },
  {
    version: 314,
    titulo: "Almoxarifado — Dropdown de obras restrito por perfil do usuário",
    descricao: "Usuários comuns (almoxarifes) só visualizam as obras às quais estão alocados via obra_funcionarios. Admins e Admin Masters continuam vendo todas as obras ativas. Se o almoxarife tiver apenas uma obra vinculada, ela é selecionada automaticamente ao abrir o módulo. Novo endpoint obras.listForAlmoxarifado implementado no backend com verificação de role e lookup por e-mail do usuário.",
    tipo: "melhoria",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 19:00:00",
  },
  {
    version: 313,
    titulo: "Correção — Análise de Foto por IA não retornava resultados",
    descricao: "Corrigido bug crítico em que a função de IA (Gemini Vision) era importada com nome incorreto ('invoke' em vez de 'invokeLLM'), fazendo com que as chamadas fossem silenciosamente ignoradas. Afetava tanto a busca por foto no catálogo quanto o preenchimento automático de cadastro. Ambos os endpoints corrigidos.",
    tipo: "correcao",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 18:00:00",
  },
  {
    version: 312,
    titulo: "Almoxarifado — Cadastro de Item com Preenchimento Automático por IA",
    descricao: "Ao fazer upload de foto no modal 'Novo Item de Estoque', a IA (Gemini Vision) analisa a imagem e preenche automaticamente: nome técnico, categoria, unidade e observações. Spinner 'Analisando com IA…' durante o processamento; badge verde 'Campos preenchidos pela IA' ao concluir. Campos já preenchidos pelo usuário não são sobrescritos. Funciona apenas ao criar novo item. Novo endpoint sugerirCadastroItem no backend.",
    tipo: "funcionalidade",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 17:30:00",
  },
  {
    version: 308,
    titulo: "Almoxarifado — Modal Emprestar: tela maior e foto do funcionário ampliada",
    descricao: "Modal 'Emprestar Ferramenta' ampliado para max-w-lg. Card de funcionário selecionado redesenhado: foto circular centralizada de 112px (w-28 h-28) com borda esmeralda e sombra, nome e cargo abaixo. Ícone genérico também em 112px quando não há foto cadastrada.",
    tipo: "melhoria",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 16:30:00",
  },
  {
    version: 307,
    titulo: "Almoxarifado — Busca de funcionário por nome no modal Emprestar Ferramenta",
    descricao: "Modal 'Emprestar Ferramenta' agora conta com busca inteligente por código (JFCxxxx) ou nome: campo único de texto dispara autocomplete com até 6 sugestões exibindo foto + nome + cargo; ao selecionar o funcionário, um card de confirmação (com foto circular ou ícone) aparece com botão de limpar; foto real do funcionário exibida quando disponível. Novo endpoint searchFuncionarios no backend com busca por nome, código ou cargo via ilike.",
    tipo: "melhoria",
    modulos: "Almoxarifado",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-15 16:00:00",
  },
];
