/**
 * Changelog centralizado do ERP.
 * 
 * COMO USAR:
 * Ao criar uma nova revisão, basta adicionar uma entrada no final deste array.
 * O servidor sincroniza automaticamente com o banco de dados no startup.
 * Não é necessário inserir manualmente no banco — a função syncRevisions()
 * compara as versões e insere apenas as que faltam.
 * 
 * Lembre-se de atualizar também shared/version.ts com o novo número de versão.
 */

export type RevisionEntry = {
  version: number;
  titulo: string;
  descricao: string;
  tipo: 'feature' | 'bugfix' | 'melhoria' | 'seguranca' | 'performance';
  modulos: string;
  criadoPor: string;
  dataPublicacao: string; // formato: "YYYY-MM-DD HH:mm:ss"
};

export const CHANGELOG: RevisionEntry[] = [
  {
    version: 168,
    titulo: "Atualizar Controle de Revisões",
    descricao: "Adicionadas revisões 143 a 167 no Controle de Revisões do sistema, cobrindo todo o histórico de atualizações.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 06:00:00",
  },
  {
    version: 169,
    titulo: "Refazer Gestão de Competências como Wizard + Relatórios",
    descricao: "Gestão de Competências refeita como wizard passo a passo fullscreen. Cada passo ocupa tela inteira com barra de progresso no topo. Sistema mostra automaticamente o passo atual e avança sozinho. Detecção automática de inconsistências em batidas de ponto. Relatório de divergências automático.",
    tipo: "feature",
    modulos: "RH & DP,Folha de Pagamento",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 07:00:00",
  },
  {
    version: 170,
    titulo: "Importação DIXI Ponto Eletrônico",
    descricao: "Módulo completo de importação de arquivos DIXI do ponto eletrônico. Suporte a múltiplos relógios e obras. Parser robusto com detecção automática de formato. Visualização de batidas importadas com status por funcionário.",
    tipo: "feature",
    modulos: "RH & DP,Ponto Eletrônico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 08:00:00",
  },
  {
    version: 171,
    titulo: "Módulo Completo de Férias",
    descricao: "Módulo de gestão de férias com cálculo automático de período aquisitivo e concessivo. Controle de saldo de dias, programação de férias, abono pecuniário. Alertas de vencimento de período concessivo. Integração com folha de pagamento.",
    tipo: "feature",
    modulos: "RH & DP,Férias",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 09:00:00",
  },
  {
    version: 172,
    titulo: "Módulo de Aviso Prévio e Rescisão",
    descricao: "Gestão completa de avisos prévios com cálculo automático de datas e valores. Suporte a aviso trabalhado e indenizado. Previsão de rescisão com estimativa de valores. Notificações automáticas por email para DP e gestores.",
    tipo: "feature",
    modulos: "RH & DP,Aviso Prévio",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 10:00:00",
  },
  {
    version: 173,
    titulo: "Módulo de Convenções Coletivas",
    descricao: "Cadastro e gestão de convenções coletivas com vigência, pisos salariais e benefícios. Comparativo entre convenções via IA. Vinculação de convenção por empresa/obra. Alertas de vencimento de convenção.",
    tipo: "feature",
    modulos: "RH & DP,Convenções Coletivas",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 11:00:00",
  },
  {
    version: 174,
    titulo: "Módulo de Horas Extras e Solicitações",
    descricao: "Sistema de solicitação e aprovação de horas extras. Cálculo automático de adicional (50%, 100%). Integração com ponto eletrônico para detecção automática de HE. Relatório consolidado por obra e período.",
    tipo: "feature",
    modulos: "RH & DP,Horas Extras",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 12:00:00",
  },
  {
    version: 175,
    titulo: "Módulo de Controle de Documentos",
    descricao: "Gestão centralizada de documentos trabalhistas com controle de validade. Upload e armazenamento em S3. Alertas automáticos de documentos vencidos ou próximos do vencimento. Categorização por tipo de documento.",
    tipo: "feature",
    modulos: "RH & DP,Documentos",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 13:00:00",
  },
  {
    version: 176,
    titulo: "Módulo Jurídico - Processos Trabalhistas",
    descricao: "Gestão completa de processos trabalhistas com análise de risco via IA. Controle de audiências, prazos e provisões. Dashboard jurídico com indicadores de risco. Upload de documentos processuais.",
    tipo: "feature",
    modulos: "Jurídico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 14:00:00",
  },
  {
    version: 177,
    titulo: "CIPA - Comissão Interna de Prevenção de Acidentes",
    descricao: "Módulo completo de CIPA com gestão de mandatos, eleições, atas de reunião e plano de ação. Controle de membros titulares e suplentes. Calendário de reuniões obrigatórias. Documentação conforme NR-5.",
    tipo: "feature",
    modulos: "SST,CIPA",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 15:00:00",
  },
  {
    version: 178,
    titulo: "Módulo de Terceiros e Conformidade",
    descricao: "Gestão de empresas terceiras com controle de documentação obrigatória. Painel de conformidade com status por empresa. Alertas automáticos de pendências. Obrigações mensais com checklist de entrega.",
    tipo: "feature",
    modulos: "SST,Terceiros",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 16:00:00",
  },
  {
    version: 179,
    titulo: "Avaliação de Desempenho e Pesquisas",
    descricao: "Módulo de avaliação de desempenho com pilares e critérios configuráveis. Pesquisas customizadas e clima organizacional. Avaliação 360° com participantes internos e externos. Relatórios individuais e consolidados.",
    tipo: "feature",
    modulos: "RH & DP,Avaliação de Desempenho",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 17:00:00",
  },
  {
    version: 180,
    titulo: "Correção de Erros TypeScript + Filtro de Permissões",
    descricao: "Correção de 27 erros TypeScript que bloqueavam publicação em 12 arquivos. Melhoria no filtro de permissões na Home (ModuleHub) e sidebar (DashboardLayout) para respeitar grupos de usuários.",
    tipo: "bugfix",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 18:00:00",
  },
  {
    version: 181,
    titulo: "Filtros na Tela de Processos Trabalhistas",
    descricao: "Adicionados filtros funcionais por Status e por Arquivo (com/sem anexo) na tela de Processos Trabalhistas. Botão Salvar na seção de Análise IA dos Processos.",
    tipo: "melhoria",
    modulos: "Jurídico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 19:00:00",
  },
  {
    version: 182,
    titulo: "Otimização de Performance do Sistema",
    descricao: "Implementação de code splitting e lazy loading em todas as rotas. Configuração de manual chunks no Vite para melhor caching de assets. Redução significativa do bundle inicial.",
    tipo: "performance",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-03 20:00:00",
  },
  {
    version: 183,
    titulo: "Reestruturação Estoque de EPI",
    descricao: "Criação de schema de estoque central (epi_estoque_central) e estoque por obra (epi_estoque_obra). Sistema de transferências do escritório para obra. Ajuste na entrega de EPI para descontar do estoque correto. Entrada direta de EPIs em obra.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 06:00:00",
  },
  {
    version: 184,
    titulo: "Validade de EPIs + Estoque Mínimo + Checklists",
    descricao: "Controle de validade de EPIs com alertas de vencimento. Configuração de estoque mínimo por EPI/obra com alertas automáticos. Checklists de inspeção de EPIs com templates configuráveis.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 07:00:00",
  },
  {
    version: 185,
    titulo: "Relatório de Custos de EPI + Dashboard EPIs",
    descricao: "Relatório detalhado de custos de EPI por obra, funcionário e período. Dashboard de EPIs com indicadores visuais: entregas, estoque, validade, custos. Gráficos interativos com drill-down.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 08:00:00",
  },
  {
    version: 186,
    titulo: "IA para Gestão de EPIs",
    descricao: "Assistente de IA para EPIs com sugestão automática de kits por função. Matching inteligente de EPIs do catálogo com entregas. Análise preditiva de consumo. Recomendações de compra baseadas em histórico.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 09:00:00",
  },
  {
    version: 187,
    titulo: "Capacidade de Contratação por EPI",
    descricao: "Análise de capacidade de contratação baseada no estoque de EPIs. Cálculo automático de quantos funcionários podem ser contratados por função. Alertas quando estoque está abaixo do necessário para novas contratações.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 10:00:00",
  },
  {
    version: 188,
    titulo: "Correção EpiCapacidade + Alertas Automáticos",
    descricao: "Correção de crash do EpiCapacidade em mobile/produção com null checks e loading states. Card 'Cap. Contratação' no dashboard principal de EPIs. Alertas automáticos por email quando capacidade abaixo do limiar configurável.",
    tipo: "bugfix",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 11:00:00",
  },
  {
    version: 189,
    titulo: "Kit Básico Automático + Desconto EPI em Folha",
    descricao: "Kit básico de contratação configurado automaticamente para cada empresa (EPIs padrão construção civil). Seed automático do kit ao acessar Capacidade. Emails de responsáveis de compras nos alertas. Desconto automático de EPI por mau uso/perda integrado à folha de pagamento.",
    tipo: "feature",
    modulos: "SST,EPIs,RH & DP",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 12:00:00",
  },
  {
    version: 190,
    titulo: "IA Assistente nos Campos de Configuração de EPIs",
    descricao: "Rotas de IA para sugestão de kits por função, cores de capacete (NR-6/NR-18), vida útil de EPIs e treinamentos obrigatórios (NR-6/10/18/33/35). Consulta automática de Regras de Ouro, funções e catálogo como contexto para a IA.",
    tipo: "feature",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 13:00:00",
  },
  {
    version: 191,
    titulo: "Card Capacidade no Painel SST",
    descricao: "Card de Capacidade de Contratação adicionado ao Painel SST (painel inicial do módulo). Correção do filtro por obra na Capacidade.",
    tipo: "melhoria",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-04 14:00:00",
  },
  {
    version: 192,
    titulo: "Formatação pt-BR em Todos os Módulos + Fix Aniversariantes",
    descricao: "Função utilitária fmtNum() centralizada para formatação de números com separador de milhar pt-BR. Aplicada em 27 arquivos (110+ valores numéricos) — KPI cards, stats e contadores de todos os módulos. Correção do bug de aniversariantes que mostrava dia errado por usar UTC ao invés de GMT-3 (America/Sao_Paulo).",
    tipo: "bugfix",
    modulos: "Sistema,RH & DP,SST,Jurídico",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 00:00:00",
  },
  {
    version: 193,
    titulo: "Remover Seção Administração da Sidebar",
    descricao: "Removida seção ADMINISTRAÇÃO completa da sidebar de todos os módulos (Usuários/Permissões, Grupos, Auditoria, Configurações, Revisões, Lixeira). Itens continuam acessíveis pela Home e rota direta. Também removida seção Administração do módulo Avaliação de Desempenho.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 01:00:00",
  },
  {
    version: 194,
    titulo: "Atalhos EPI na Sidebar SST",
    descricao: "Adicionados 4 atalhos de EPI à sidebar do módulo SST: Checklists EPI, Descontos EPI, Transferências EPI e Config EPI. Implementado suporte a navegação direta via ?tab= com listener navParamsUpdated para trocar aba sem recarregar a página.",
    tipo: "melhoria",
    modulos: "SST,EPIs",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 02:00:00",
  },
  {
    version: 195,
    titulo: "Controle de Revisões Atualizado",
    descricao: "Inseridas 27 novas revisões (168 a 194) no banco de dados do Controle de Revisões. Histórico completo e atualizado.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 02:30:00",
  },
  {
    version: 196,
    titulo: "Auto-Sync de Revisões no Startup",
    descricao: "Automatização da inserção de revisões no banco de dados. Ao iniciar o servidor, o sistema compara o changelog em código com as revisões no banco e insere automaticamente as que faltam. Não é mais necessário inserir revisões manualmente no banco.",
    tipo: "melhoria",
    modulos: "Sistema",
    criadoPor: "Sistema",
    dataPublicacao: "2026-03-05 03:00:00",
  },
];
