/**
 * Normalização de nomes de cidades brasileiras.
 *
 * Regras:
 *   1. Trim + colapsar espaços múltiplos
 *   2. Buscar na tabela de municípios (chave = sem acento, sem caixa)
 *   3. Se não encontrar, aplicar Title Case português (artigos/preposições minúsculos)
 *
 * Usado no backend (createEmployee / updateEmployee) e no frontend (onBlur do campo Cidade).
 */

// ─── helpers ────────────────────────────────────────────────────────────────

/** Remove acentos e converte para minúsculas — chave de busca */
export function toKey(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ");
}

const LOWER_WORDS = new Set(["de", "da", "do", "das", "dos", "e", "em"]);

/** Title Case português: preposições/artigos minúsculos exceto 1ª palavra */
function titleCasePT(s: string): string {
  return s
    .toLowerCase()
    .split(" ")
    .map((w, i) => {
      if (w === "") return w;
      if (i > 0 && LOWER_WORDS.has(w)) return w;
      return w.charAt(0).toUpperCase() + w.slice(1);
    })
    .join(" ");
}

// ─── Tabela de municípios brasileiros ────────────────────────────────────────
// Chave = toKey(nome correto), Valor = nome oficial com acentos e grafia correta.
// Cobertura prioritária: São Paulo / Vale do Paraíba / principais capitais / todo Brasil.

const MUNICIPIOS: Record<string, string> = {
  // ── Vale do Paraíba (SP) ──────────────────────────────────────────────────
  "guaratingueta": "Guaratinguetá",
  "taubate": "Taubaté",
  "cacapava": "Caçapava",
  "jacaret": "Jacareí",
  "jacarei": "Jacareí",
  "sao jose dos campos": "São José dos Campos",
  "lorena": "Lorena",
  "aparecida": "Aparecida",
  "potim": "Potim",
  "cruzeiro": "Cruzeiro",
  "roseira": "Roseira",
  "pindamonhangaba": "Pindamonhangaba",
  "silveiras": "Silveiras",
  "areias": "Areias",
  "sao jose do barreiro": "São José do Barreiro",
  "bananal": "Bananal",
  "arapeı": "Arapeí",
  "arapeí": "Arapeí",
  "sao luis do paraitinga": "São Luís do Paraitinga",
  "lagoinha": "Lagoinha",
  "natividade da serra": "Natividade da Serra",
  "paraibuna": "Paraibuna",
  "redenção da serra": "Redenção da Serra",
  "redencao da serra": "Redenção da Serra",
  "salesopolis": "Salesópolis",
  "salesopolis": "Salesópolis",
  "santa branca": "Santa Branca",
  "guararema": "Guararema",
  "mogi das cruzes": "Mogi das Cruzes",
  "bertioga": "Bertioga",
  "caraguatatuba": "Caraguatatuba",
  "ubatuba": "Ubatuba",
  "ilhabela": "Ilhabela",
  "sao sebastiao": "São Sebastião",
  "cunha": "Cunha",
  "queluz": "Queluz",
  "lavrinhas": "Lavrinhas",
  "arapeí": "Arapeí",
  "miracatu": "Miracatu",
  "campos do jordao": "Campos do Jordão",
  "campos do jordão": "Campos do Jordão",
  "santo antonio do pinhal": "Santo Antônio do Pinhal",
  "santo antonio do pinhal": "Santo Antônio do Pinhal",
  "sao bento do sapucai": "São Bento do Sapucaí",
  "sao bento do sapucaí": "São Bento do Sapucaí",
  "monteiro lobato": "Monteiro Lobato",
  "tremembe": "Tremembé",
  "tremembé": "Tremembé",

  // ── Grande SP ─────────────────────────────────────────────────────────────
  "sao paulo": "São Paulo",
  "guarulhos": "Guarulhos",
  "campinas": "Campinas",
  "sao bernardo do campo": "São Bernardo do Campo",
  "santo andre": "Santo André",
  "santo andré": "Santo André",
  "osasco": "Osasco",
  "sao caetano do sul": "São Caetano do Sul",
  "diadema": "Diadema",
  "maua": "Mauá",
  "mauá": "Mauá",
  "carapicuiba": "Carapicuíba",
  "carapicuíba": "Carapicuíba",
  "barueri": "Barueri",
  "taboao da serra": "Taboão da Serra",
  "taboão da serra": "Taboão da Serra",
  "embu das artes": "Embu das Artes",
  "itapevi": "Itapevi",
  "cotia": "Cotia",
  "santana de parnaiba": "Santana de Parnaíba",
  "santana de parnaíba": "Santana de Parnaíba",
  "itaquaquecetuba": "Itaquaquecetuba",
  "suzano": "Suzano",
  "poá": "Poá",
  "poa": "Poá",
  "ferraz de vasconcelos": "Ferraz de Vasconcelos",
  "ribeirao pires": "Ribeirão Pires",
  "ribeirão pires": "Ribeirão Pires",
  "rio grande da serra": "Rio Grande da Serra",
  "mairipora": "Mairiporã",
  "mairiporã": "Mairiporã",
  "francisco morato": "Francisco Morato",
  "franco da rocha": "Franco da Rocha",
  "caieiras": "Caieiras",
  "aruja": "Arujá",
  "arujá": "Arujá",
  "biritiba mirim": "Biritiba-Mirim",
  "biritiba-mirim": "Biritiba-Mirim",
  "guararapes": "Guararapes",
  "pirapora do bom jesus": "Pirapora do Bom Jesus",

  // ── Interior SP ───────────────────────────────────────────────────────────
  "ribeirao preto": "Ribeirão Preto",
  "ribeirão preto": "Ribeirão Preto",
  "sorocaba": "Sorocaba",
  "jundiai": "Jundiaí",
  "jundiaí": "Jundiaí",
  "piracicaba": "Piracicaba",
  "bauru": "Bauru",
  "marilia": "Marília",
  "marília": "Marília",
  "aracatuba": "Araçatuba",
  "araçatuba": "Araçatuba",
  "sao jose do rio preto": "São José do Rio Preto",
  "presidente prudente": "Presidente Prudente",
  "limeira": "Limeira",
  "americana": "Americana",
  "itu": "Itu",
  "indaiatuba": "Indaiatuba",
  "tatui": "Tatuí",
  "tatuí": "Tatuí",
  "botucatu": "Botucatu",
  "itapetininga": "Itapetininga",
  "registro": "Registro",
  "iguape": "Iguape",
  "ilha comprida": "Ilha Comprida",
  "itanhaem": "Itanhaém",
  "itanhaém": "Itanhaém",
  "mongagua": "Mongaguá",
  "mongaguá": "Mongaguá",
  "itarare": "Itararé",
  "itararé": "Itararé",
  "ourinhos": "Ourinhos",
  "assis": "Assis",
  "lins": "Lins",
  "avanhandava": "Avanhandava",
  "birigui": "Birigui",
  "penapolis": "Penápolis",
  "penápolis": "Penápolis",
  "andradina": "Andradina",
  "mirassol": "Mirassol",
  "votuporanga": "Votuporanga",
  "fernandopolis": "Fernandópolis",
  "fernandópolis": "Fernandópolis",
  "afrania": "Afrânio",
  "olimpia": "Olímpia",
  "olímpia": "Olímpia",
  "catanduva": "Catanduva",
  "bebedouro": "Bebedouro",
  "matao": "Matão",
  "matão": "Matão",
  "araraquara": "Araraquara",
  "sao carlos": "São Carlos",
  "rio claro": "Rio Claro",
  "pirassununga": "Pirassununga",
  "leme": "Leme",
  "araras": "Araras",
  "cordeiropolis": "Cordeirópolis",
  "santa barbara d'oeste": "Santa Bárbara d'Oeste",
  "santa barbara d oeste": "Santa Bárbara d'Oeste",
  "americana": "Americana",
  "hortolândia": "Hortolândia",
  "hortolândia": "Hortolândia",
  "hortolandia": "Hortolândia",
  "paulinia": "Paulínia",
  "paulínia": "Paulínia",
  "sumare": "Sumaré",
  "sumaré": "Sumaré",
  "cosmopolis": "Cosmópolis",
  "cosmópolis": "Cosmópolis",
  "atibaia": "Atibaia",
  "bragança paulista": "Bragança Paulista",
  "braganca paulista": "Bragança Paulista",
  "itatiba": "Itatiba",
  "valinhos": "Valinhos",
  "vinhedo": "Vinhedo",
  "louveira": "Louveira",
  "itupeva": "Itupeva",
  "jambeiro": "Jambeiro",
  "serrinha dos pintos": "Serrinha dos Pintos",
  "brotas": "Brotas",
  "dois corregos": "Dois Córregos",
  "dois córregos": "Dois Córregos",
  "mineiros do tieté": "Mineiros do Tietê",
  "mineiros do tiete": "Mineiros do Tietê",

  // ── Litoral SP ────────────────────────────────────────────────────────────
  "santos": "Santos",
  "sao vicente": "São Vicente",
  "praia grande": "Praia Grande",
  "guaruja": "Guarujá",
  "guarujá": "Guarujá",
  "cubatão": "Cubatão",
  "cubatao": "Cubatão",
  "peruibe": "Peruíbe",
  "peruíbe": "Peruíbe",

  // ── Minas Gerais ──────────────────────────────────────────────────────────
  "belo horizonte": "Belo Horizonte",
  "uberlandia": "Uberlândia",
  "uberlândia": "Uberlândia",
  "contagem": "Contagem",
  "juiz de fora": "Juiz de Fora",
  "betim": "Betim",
  "montes claros": "Montes Claros",
  "ribeirao das neves": "Ribeirão das Neves",
  "ribeirão das neves": "Ribeirão das Neves",
  "uberaba": "Uberaba",
  "governador valadares": "Governador Valadares",
  "ipatinga": "Ipatinga",
  "sete lagoas": "Sete Lagoas",
  "divinopolis": "Divinópolis",
  "divinópolis": "Divinópolis",
  "santa luzia": "Santa Luzia",
  "ibirité": "Ibirité",
  "ibirite": "Ibirité",
  "sabara": "Sabará",
  "sabará": "Sabará",
  "vespasiano": "Vespasiano",
  "nova lima": "Nova Lima",
  "itabira": "Itabira",
  "caete": "Caeté",
  "caeté": "Caeté",
  "pocos de caldas": "Poços de Caldas",
  "poços de caldas": "Poços de Caldas",
  "varginha": "Varginha",
  "passos": "Passos",
  "itajuba": "Itajubá",
  "itajubá": "Itajubá",
  "alfenas": "Alfenas",
  "lavras": "Lavras",
  "tres coracoes": "Três Corações",
  "três corações": "Três Corações",
  "sao joao del rei": "São João del-Rei",
  "sao joão del rei": "São João del-Rei",
  "tiradentes": "Tiradentes",
  "ouro preto": "Ouro Preto",
  "mariana": "Mariana",
  "congonhas": "Congonhas",
  "conselheiro lafaiete": "Conselheiro Lafaiete",
  "barbacena": "Barbacena",
  "leopoldina": "Leopoldina",
  "muriae": "Muriaé",
  "muriaé": "Muriaé",
  "cataguases": "Cataguases",
  "visconde do rio branco": "Visconde do Rio Branco",
  "uba": "Ubá",
  "ubá": "Ubá",
  "formiga": "Formiga",
  "patos de minas": "Patos de Minas",
  "araguari": "Araguari",
  "araxá": "Araxá",
  "araxa": "Araxá",
  "ituiutaba": "Ituiutaba",
  "caratinga": "Caratinga",
  "igarape": "Igarapé",
  "igarapé": "Igarapé",

  // ── Rio de Janeiro ─────────────────────────────────────────────────────────
  "rio de janeiro": "Rio de Janeiro",
  "sao goncalo": "São Gonçalo",
  "são gonçalo": "São Gonçalo",
  "duque de caxias": "Duque de Caxias",
  "nova iguacu": "Nova Iguaçu",
  "nova iguaçu": "Nova Iguaçu",
  "belford roxo": "Belford Roxo",
  "niteroi": "Niterói",
  "niterói": "Niterói",
  "campos dos goytacazes": "Campos dos Goytacazes",
  "petropolis": "Petrópolis",
  "petrópolis": "Petrópolis",
  "volta redonda": "Volta Redonda",
  "mage": "Magé",
  "magé": "Magé",
  "itaborai": "Itaboraí",
  "itaboraí": "Itaboraí",
  "mesquita": "Mesquita",
  "queimados": "Queimados",
  "nova friburgo": "Nova Friburgo",
  "teresopolis": "Teresópolis",
  "teresópolis": "Teresópolis",
  "barra mansa": "Barra Mansa",
  "angra dos reis": "Angra dos Reis",
  "paraty": "Paraty",
  "resende": "Resende",
  "itatiaia": "Itatiaia",
  "pirai": "Piraí",
  "piraí": "Piraí",
  "valença": "Valença",
  "valenca": "Valença",
  "porciuncula": "Porciúncula",
  "porciúncula": "Porciúncula",
  "sao joao de meriti": "São João de Meriti",
  "são joão de meriti": "São João de Meriti",
  "caxias": "Duque de Caxias",
  "nilopolis": "Nilópolis",
  "nilópolis": "Nilópolis",

  // ── Capitais e principais cidades Brasil ──────────────────────────────────
  "brasilia": "Brasília",
  "brasília": "Brasília",
  "salvador": "Salvador",
  "fortaleza": "Fortaleza",
  "manaus": "Manaus",
  "curitiba": "Curitiba",
  "recife": "Recife",
  "porto alegre": "Porto Alegre",
  "goiania": "Goiânia",
  "goiânia": "Goiânia",
  "belem": "Belém",
  "belém": "Belém",
  "florianopolis": "Florianópolis",
  "florianópolis": "Florianópolis",
  "sao luis": "São Luís",
  "são luís": "São Luís",
  "maceio": "Maceió",
  "maceió": "Maceió",
  "natal": "Natal",
  "teresina": "Teresina",
  "campo grande": "Campo Grande",
  "joao pessoa": "João Pessoa",
  "joão pessoa": "João Pessoa",
  "aracaju": "Aracaju",
  "porto velho": "Porto Velho",
  "cuiaba": "Cuiabá",
  "cuiabá": "Cuiabá",
  "macapa": "Macapá",
  "macapá": "Macapá",
  "rio branco": "Rio Branco",
  "palmas": "Palmas",
  "boa vista": "Boa Vista",

  // ── Paraná ────────────────────────────────────────────────────────────────
  "londrina": "Londrina",
  "maringa": "Maringá",
  "maringá": "Maringá",
  "ponta grossa": "Ponta Grossa",
  "cascavel": "Cascavel",
  "sao jose dos pinhais": "São José dos Pinhais",
  "foz do iguacu": "Foz do Iguaçu",
  "foz do iguaçu": "Foz do Iguaçu",
  "colombo": "Colombo",
  "guarapuava": "Guarapuava",
  "paranagua": "Paranaguá",
  "paranaguá": "Paranaguá",
  "araucaria": "Araucária",
  "araucária": "Araucária",
  "toledo": "Toledo",
  "apucarana": "Apucarana",
  "campo mourao": "Campo Mourão",
  "campo mourão": "Campo Mourão",
  "umuarama": "Umuarama",

  // ── Santa Catarina ────────────────────────────────────────────────────────
  "joinville": "Joinville",
  "blumenau": "Blumenau",
  "sao jose": "São José",
  "criciuma": "Criciúma",
  "criciúma": "Criciúma",
  "chapeco": "Chapecó",
  "chapecó": "Chapecó",
  "itajai": "Itajaí",
  "itajaí": "Itajaí",
  "jaraguá do sul": "Jaraguá do Sul",
  "jaraguà do sul": "Jaraguá do Sul",
  "lages": "Lages",
  "balneario camboriu": "Balneário Camboriú",
  "balneário camboriú": "Balneário Camboriú",
  "tubarao": "Tubarão",
  "tubarão": "Tubarão",
  "palhoça": "Palhoça",
  "palhoca": "Palhoça",

  // ── Rio Grande do Sul ─────────────────────────────────────────────────────
  "canoas": "Canoas",
  "pelotas": "Pelotas",
  "caxias do sul": "Caxias do Sul",
  "santa maria": "Santa Maria",
  "gravataí": "Gravataí",
  "gravatai": "Gravataí",
  "viamao": "Viamão",
  "viamão": "Viamão",
  "novo hamburgo": "Novo Hamburgo",
  "sao leopoldo": "São Leopoldo",
  "rio grande": "Rio Grande",
  "alvorada": "Alvorada",
  "passo fundo": "Passo Fundo",
  "sapucaia do sul": "Sapucaia do Sul",
  "uruguaiana": "Uruguaiana",
  "santa cruz do sul": "Santa Cruz do Sul",
  "cachoeirinha": "Cachoeirinha",
  "bento gonçalves": "Bento Gonçalves",
  "bento goncalves": "Bento Gonçalves",
  "erechim": "Erechim",
  "ijui": "Ijuí",
  "ijuí": "Ijuí",
  "cruz alta": "Cruz Alta",
  "bagé": "Bagé",
  "bage": "Bagé",

  // ── Bahia ─────────────────────────────────────────────────────────────────
  "feira de santana": "Feira de Santana",
  "vitoria da conquista": "Vitória da Conquista",
  "vitória da conquista": "Vitória da Conquista",
  "camacari": "Camaçari",
  "camaçari": "Camaçari",
  "jequie": "Jequié",
  "jequié": "Jequié",
  "ilheus": "Ilhéus",
  "ilhéus": "Ilhéus",
  "itabuna": "Itabuna",
  "porto seguro": "Porto Seguro",
  "lauro de freitas": "Lauro de Freitas",
  "simoes filho": "Simões Filho",
  "simões filho": "Simões Filho",
  "teixeira de freitas": "Teixeira de Freitas",
  "barreiras": "Barreiras",

  // ── Pernambuco ────────────────────────────────────────────────────────────
  "olinda": "Olinda",
  "caruaru": "Caruaru",
  "petrolina": "Petrolina",
  "paulista": "Paulista",
  "cabo de santo agostinho": "Cabo de Santo Agostinho",
  "camaragibe": "Camaragibe",
  "jaboatao dos guararapes": "Jaboatão dos Guararapes",
  "jaboatão dos guararapes": "Jaboatão dos Guararapes",

  // ── Ceará ─────────────────────────────────────────────────────────────────
  "caucaia": "Caucaia",
  "maracanau": "Maracanaú",
  "maracanaú": "Maracanaú",
  "juazeiro do norte": "Juazeiro do Norte",
  "sobral": "Sobral",
  "crato": "Crato",

  // ── Goiás ─────────────────────────────────────────────────────────────────
  "aparecida de goiania": "Aparecida de Goiânia",
  "aparecida de goiânia": "Aparecida de Goiânia",
  "anapolis": "Anápolis",
  "anápolis": "Anápolis",
  "rio verde": "Rio Verde",
  "luziania": "Luziânia",
  "luziânia": "Luziânia",
  "valparaiso de goias": "Valparaíso de Goiás",
  "valparaíso de goiás": "Valparaíso de Goiás",

  // ── Espírito Santo ────────────────────────────────────────────────────────
  "vitoria": "Vitória",
  "vitória": "Vitória",
  "vila velha": "Vila Velha",
  "serra": "Serra",
  "cariacica": "Cariacica",
  "cachoeiro de itapemirim": "Cachoeiro de Itapemirim",
  "linhares": "Linhares",
  "sao mateus": "São Mateus",

  // ── Mato Grosso / MS ──────────────────────────────────────────────────────
  "varzea grande": "Várzea Grande",
  "várzea grande": "Várzea Grande",
  "rondonopolis": "Rondonópolis",
  "rondonópolis": "Rondonópolis",
  "dourados": "Dourados",
  "tres lagoas": "Três Lagoas",
  "três lagoas": "Três Lagoas",
  "corumba": "Corumbá",
  "corumbá": "Corumbá",

  // ── Pará ─────────────────────────────────────────────────────────────────
  "ananindeua": "Ananindeua",
  "santarem": "Santarém",
  "santarém": "Santarém",
  "maraba": "Marabá",
  "marabá": "Marabá",
  "castanhal": "Castanhal",
  "parauapebas": "Parauapebas",

  // ── Maranhão ──────────────────────────────────────────────────────────────
  "imperatriz": "Imperatriz",
  "timon": "Timon",
  "caxias": "Caxias",
  "codó": "Codó",
  "codo": "Codó",

  // ── Outros ────────────────────────────────────────────────────────────────
  "petrolina": "Petrolina",
  "juazeiro": "Juazeiro",
  "arapiraca": "Arapiraca",
  "mossoro": "Mossoró",
  "mossoró": "Mossoró",
  "campina grande": "Campina Grande",
  "caicó": "Caicó",
  "caico": "Caicó",
  "parnaiba": "Parnaíba",
  "parnaíba": "Parnaíba",
  "picos": "Picos",
  "floriano": "Floriano",
  "balsas": "Balsas",
  "bacabal": "Bacabal",
  "açailandia": "Açailândia",
  "acailandia": "Açailândia",
  "porto nacional": "Porto Nacional",
  "araguaina": "Araguaína",
  "araguaína": "Araguaína",
  "guaraí": "Guaraí",
  "guarai": "Guaraí",
  "paraiso do tocantins": "Paraíso do Tocantins",
  "paraíso do tocantins": "Paraíso do Tocantins",
  "gurupi": "Gurupi",
  "ji-parana": "Ji-Paraná",
  "ji-paraná": "Ji-Paraná",
  "ariquemes": "Ariquemes",
  "vilhena": "Vilhena",
  "cacoal": "Cacoal",
  "sinop": "Sinop",
  "sorriso": "Sorriso",
  "lucas do rio verde": "Lucas do Rio Verde",
  "alta floresta": "Alta Floresta",
  "tangara da serra": "Tangará da Serra",
  "tangará da serra": "Tangará da Serra",
  "barra do garcas": "Barra do Garças",
  "barra do garças": "Barra do Garças",
  "parintins": "Parintins",
  "itacoatiara": "Itacoatiara",
  "tefé": "Tefé",
  "tefe": "Tefé",
  "tabatinga": "Tabatinga",
  "cruzeiro do sul": "Cruzeiro do Sul",
  "rio branco": "Rio Branco",
  "senador guiomard": "Senador Guiomard",
  "boa vista": "Boa Vista",
  "caracarai": "Caracaraí",
  "caracaraí": "Caracaraí",
  "oiapoque": "Oiapoque",
  "laranjal do jari": "Laranjal do Jari",
};

// ─── Função principal ────────────────────────────────────────────────────────

/**
 * Normaliza um nome de cidade para o padrão oficial:
 * - Primeira letra de cada palavra em maiúsculo (exceto preposições)
 * - Acentos corretos conforme grafia oficial do IBGE
 * - Trim + colapso de espaços múltiplos
 *
 * @param cidade - valor bruto digitado pelo usuário
 * @returns nome normalizado, ou string vazia se entrada vazia
 */
export function normalizeCidadeInput(cidade: string | null | undefined): string {
  if (!cidade) return "";
  const trimmed = cidade.trim().replace(/\s+/g, " ");
  if (!trimmed) return "";

  const key = toKey(trimmed);
  if (MUNICIPIOS[key]) return MUNICIPIOS[key];

  // Não encontrado na tabela → aplica Title Case português
  return titleCasePT(trimmed);
}
